background/constants/index.ts, background/lib/erc721.ts, background/lib/utils/index.ts, background/main.ts, background/redux-slices/accounts.ts, background/services/index.ts, background/services/name/index.ts, background/types.ts, ui/components/TopMenu/TopMenu.tsx, ui/components/TopMenu/TopMenuProfileButton.tsx
An implementation of reverse ENS resolution, enabling ENS nicknames and avatars in the menu.
Includes
Doesn't include
- A way to add a new read-only wallet by ENS name or to send funds to an ENS name (#411)
- Any sort of "address book" functionality
Closes #12
Closes #414
=> 📛 The Names of Things: Look up ENS names and avatars for new wallets

manifest/manifest.development.json, manifest/manifest.json
The content script is not yet ready to be released so we want to keep it confined into development mode. 
For this separation we use modes to handle different setups in the manifest.json
https://github.com/tallycash/tally-extension/blob/main/webpack.config.ts#L153
This PR moves the content script from the main manifest.json file into manifest.development.json so it get's picked up in development mode, but won't be included when we release a new version to the chrome store.
=> Move the content script into manifest.development.json

ui/pages/Overview.tsx
Previously, the top section felt to users as if something was cut off the top of the screen. So the design has been updated. Based on the changes to the design in Figma,
=> 🗺 Quick overview tab style update

background/lib/alchemy.ts
In certain cases, Alchemy returns token balance data with a token
balance of `0x`. In these cases, Alchemy has no data for the token
balance in question—however, that data may be available elsewhere.
Originally, this result was converted into a 0 balance, which would
result in updating the recorded balance elsewhere in the extension
to 0, manifesting in the token “disappearing”. getTokenBalances now
discards these entries entirely, letting any existing balance stand
on its own.
=> Don't bubble out empty token balances from Alchemy

background/assets.ts, background/lib/alchemy.ts, background/lib/prices.ts, background/redux-slices/utils/asset-utils.ts, background/services/base.ts, background/services/chain/index.ts, background/services/indexing/index.ts, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/Core/CorePage.tsx, ui/components/Overview/OverviewAssetsTable.tsx, ui/components/TabBar/TabBar.tsx, ui/components/TopMenu/TopMenu.tsx, ui/components/TopMenu/TopMenuProfileButton.tsx, ui/components/TopMenu/TopMenuProtocolSwitcher.tsx
During testing, we realized the asset price point conversions landed
in #490 weren't working quite as expected. This PR fixes that issue, as
well as a handful of others:
- All remaining React warnings in common paths are gone.
- Certain lookups that were waiting 1 minute to run due to being hooked up
as alarms now run immediately.
- Initial balance checks for a new account are immediately followed by price
checks for those assets.
=> Fix Fairy: Fix a few nits and bugs in current main

background/services/chain/index.ts, env.d.ts, manifest/manifest.development.json, manifest/manifest.json, src/window-provider.ts
This PR will integrate the window-provider and provider-bridge into the published extension.
The window-provider is still behind a feature flag so it does not introduce issues until the integration is ready.
To enable the integration the isTallyWindowProviderEnabled has to be set to true in the local storage of the given page.
* moved the content script into the main manifest.json — solving the CORS issues as well
* added typing for the window provider because that's always a cosy feeling
* added window.tally
* switched to the websocket provider so subscriptions can also work
=> 🐝  the change: let's give our beloved OGs some dApp goodies

ui/components/Shared/SharedBackButton.tsx, ui/pages/Onboarding/OnboardingAddWallet.tsx, ui/pages/Onboarding/OnboardingImportMetamask.tsx
I had committed the sin of using a fixed position in a shared component. This ended up breaking its display on the single asset page. No longer must we suffer after PR!
For now, it leaves the "back" button text in for all uses. We could add a prop to turn this on and off.
=> 👻 Fix back button gore

background/index.ts, background/redux-slices/accounts.ts, background/redux-slices/index.ts, background/redux-slices/selectors/accountsSelectors.ts, background/redux-slices/selectors/index.ts, src/background-ui.ts, ui/components/AccountsNotificationPanel/AccountsNotificationPanel.tsx, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccountItem.tsx, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/Shared/SharedProgressIndicator.tsx, ui/components/TopMenu/TopMenuProfileButton.tsx, ui/components/Wallet/WalletActivityList.tsx, ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx, ui/pages/Overview.tsx, ui/pages/Send.tsx, ui/pages/SingleAsset.tsx, ui/pages/Swap.tsx, ui/pages/Wallet.tsx
This PR fils in the remaining data in the account selector, as
well as adjusting the wallet and single asset tabs to only display
balances and activity related to the currently-selected account. In
the process, almost all of the combined activity-related code in the
accounts slice is removed, since it was meant to populate this view,
which was never meant to display data across accounts.
The other large refactor here was the introduction of the
`accountsSelectors` file, following @henryboldi's example with the
`activitiesSelectors` file. Both of these are exposed at the top level
via a re-exporting `background/redux-slices/selectors` package that
exposes all internal selectors for the UI to use, which has allowed
some cleanup in typing dependencies to take place (in particular,
allowing …
=> Wen Account Selector: Fill in the rest of the account selector data, adjust the wallet tab to only display current account

background/main.ts, background/redux-slices/keyrings.ts, background/services/keyring/encryption.ts, background/services/keyring/index.ts, background/tests/keyring-integration.test.ts
From the first commit message:
The service supports autolocking depending on internal and external
idle times. Currently both are set to 30 minutes, but although the
markOutsideActivity method exists on the service, it is not yet being
called by any external caller, so the keyring is locked for max 30
minutes no matter what.
This PR also bumps our PBKDF2 iterations per the Least Authority audit.
See #423 .
=> Custodian: Add keyring service autolock and track status in keyrings slice

manifest/manifest.json, package.json
This permission isn't currently used by the extension, which has
led to rejection in the Chrome store. Drop it since we don't need
it.
Also included: 
* 🎨 New onboarding and settings paint
* 🚧 Improved infrastructure for autolocking and account listing
* 🐛 Firefox scrollbars, buggy button icon, and weird back button positions begone!
* 🛑 Drop notifications permission to enable Chrome store approval
=> v0.8.1: Patch fix to drop notifications permission

background/redux-slices/keyrings.ts, background/redux-slices/selectors/activitiesSelectors.ts, background/redux-slices/selectors/keyringsSelectors.ts, ui/pages/Send.tsx
Had a reversed condition here. While poking around, also found
some quick wins on optimizing selectors, and while looking at that
also found an issue with how we were setting the `from` on send
transactions.
=> Reverse Safety: Fix autolock clearing keyring metadata for good

ui/components/Keyring/KeyringSetPassword.tsx
This doesn't exactly match the updated design in Figma, and I've deviated on the copy a bit (see #577). But I think these copy changes make sense given that this screen isn't first in the flow.
Closes #577
=> 🔐 Update create password page copy

background/main.ts, ui/components/NetworkFees/NetworkFeesChooser.tsx
This PR updates the fee selection logic with updated multipliers, we now show the estimated amount along with a maximum that can be charged.
The animation of fees timeout has been reversed to be as per the design.
Users can now specify their custom gasLimit to be set in the transaction provided it's more than `21000`. If the user mistakenly sets lower amount, we will estimate the needed gas and update.
To be merged after #534
=> Network fees ranges and gas limit handling

background/redux-slices/dapp-permission.ts, background/services/provider-bridge/index.ts
I have set up the store in a way to be able to handle multiple dApp requests, but we are just showing the latest in the UI. 
This change overwrites the whole `permissionRequests` object with the incoming request, so we keep track only the latest request.  
The source of the problem seems to be that the store was really busy and user interaction come quicker then it could remove the previous request from the queue. The remove reducer is ran on the fulfillment of an async thunk. It's more than possible that something keeps that from finishing.
Closes #606, closes #613
=> 👻 Ghostbuster: Only store the latest dApp request in store

ui/components/NetworkFees/NetworkFeesChooser.tsx, ui/pages/SignTransaction.tsx
Fix: When user navigates to a component with `NetworkFeesChooser` the `Regular` fee option will be auto-selected.
Example:
* When user on the Send page selects `Express` as the fee option and goes to Sign and then rejects the signing he is returned to the Send page, but the fee option will be reverted back to `Regular`.
FIx: Sign page should now show the maxFeePerGas from the transaction details.
Fix: After signing the transaction users are redirected to the respective `SingleAsset` page.
=> Default fee auto-select and sign page redirect

ui/pages/SingleAsset.tsx
We still show transfers, of course, or anything that interacts directly against an asset contract. Just want to avoid the ETH single asset page becoming a dumping ground for every uncategorized tx.
Closes #676
=> ⛔ Contracts Not Welcome: Don't show contract interactions per asset

ui/package.json, ui/pages/Onboarding/OnboardingImportMetamask.tsx
Please test this carefully as it interacts with the recovery phrase. Uses Ethers' `isValidMnemonic` until.
Closes #580
=> ⚠️ Add error message for invalid recovery phrase

background/main.ts, background/redux-slices/transaction-construction.ts, background/services/enrichment/index.ts, background/services/keyring/index.ts, ui/pages/Send.tsx, ui/pages/SignTransaction.tsx
Fixes an issue introduced in #694 where the keyring status in a fresh extension install was unlocked rather than uninitialized. Also fixes an issue where transaction enrichment would fail for token approvals due to a misnamed parameter.
Finally, fixes #692.
=> More Bags to Grab Redux: A fix for a keyring status change and an enrichment approval parameter, oh and also a showstopper fix

ui/components/NetworkFees/NetworkFeesChooser.tsx
Networks fees were showing too high in $$,because in order to work with bigInts the multipliers were converted into bigInts so 1.3 = 13n but after calculating the value was not divided by 10 so we were actually showing fees x13 not x1.3. This PR fixes that by adding a division by `10n`.
=> Correct fee value display

ui/components/Shared/SharedCurrentAccountInformation.tsx, ui/components/Shared/SharedPanelAccountItem.tsx, ui/components/Snackbar/Snackbar.tsx, ui/components/Wallet/WalletAccountBalanceControl.tsx, ui/components/Wallet/WalletActivityList.tsx, ui/pages/Onboarding/OnboardingImportMetamask.tsx, ui/pages/SignTransaction.tsx
=> 🏀 Buzzer beaters

background/main.ts, background/redux-slices/transaction-construction.ts, background/services/internal-ethereum-provider/index.ts, background/services/provider-bridge/index.ts, ui/pages/SignTransaction.tsx
Also fixes some corner cases where an RPC request could fail
but the calling dApp would never find out about it.
Fixes #690.
=> Rejectamundo: Proper support for transaction signing rejection

background/services/chain/utils.ts, background/services/indexing/index.ts
When transactions near the chain tip with a successful status are
seen, the indexing service now schedules a token balance lookup to
occur within 1 minute. This should ensure that any transactions that
affect balances update the balance in relatively short order, even if
we don't have enough insight into the transaction itself to locally
handle those updates.
~~Fixes~~ Refs #707 .
=> Alarming Balances: Update balances when transactions are confirmed

ui/components/Shared/SharedAssetInput.tsx, ui/components/Shared/SharedCurrentAccountInformation.tsx
Two **tiny** tweaks derived from real problems.
Currently there's a mental disconnect in the top nav wallet info provided, in
the dApp UI (shorted address) and our wallet (dog name), leaving users to
wonder. Basically, it's inconvenient to coordinate what's seen to make
decisions. In ~~buzzword~~ cognitive psychology terms, the cognitive load is too
high!
So, for #714, we've brought back the shortened address in the top menu.
But if you've got an ENS name, let's keep that because:
1) They're lovely.
2) They're what's expected. That's what dApps are displaying.
As for the code, this is resolved in literally one line change. Why? It's easy!
It's simple! But also, for real, once our account switcher names can be edited,
perhaps we'd like to bring back defaulting to the names. To be …
=> 🐶 In top bar, replace dog name w/ shortened address

background/redux-slices/selectors/accountsSelectors.ts, background/redux-slices/selectors/dappPermissionSelectors.ts, background/redux-slices/utils/activity-utils.ts, background/services/provider-bridge/db.ts, background/services/provider-bridge/index.ts, ui/components/Shared/SharedCurrentAccountInformation.tsx, ui/components/SignTransaction/SignTransactionNetworkAccountInfoTopBar.tsx, ui/components/TopMenu/TopMenuProfileButton.tsx, ui/pages/SignTransaction.tsx
This is essentially the same PR as #728 and solves the transaction parts,
but rebased on top of #731 which solves the underlying dapp selection issue.
From the original PR written by @Shadowfiend 
---
The approach here roughly follows what I outlined in [this comment](https://github.com/tallycash/extension/issues/705#issuecomment-996413752).
In particular:
- The provider bridge only reports authorized addresses to dApps, not all
wallet addresses. This bug could leak information.
- The provider bridge instantly rejects any signature requests for a
transaction whose `from` address is not authorized. This occurs before
the transaction transitions into the internal provider.
- The dApp connection icon in the header only appears if the current tab's
origin is authorized to access the …
=> Quicksand Accounting Remastered: Improve handling of dApp connections with multiple accounts 

ui/components/Keyring/KeyringSetPassword.tsx, ui/components/Keyring/KeyringUnlock.tsx, ui/components/NetworkFees/NetworkFeesChooser.tsx, ui/components/Shared/SharedInput.tsx, ui/hooks.ts, ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx, ui/public/popup.html
Of note, I added a `useRunOnFirstRender` hook. I've added it because the
`useEffect` approach of passing `[]` hits snag here — the functions need to be
passed, which breaks it running only on first render.
- `SharedInput` now can accept a default value
- The animated label can adapt to different backgrounds, like in a slide up
menu
- The label will turn red on an error
=> ✨ Fancy input labels

background/lib/alchemy.ts
A couple bad token contracts were preventing us from balance checking the entire token list. This should handle it.
Closes #746
=> Alchemical Misadventures: Loosen the Alchemy API validation to allow errors

background/lib/alchemy.ts, background/services/indexing/index.ts
This PR fixes the ETH balance update once a transaction is completed.
Users should see the new balance within one minute from the transaction confirmation.
=> Pull updated ETH balance after transaction

background/redux-slices/selectors/accountsSelectors.ts
We always want to show ETH balance regardless of its amount.
=> Fix a bug where low balance ETH would be hidden

package.json, patches/jsan+3.1.13.patch, yarn.lock
Redux devtools hung after a while and was unusable for me. It happened because it did not know how to desierialise our bigint format, even though we had enhancers and whatnot.
The error pointed to [this line of code](https://github.com/kolodny/jsan/blob/master/lib/index.js#L33), which failed when it had to deal with our bigint format. When this was enhanced with our custom serialiser, redux devtools started working.
Tried to fix the issue but it was deep in the stack:
background > `remote-redux-devtools` > `redux-devtools-core` > `remotedev-serialize` > `jsan`. The problem seems to be that `redux-devtools-core` does not propagate our serialiser enhancement here. Can continue going down the rabbit hole to find a good fix but instead changed directions.
It's a simple patch, which fixes our …
=> 🔧  MacGyver Serialise: Fix redux devtools by extending with our BigInt format

background/main.ts, background/redux-slices/keyrings.ts, background/redux-slices/selectors/accountsSelectors.ts, background/redux-slices/selectors/uiSelectors.ts, background/redux-slices/ui.ts, background/services/internal-ethereum-provider/index.ts, background/services/preferences/db.ts, background/services/preferences/defaults.ts, background/services/preferences/index.ts, background/services/preferences/types.ts, background/services/provider-bridge/index.ts, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/SignTransaction/SignTransactionSignBlock.tsx, ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx
> [The **Migratory Bird Treaty Act of 1918** (MBTA), codified at 16 U.S.C. §§ 703–712 (although §709 is omitted), is a United States federal law, first enacted in 1918 to implement the convention for the protection of migratory birds between the United States and Canada .[1] The statute makes it unlawful without a waiver to pursue, hunt, take, capture, kill, or sell nearly 1,100 species of birds listed therein as migratory birds. The statute does not discriminate between live or dead birds and also grants full protection to any bird parts including feathers, eggs, and nests. A March 2020 update of the list increased the number of species to 1,093.](https://en.wikipedia.org/wiki/Migratory_Bird_Treaty_Act_of_1918) — Wikipedia
We need to do some serious refactoring to the Redux store, but we …
=> 🐦 Migratory Bird Treaty Act: Refactor the Redux store with a proposed migration mechanism

background/main.ts, background/package.json, background/redux-slices/keyrings.ts, background/services/keyring/index.ts, background/tests/keyring-integration.test.ts, yarn.lock
Backend component for the "Add Address" feature, allowing users to derive new addresses from a recovery phrase.
Ran into and squashed a small bug in `hd-keyring` along the way.
Closes #763
=> Moar Accounts Plz: Support additional address derivation in KeyringService

background/main.ts
Currently, all at once, there are hundreds of dispatches of `updateAccountBalance`. This is believed to be causing performance issues mentioned in https://github.com/tallycash/extension/issues/739. Many of these dispatched asset balances aren't needed in the store.
Still, this should cover:
- Pushing balance changes that drop to 0
- Still balance update w/ transfers that have a newly encountered asset
It now excludes dispatching asset balances that both are 0 and aren't for an already tracked asset. This saves us from a significant majority of the dispatches.
A flawed attempt to address the same problem was discussed here https://github.com/tallycash/extension/pull/353/files/f48a511bc0abba92b36ffa09d43bb2d5bbd9af11..41ad2bbd9afaabddcbc59f0528dcf50daec1298f#r733777078
Thanks to @greg-nagy …
=> 🙅 Prune `updateAccountBalance` dispatches

webpack.config.ts
The Mozilla add-on store has an automated policy preventing JS files over 4 MB. Because we use webpack, they already require a full extension source code submission every version bump... leading me to believe that minification, including mangling and compression, is the right approach for Firefox in production versus other options like chunking.
To test this PR thoroughly, make sure...
* `yarn start` works as expected
* `yarn start --config-name chrome` works as expected
* `yarn start --config-name firefox` works as expected
* `yarn build --config-name firefox` produces a zip with a `ui.js` that's smaller than `yarn build --config-name chrome`
* The productions builds behave as expected
=> 🔥🦊 Fox Kit: Minify the Firefox production build

ui/pages/Onboarding/OnboardingImportMetamask.tsx
Looks like resolving merge conflicts went wrong at some point. Noticed and fixed by @7alip in #788. I want to get this in quickly w/o needing to review/accept the other changes.
=> 🧬 Fix dispatching `importLegacyKeyring` twice

ui/pages/Onboarding/OnboardingSaveSeed.tsx
=> chore: fix typo

background/main.ts, background/services/keyring/index.ts, background/tests/keyring-integration.test.ts, ui/pages/Onboarding/OnboardingAddWallet.tsx, ui/pages/Onboarding/OnboardingSaveSeed.tsx, ui/pages/Onboarding/OnboardingVerifySeed.tsx
For now, this matches Vlad's design in terms of concept but not in the visual details. I'm unhappy about the verify phrase page's **wonky typings and repetitiveness; I've got improvements in mind to add**. That said, this is still behind a feature flag. Above all, ✨it works ✨ 😊🤞
@VladUXUI's review,
> I’m 80% happy with that, so if you don’t want to spend the time or don’t have the time to bring it closer, I’m good to leave it as an update for later
List of 24 words,
Verify 8 random words in phrase,
=> ✍️ Update recovery phrase flow to 24 words

background/assets.ts, background/lib/tokenList.ts, background/redux-slices/accounts.ts, background/redux-slices/assets.ts, background/redux-slices/utils.ts, background/services/indexing/index.ts
This is the second PR extracted from the swaps flow rework, again
rebased against main for holistic review. This one is focused on
a cleaner set of available assets, which feeds the swap buy list
in the new quote-based flow.
The outcome still isn't perfect here, and to update existing installs
will require clearing and repopulating the asset store from
`getCachedAssets`. Nonetheless, this should be a large improvement,
removing a whole swath of duplicates and irrelevant assets that were
slipping through before.
Also packaged here are a few type-level tidbits that are useful
external to the assets pipeline.
------
One thing to look at carefully: right now the new `mergeAssets` helper
merges assets by symbol if a contract address is unavailable. This
may not be the correct behavior, so …
=> Asset-ic Acid: Improve asset deduplication and merging

background/assets.ts, ui/components/Shared/SharedAssetInput.tsx, ui/components/Shared/SharedAssetItem.tsx, ui/components/Shared/SharedSlideUpMenu.tsx
Extracted these from the swap work and rebased against main for
holistic review.
Big ticket global change:
- `SharedSlideUpMenu` *only renders its children when open*! This has
high potential for unexpected bugs, though I haven't found any yet,
as I believe we weren't *depending* on the behavior of children
rendering in spite of being invisible. The motivation here was ensuring
React lifecycle hooks fired at a useful time for slide-up menu contents
(see the search input auto-focus change mentioned below).
Big ticket changes for `SharedAssetInput`:
- @henryboldi's work from #847, including search by symbol for assets.
- An expansion of this work to search/filter by contract addresses
where applicable.
- Auto-focusing of the search input when the `SharedAssetInput` asset
selector is …
=> IO Transit: Collection of improvements to SharedAssetInput

background/services/keyring/index.ts, ui/components/NetworkFees/NetworkSettingsSelect.tsx, ui/pages/SignData.tsx, ui/pages/SignTransaction.tsx, ui/utils/capitalize.ts, ui/utils/formatting.ts
When restructuring the SignTransaction page we have accidentally omitted Approval Page.
In order to avoid future unexpected outcomes from deleting type from types to be signed we now destructure it instead.
Removed eslint disable from capitalization function.
=> Signing fixes

background/redux-slices/assets.ts
This PR adds an explicit null check that fixes a bug where the 1st asset in the asset list was not having its prices populated.  Since we explicitly prepend the assets array with ETH and BTC this would always result in ETH not having its prices populated.
This was a fun one - I went down the rabbit hole into indexDb and alchemy.ts before coming back out. 🐰
Closes #813
=> Fix Edge Case When Adding Pricepoint for "0th" Asset

background/lib/fixed-point.ts, ui/components/Shared/SharedAssetInput.tsx, ui/components/Shared/SharedAssetItem.tsx, ui/components/Shared/SharedButton.tsx, ui/pages/Send.tsx, ui/pages/Swap.tsx
This PR is a bigger rework than I originally embarked on. It
implements balance info on the shared asset input, as well as
in the asset selector, and includes a max button that can be
disabled if desired (used in swaps for buy assets).
There were a couple of tangential changes included here:
- The fixed-point library's string handling is much more robust.
- `SharedAssetInput`'s “now for something completely different” option,
`isTypeDestination`, is gone in favor of custom styling in the Send
component.
The primary changes to `SharedAssetInput` are one big commit
(should really have been at least 2-3, but time ran out). Here's
the relevant commit message, which covers the details:
```
SharedAssetInput now takes an assetsAndAmounts prop, which is of a new
type, AnyAssetWithOptionalAmount …
```
=> Asset Amounty Input: Alternate approach to SharedAssetInput max/balance info

background/main.ts, background/redux-slices/ledger.ts, background/redux-slices/selectors/ledgerSelectors.ts, background/redux-slices/selectors/signingSelectors.ts, background/redux-slices/transaction-construction.ts, background/services/keyring/index.ts, background/services/ledger/index.ts, background/services/signing/index.ts, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/Shared/SharedSelect.tsx, ui/pages/Ledger/Ledger.tsx, ui/pages/Ledger/LedgerImportAccounts.tsx, ui/pages/SignTransaction.tsx
Closes #841 
* Handle the import+sign happy cases for the users who can read and follow the instructions on screen ie. unlock and have Ethereum app active, when interacting with the extension
* Onboarding of Ledger generated addresses with preprogrammed or custom derivation paths
* Checking Ledger-handled account balances and their history
* Sending _spice_ (ETH) from Ledger addresses
* Selecting between all kind of accounts
* Put every Ledger-related thing behind feature flag
* Ledger onboarding (Add wallet -> Connect to a Ledger)
* Already imported Ledger accounts in the account selector
* On import the lists of the available addresses shows fake balance (on import it is populated and refreshed correctly)
* When the extension is reran with disabled Ledger support but the last active …
=> Wire up Ledger UI and services

background/main.ts, background/redux-slices/transaction-construction.ts, ui/components/Shared/SharedAssetInput.tsx, ui/components/Snackbar/Snackbar.tsx, ui/components/Swap/SwapQuote.tsx, ui/pages/EarnDeposit.tsx, ui/pages/Send.tsx, ui/pages/Swap.tsx
This hits a few issues observed during final QA of swaps:
- Closes #937 .
- Reworks handling of transaction state so that the swap transition
to transaction signing works correctly; when transaction state
clearing became more aggressive, it left the sign transaction page
in a state where it might decide it was seeing a rejected transaction
and redirect back to the caller---not great!
- Rework selected asset handling in `SharedAssetInput` so that the
caller provides the currently-selected asset at all times (instead of
providing the starting default). This allowed the swap flip button to
correctly update the selected assets in the UI.
- Added sorting for assets in `SharedAssetInput`. Sorting without a
search term sorts alphabetically by symbol, while sorting with a search
term sorts …
=> Minty Fresh: Fix a few outstanding bugs in swaps

background/main.ts, background/redux-slices/ledger.ts
Replace fake ETH balances with real balance, when importing accounts from a Ledger.
**Implementation.** Keeps existing Redux slice and thunk. A method `getAccountEthBalanceUncached` is added to the `main` service, which, in turn, invokes `chainService.pollingProviders.ethereum.getBalance`. The thunk is changed to use this new method instead of the fake one, and the fake one is removed.
=> Show real ETH balances when importing from Ledger

background/main.ts, background/redux-slices/0x-swap.ts, background/redux-slices/transaction-construction.ts, background/services/chain/utils.ts, ui/components/Swap/SwapTransactionSettingsChooser.tsx
Fixes here for add address not working, approve transactions not
preserving network fee info from the swap page, gas price
correctness on the activity page (for new transactions; old ones
for now remain unmigrated), and a small adjustment to give more
clickable area to the swap transaction settings button.
For add address, just crack open that address dropdown and hit Add
address. If it works, it works! Make sure the build has Ledger disabled;
the issue here only shows up in those cases.
For the approve issue, go to swap and either pick a from asset that
you haven't approved yet, or zero out your approval first. Then,
change the default fee settings from Regular to Express or Instant
on the swap settings, and hit Approve asset. The selected fee on the
sign page should be the same as that …
=> Nitsy Bitsy: Fix a few nits here and there from the last release

.eslintrc.js, background/services/keyring/index.ts, background/tests/keyring-integration.test.ts, package.json, yarn.lock
This PR remotes two `it.only`'s from keyring-integration.test.ts and configured our linter to throw an error if it detects a `.only` test block.  I went into this PR with the assumption that the inactive tests were written correctly but underlying behavior had changed while they were inactive - so went with the route of changing the code to match the tests although it is certainly possible that the tests themselves need to change as well.
=> Remove .only's and fix broken integration tests

ui/components/Shared/SharedSlideUpMenu.tsx, ui/components/SignTransaction/SignTransactionContainer.tsx
Per Vlad's instructions during our UI sync
Closes #999
⚠️ Haven't written a proper description here yet
=> 🌒 Update slide up menu to always have clickable backdrop

background/redux-slices/accounts.ts, ui/pages/Swap.tsx
This PR fixes a bug where the balance showed at the top of the Swap page was showing the balance of a given token across all addresses imported to the wallet.
https://user-images.githubusercontent.com/94649004/154405873-deee7460-fb63-4db4-9c84-17d333863a2a.mov
Closes #1005
=> Balance in All Things: Show Address-specific balances in Swap page

background/services/ledger/index.ts, ui/pages/Onboarding/OnboardingAddWallet.tsx
Fixes #1035.
Hides the "Connect to a Ledger" option if `navigator.usb` is not available (or the Ledger feature flag is disabled).
=> Hide option to connect to a Ledger if WebUSB is not supported

ui/pages/SignTransaction.tsx
dApp requests for signatures caused blank screen if the current account is read-only (see below). Fixed.
=> Fix blank signing page if read-only account

background/services/ledger/index.ts, background/services/signing/index.ts
The happy path was already merged but users tend to alter from the intended use cases :)
- Serialize typed signing with other Ledger operations
- Bubble up errors for further processing when we use typed data signing
- Match Redux and LedgerService state before attempting typed signing
=> Typed signing on Ledger error handling + serialization

background/services/keyring/index.ts
Without this fix - attempting to import a wallet after first creating a new Tally wallet resulted in an exception being thrown in the background thread and the importing `status` in the Keyring Redux Slice being stuck at `pending`.
Not sure why this did not show up until after `main` was merged into #1001 - but this should fix the issue of not being able to add multiple separate `Tally` and `Import` keyrings.
To Test:
- Add a `Tally` wallet from a new Seed.
- Import a wallet from a metamask seed.
- You should see both wallets in the Account List.
- Any combination of Tally / Imported wallets should be supported.
=> Immutably Update this.#keyringMetadata to prevent exception.

background/main.ts, background/redux-slices/accounts.ts, background/services/keyring/index.ts, ui/components/AccountItem/AccountItemRemovalConfirm.tsx, ui/components/AccountItem/AccountItemSummary.tsx, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/Shared/SharedPanelAccountItem.tsx
This PR introduces the ability to remove non read-only addresses from the accounts list.  This is done through a new `#hiddenAccounts` property inside of `keyringService` that acts as a filter for what addresses to emit with keyrings when emitting via the `emitKeyrings` method.
Removed addresses are easily able to be re-added with the `+ Address` button - and addresses are not removed from `accountsToTrack` when they are removed so that users have the UX of being able to immediately see the current state of addresses they have previously hidden when unhiding them.
This PR is blocked until #1060 is merged.
https://user-images.githubusercontent.com/94649004/156622214-21e56318-0bdc-441b-ab77-a09c6fa58aad.mov
=> Enable hiding non `read-only` addresses.

ui/components/Shared/SharedAssetInput.tsx
Fixes #1038
Fixed problem with tokens list searchbox that was scrolling with the list.
Now the list is scrolling but the searchbox stays on the top.
=> Fix swap list searchbox to the top

ui/pages/Popup.tsx, ui/public/index.css, ui/public/popup.html
Fixes #924.
Flash was caused by dynamic loading of CSS.
This commit restores the popup sizing as part the static, global CSS,
but uses a popup-specific class applied to `<body>`, to avoid poisoning
the style of full-page UIs.
=> Fix flash of unsized popup

background/redux-slices/accounts.ts, background/redux-slices/keyrings.ts, background/redux-slices/selectors/accountsSelectors.ts, background/redux-slices/selectors/keyringsSelectors.ts, background/services/keyring/index.ts, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/pages/Onboarding/OnboardingVerifySeed.tsx
Per discussion in https://github.com/tallycash/extension/pull/1001.  We want to avoid using the `new seed` nomenclature.
=> Rename "NewSeed" accounts to "Internal"

.eslintrc.js
Using an underscore as a signifier for an unused variable is a common convention and our linter should allow it.  This is an extension of the current airbnb style-guide rule we are using found [here](https://github.com/iamturns/eslint-config-airbnb-typescript/blob/master/lib/shared.js#L39)
[See discussion here](https://github.com/tallycash/extension/pull/1060#discussion_r820857886).
=> Allow '_' as a variable name

.github/workflows/build.yml
Why?
At the moment the assets from main are used as release asset. 
But internal QA happens on the release branch and during the QA PRs can be merged into main.
This way the released asset is different from the QAd version which beats the purpose of the internal QA. 
(or we stop merging PRs to main during internal QA)
How? 
This way release branch generates the release build which can be used
for store uploads. This way the QAd code is the same as released.
Simplify asset upload into a single step on every branch.
=> create the same assets on release-* and main

ui/components/Shared/SharedAssetInput.tsx
This PR adds an easily customizable priority list so that when users use swaps they are not immediately presented with a bunch of AAVE tokens with no icons.  The list of assets I chose is pretty much random - I went through our lists and picked some assets that actually had icons.  Completely open to changing up the list if desired.
Open the swaps page - try selecting a buy asset - if you see UST and KEEP at the top of the list - great success!
https://user-images.githubusercontent.com/94649004/157496668-d7d5bfb8-c5be-44ca-9996-b5f80634d411.mov
=> AAAVEE AAVEE AAVE - Add prioritized asset sorting to SharedAssetInput

ui/components/Shared/SharedTooltip.tsx, ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
FIxes #726
Mark with red color infinite spend limit. User can change spend limit and it will be white. 
Add tooltip to explain spend limit role.
=> Properly display infinite token approval

background/services/chain/index.ts, background/services/indexing/index.ts
This PR fixes a regression introduced post 0.12.1  that prevented the wallet from getting _any_ token balances - as well as reduces the interval at which we check for token balances down to 1 minute (from 30).  It partially addresses the symptoms caused by #1158 but probably not the root cause.
• complete a swap for (or send yourself) a token you do not already have in your wallet
• wait a maximum of 1 minute
• the token and balance should show up in your asset list
=> So Refreshing 🍋 - Update token balances every minute.

package.json, ui/pages/Menu.tsx, webpack.config.ts, yarn.lock
https://www.youtube.com/watch?v=QVYgoejO3ac
Depending on the git to check version number during
build time proved to be a headache, so we have returned
to using the version from `package.json` file.
The idea is good though, probably should be placed into
the CI pipe as a step so the build itself does not depend
on the git tag.
(It caused issues with the firefox release and also internally)
=> 💔 It's not you: remove git dependency from the build process

ui/components/Shared/SharedAssetInput.tsx
Now that we support swapping from ETH into other ERC-20 Tokens.  The notice is no longer needed.
- Open up the Swaps page, select ETH as your `From` Asset, the notice should not be there.
=> Remove "ETH coming soon" notice

ui/components/Swap/SwapTransactionSettingsChooser.tsx
Closes #863
Since this is a setting we do not ~~have control over~~ currently allow the user to change we should just display is as a value and not a dropdown.
Before:
After:
=> Disable Editing of Slippage Tolerance in Swaps Network Settings.

ui/pages/Onboarding/OnboardingSaveSeed.tsx
This PR adds a copy to clipboard button on the save recovery phrase page. This has been a convenience feature repeatedly requested in Discord.
Closes #1192
=> 📋 Add copy to clipboard button to onboarding save phrase

ui/components/Swap/SwapQuote.tsx
Having "Execute Swap" be the verbiage for approving was causing confusion when users were presented with an additional signing page after clicking "Execute Swap".
=> Change "Execute Swap" to "Confirm Swap"

background/lib/utils/index.ts, background/services/name/index.ts, ui/components/Shared/SharedAddress.tsx, ui/components/Shared/SharedTooltip.tsx, ui/components/SignTransaction/SignTransactionSignInfoProvider.tsx, ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx, ui/components/SignTransaction/SignTransactionTransferInfoProvider.tsx, ui/components/Wallet/WalletActivityDetails.tsx
Add `SharedAddress` component and use it in transaction signing
and activity details.
Current limitations:
- Tooltip is an OS tooltip using `title`, preferences may vary.
- We don't propagate name system information and don't yet have
a design for how to tell the user which name system was used
to determine the name they see.
- Names are not resolved in as many places as might be ideal.
- There is no icon indicator that a copy is possible.
That said, anywhere a name is resolved it is displayed, tooltip
has the address, and clicking copies, so the basis for the
functionality we want is there and we are in a strictly better
place with these changes.
Screenshots:
See #649.
=> Copy Waste: Add SharedAddress component with address copying

background/lib/logger.ts, background/main.ts, background/redux-slices/transaction-construction.ts, background/services/ledger/index.ts, background/tests/keyring-integration.test.ts, provider-bridge-shared/eip-1193.ts, provider-bridge-shared/runtime-typechecks.ts, ui/components/Core/CorePage.tsx, ui/components/Onboarding/OnboardingDerivationPathSelect.tsx, ui/components/Shared/SharedSelect.tsx, ui/components/SignTransaction/SignTransactionDetailPanel.tsx, ui/components/SignTransaction/SignTransactionTransferInfoProvider.tsx, ui/components/Swap/SwapQuote.tsx, ui/components/Wallet/WalletActivityDetails.tsx, ui/pages/Popup.tsx, ui/pages/Send.tsx, ui/pages/SignTransaction.tsx, ui/pages/Swap.tsx, window-provider/index.ts
Currently this is achieved not by overlaying signing, but by
replacing the location when a signature is in progress. Overlaying
signing proved too much for an initial pass due to how complex
the CSS transition logic is and how entangled it is with the page
structure.
Note also that the keyring handling here will likely be dropped in
favor of a signing-flow-specific approach via #1165 .
A few linter fixes and a small logger improvement are also in here.
Try sending ETH, swapping, and using dApp transaction signing. All
should behave correctly.
=> Modalicious: Make transaction signing modal

ui/pages/DAppConnectRequest.tsx
waiting for the dispatch to go through resulted in a
temporary state where the actual permission has already
been cleared up, but the window was not yet closed
resulting in a protective clause to briefly show the error state
which was confusing
https://discord.com/channels/808358975287722045/888500174685614090/958726241924554823
=> 👻 False alarm: Remove brief error state from dapp connect

ui/public/index.css
Given a mismatch between how Figma's unmanaged color profile in rendered vs.
the colors rendered on the web in RGB, our implementation felt a bit dull in
comparison to the designs. After setting Figma's color profile explicitly to
sRGB we (Vlad) could pick colors that appear more vibrant, while constrained to
the color space that Chrome and Firefox can currently display. Safari has both
Chrome and Firefox beat in implementing `CSS Color Module Level 4`! So here we
are. Now we've got lovely vibrant colors selected by @VladUXUI. In fact, Vlad
sent me these colors already formatted with the code.
Kudos to Vlad —  these updated colors look like a nice boost! And to @mr-michael 
for bringing the discrepancy in saturation to our attention. It's like a layer
of dust has been wiped off 🧼
<br/> …
=> 🎨 Update colors throughout with improved saturation

ui/_locales/en/messages.json, ui/_locales/zh_TW/messages.json, ui/components/Wallet/WalletAccountBalanceControl.tsx, ui/pages/Menu.tsx, ui/utils/i18n.ts
related to #438
refer official i18n doc https://developer.chrome.com/docs/webstore/i18n/
to localize some strings
to add new locale, just add _locale/es/messages.json and copy from en/messages.json
Learned while porting:
- the message format is verbose, and json is not a good format to maintain multiple locale files. Need think about a better way to
- merge new strings for locale files 
- collaborate the translations work
- localize ui/pages/Tab.tsx broken the UI, need more tweak
- some strings (ex: `$`) need to be present as the encoded version in messages.json 
refer https://www.w3schools.com/tags/ref_urlencode.asp
=> init extension i18n support

background/lib/alchemy.ts, background/redux-slices/accounts.ts, background/services/chain/index.ts, background/services/indexing/index.ts
Direct commit message lift:
Enriched transaction annotations can give us high-certainty token
transfers for most ERC20 token transfers. In these scenarios, rather
than doing a within-1-minute balance check, the indexing service now
does an accelerated within-300-ms check for just those addresses,
which should considerably improve responsiveness to transaction
confirmation in those cases.
Additionally, fixed an issue in the accounts slice where normalized
addresses weren't being used to key into the accounts map consistently.
Balances should start behaving more consistently across the board now!
- Do some swaps and other transactions that move around ERC20s. You
should see fast balance updates fairly consistently, rather than
having to wait up to a minute.
=> Turbo Check: Implement accelerated balance checks for known transfers

background/lib/utils/index.ts, background/lib/utils/type-guards.ts, ui/pages/Send.tsx
The three helpers here are used in later PRs and likely
useful across the code base, while the alignment tweaks
fix some margin jumps that happen during ENS resolution
on the asset Send page.
Check that as you type a name/address on the Send page,
the network fee box doesn't move or jump, both while the
name/address is invalid and once it is valid or blank.
=> Helpers and alignments: Handful of helper and alignment tweaks

background/main.ts, background/services/enrichment/index.ts, background/services/enrichment/utils.ts, background/services/name/index.ts, background/services/name/name-resolver.ts, background/services/name/resolvers/ens.ts, background/services/name/resolvers/index.ts, ui/hooks/validation-hooks.ts
--> Draft until #1303 lands.
Two big differences here:
- The NameService is now able to use more than one resolver, though the
only implemented resolver is still ENS.
- Lookups generally use *OnNetwork types, and results are similarly
*OnNetwork types. Avatars are still returned as plain URLs, at least
for now.
Make sure that name resolution continues to work:
- Check that entering an ENS name resolves in the Send form.
- Check that entering an ENS name resolves in the Read-only form.
- Check that sending to an address with an ENS name correctly shows
the ENS name in the Sign Transaction page.
- Check that sending to an address with an ENS name correctly shows
the ENS name in the activity list.
=> Resolver Revolver: Introduce NameResolver and refactor NameService to use it

ui/components/Shared/SharedButton.tsx, ui/components/SignTransaction/SignTransactionContainer.tsx
This PR adds a delay to enabling the sign button when opening a sign
transaction screen. Additionally, it aims to enable/disable the sign
transaction button depending on if the window is blurred or focused, or if the
transaction details change. The idea is to make sure the user has a chance to
review the transaction and confirm there's no shenanigans before pulling the
trigger. As for implementation, this is achieved with hooks
in`SignTransactionContainer.tsx`. Granted, this enable/disable logic isn't
neatly tucked away as a single new hook of its own. That said, the
implementation feels somewhat convoluted to me. Input is welcome!
=> 🚦 Add countdown/delay on button for transaction signing

ui/pages/Swap.tsx
This PR fixes a bug where users would seemingly lose control of the buy asset's input when trying to change the buy quantity during a swap.
- Open up the Swap page
- Select a buy asset and sell asset
- Enter a quantity for the buy asset (the lower input)
- At this point you should see the quantity you entered - and the sell asset quantity should automatically populate.
=> 1 Thing You Should Never Buy Used - Use newAmount when setting the buy asset's quantity.

ui/pages/Onboarding/OnboardingInfoIntro.tsx
close #1145 
Simply replace "TallyHo" with "Tally Ho"
test in local build with firefox
@henryboldi @VladUXUI
=> fix: use Tally Ho instead of TallyHo for content

background/services/preferences/db.ts, background/services/preferences/defaults.ts
> I just tried to install the Firefox extension off the tally.cash site and my antivirus (Avast) complained it needed to abort the connection to ipfs.fleek.co due to URL:Mal threat
Fixes #1320
<table>
<tbody>
<tr>
<td>Before</td>
<td>After</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
=> ⚡️ Replace use of fleek's gateway to silly avoid virus scanner block

ui/components/Shared/SharedAssetIcon.tsx
When I updated our IPFS support in asset icons, I broke the logic that determined when to display a hardcoded asset icon 😬. This should fix it!
Closes #1333
=> 💎 Fix displaying ETH asset icon

background/main.ts
This PR addresses two bugs:
The first is a bug where we were assigning `isArbitraryDatSigningEnabled` to the root LedgerState rather than assigning it to the state of each connected device.  This did not seem to have any adverse effect on the application but it did not conform to our typing.
The second is a much rarer bug where if a user was upgrading to version 0.13.0 from a pre 0.11.0 version of tally the application would become unresponsive due to pre 0.11.0 redux-states not having the "ledger" property.
-  uninstall tally extension
- `git checkout c88495eba2299771bb8be785d99832a0a89a6e0c` (version 0.10.0)
-  build it and add it to chrome
- open it up - add a wallet (preview is fine)
- `git checkout fix-migration-six`
-  update the wallet in chrome://extensions - version should change …
=> Uh Oh - Arbitrary extension version is enabled - Fix redux-state migration.

ui/pages/Onboarding/OnboardingVerifySeed.tsx
This PR reworks the verify phrase page's logic to fix issues with duplicate
words. Several users got stuck on the verify phrase page because the interface
assumed that words in the mnemonic were unique, which isn't the case. So now
the logic is based on the index of the words, rather than the words themselves.
To test, fire up the verify phrase page many times, and see if there's anything
funky. In addition, verify that incorrectly ordered selections and correctly
ordered selections correspond to success and failure states.
Closes #1008, closes #1073
=> ☑️ Rework verify phrase page to fix issues w/ duplicates

.github/workflows/build.yml, ui/pages/Menu.tsx
By setting an env variable via the build GitHub action, this PR adds displaying
the first 7 digits of the triggering commit's SHA on the menu page. As we move
towards continuous deployment, some folks are doing QA on main via an artifact.
Since `main` is fluid between versions, using just the current version number
is insufficient to specify a build for a bug report.
=> 🍁 420: Add commit hash to versions on menu page 

webpack.config.ts
Switch to eval source maps in development builds, which webpack claims
are more performant for rebuilds. At the same time, turn off source maps
for Firefox production builds, since these need to be fully reproducible
by the FF add-on verification team, and source maps currently inject
absolute path data into the packaged files, which makes the build
non-reproducible in a different environment.
Future work would ideally allow investigating how to have source maps
without injecting absolute paths.
Run `yarn build --config-name firefox` in your clone. Then, clone to a
completely different place, maybe even on a different machine, and do the
same. Then check the generated ZIP files to ensure their unzipped contents
are textually identical (I used [`ksdiff`](https://kaleidoscope.app) for this …
=> Adjust source map configs for performance and reproducibility

ui/components/Shared/SharedButton.tsx
=> 💚 Update `SharedButton` default text color to dark green

ui/components/SignTransaction/SignTransactionContractInteractionProvider.tsx, ui/components/SignTransaction/SignTransactionInfoBaseProvider.tsx, ui/components/SignTransaction/SignTransactionInfoProvider.tsx, ui/components/SignTransaction/SignTransactionLoader.tsx, ui/components/SignTransaction/SignTransactionPanelCombined.tsx, ui/components/SignTransaction/SignTransactionSignInfoProvider.tsx, ui/pages/SignTransaction.tsx
⚠️ I haven't written a proper description here yet, but feel free to review it anyway! Each of the commit messages include some additional explanation.
1. Try to swap ETH on Uniswap for any token. The "sign transaction" version should appear with the spend amount
2. Try to swap BAL (any besides ETH) on Uniswap for another token. The "contract interaction" screen should appear like in the screenshot below.
Ideally, all sign transaction types should be tested. That said, these two steps cover what's meant to have been changed.
<hr/>
If we don't have the relevant token spend amount on a contract interaction, after this PR it'll display:
Closes #1271
=> ✍️ Contract interaction sign page

background/lib/prices.ts
If a token without a fiat pair was being price checked, the error prevented other tokens from getting a price.
Closes https://github.com/tallycash/extension/issues/1206
=> 🫓 Fuckin' NaN: Fix long-tail token price bug

background/networks.ts, background/services/chain/index.ts, background/services/ledger/index.ts, background/services/signing/index.ts, background/tests/keyring-integration.test.ts
This implements queued transaction lookups for all networks with a
provider available, factors the provider tracking in `ChainService`
to follow the pattern from elsewhere of nesting all EVM chains under
an `evm` property for future work, and adds network tracking to
transaction requests.
Things to be tested here:
created transactions, continue to work properly on mainnet.
enabled; in particular, transactions can still be signed and
mined on the mainnet fork.
=> Error Vector Magnitude: Light refactoring for multi-network handling

background/lib/alchemy.ts
Sending an empty array results in the following error: 
`Error: invalid 2nd argument: contract_addresses was not a valid contract address array or string literal 'DEFAULT_TOKENS'`
=> Don't send an empty array when calling alchemy_getTokenBalances.

background/lib/logger.ts
Before: 
```
chrome-extension://licmhmlaminmlpcdkobcjofpnchdlacg/background.js:61926:63
Error fetching, validating, and saving token list https://yearn.science/static/tokenlist.json,[object Object]
at chrome-extension://licmhmlaminmlpcdkobcjofpnchdlacg/background.js:61926:63 
```
Note the `[object Object]`
After:
```
chrome-extension://licmhmlaminmlpcdkobcjofpnchdlacg/background.js:61939:63
Error fetching, validating, and saving token list https://yearn.science/static/tokenlist.json,{"foo":"bar"}
at chrome-extension://licmhmlaminmlpcdkobcjofpnchdlacg/background.js:61939:63 
```
As a result of the following line of code: 
```
logger.error(`Error fetching, validating, and saving token list ${url}`, { foo: "bar" })
```
This will make logs that users export for us a lot more useful - …
=> Properly log objects in exported logs.

ui/pages/Onboarding/OnboardingImportMetamask.tsx
=> Fix address import error border color

ui/components/Shared/SharedAssetInput.tsx
=> Fix: search icon overlap

background/services/chain/index.ts
Since we invoke some async functions without awaiting them inside of chain service's addAccountToTrack - any errors in those functions are swallowed without being logged. 
Adding these catch's at least lets us log the errors - although unfortunately we do not get a relevant stack trace so extra labeling of the logs is necessary.
- disconnect from internet
- install tally
- import a new wallet
=> Explicit error logging inside of chainService.addAccountToTrack

background/services/indexing/index.ts
This change makes it so that ETH balance update on our 1-minute balance update alarm.
- disconnect from internet
- clean install the extension
- import an account
- Stay disconnected for ~1-2 minutes
- Connect to internet
This is related to https://github.com/tallycash/extension/issues/1158
=> Refresh the base asset along with tokens when refreshing token balances.

background/redux-slices/utils/contract-utils.ts
We had a small memory leak that became especially apparent when the app was disconnected and attempting to reconnect and call `eth_chainID` over long periods of time.
This issue _might_ be related to https://github.com/tallycash/extension/issues/1158
=> Properly cleanup event listeners on the Internal Provider.

background/services/enrichment/index.ts
To preserve uniqueness, the transfer log recipient addresses are
extracted and then passed through a Set. Due to a small error in how
the recipient addresses were being fed to the Set, the addresses were
being fully flattened into individual characters instead of addresses,
leading to very incorrect and extra-repetitive naming lookups.
Closes #1430 .
=> Richness not Flatness: Don't flatten recipients in internal log recipient lookups

ui/components/Claim/ClaimIntro.tsx, ui/pages/Claiming/Eligible.tsx
We used to set the referral on each visit to the claim container
component, which caused the referrer to be re-set after we come
back from signing delegation. Now unless users go back to the
first step the referred variable will stay removed.
https://user-images.githubusercontent.com/61434499/168087395-a50c17e2-e48b-40c8-b369-7ee0e45f15ec.mov
=> Move the referral bridge to first claim step

background/main.ts, background/services/indexing/index.ts, background/services/provider-bridge/index.ts
`notifyEnrichedTransaction` and `notifyContentScriptsAboutAddressChange` are actually synchronous functions that fire off unawaited promises outside of our control flow.  This PR updates their typing to match their behavior.
=> Small cleanup of typing of synchronous functions.

.gitignore
Reasoning here is that we should allow developers to customize their development environment while developing without forcing a particular set of settings onto anyone or cluttering up the filesystem of developers who do not use vscode.
=> Add the .vscode folder to .gitignore.

background/redux-slices/ui.ts
This seems to be a holdover from a previous implementation attempt - discarded in favor of the [addOrEditAddressName](https://github.com/tallycash/extension/blob/main/background/redux-slices/accounts.ts#L325) function.
=> Remove unused addOrEditAddressName event in ui redux slice.

background/constants/networks.ts, background/redux-slices/ui.ts, ui/components/TopMenu/TopMenuProfileButton.tsx, ui/components/TopMenu/TopMenuProtocolList.tsx, ui/components/TopMenu/TopMenuProtocolListItem.tsx, ui/components/TopMenu/TopMenuProtocolSwitcher.tsx
This PR allows users to use the top menu protocol switcher to switch between Ethereum & Polygon and see their network balance on the corresponding network.
https://user-images.githubusercontent.com/94649004/168637792-048443f3-1e20-4371-b428-f49c497590b1.mov
- Compile the extension with MULTI_NETWORK=true in your `.env` file.
- Import a wallet to the extension.
- Note balance on Polygon (import should default to this chain when MULTI_NETWORK=true).
- Use top switcher to switch to Ethereum.
- Your ETH balance should load quickly and your token balances should load over time.
- Switching back and forth between Polygon and Ethereum should correctly show your balance on the respective chain.
=> Ξ -> ♾️  Switch to Polygon.

background/redux-slices/utils/contract-utils.ts
Nonce logic should automatically be handled by the provider or inside of chain service.  This function is unused and can potentially be harmful if accidentally used to manually set a nonce.
- compile the extension.
=> Remove unused getNonce function.

ui/components/AccountItem/AccountItemRemovalConfirm.tsx
Resolves #1497
1. Add a few addresses 
2. Remove the currently selected address
**Expected result:** extension will switch selected account to another address
=> 🗑  Fix selecting other address if current one is removed

background/main.ts, background/redux-slices/ui.ts, background/redux-slices/utils/contract-utils.ts, background/tally-provider.ts
Closes #1508 
Do not merge until #1483 makes it into main.
Also - I'm not sure of the utility of the `switchChain` extension of the provider if we notify directly through main - would you mind commenting @Shadowfiend
=> Notify the internal ethereum provider directly about network changes.

ui/pages/Onboarding/VerifySeed/VerifySeedError.tsx
Resolves https://github.com/tallycash/extension/issues/1518
Change link on failed verification screen during creating new wallet so it will redirect to creating a new wallet, not to the root page.
=> ⛓️ Change link for "create new wallet" during onboarding

background/constants/network-fees.ts
`ESTIMATED_FEE_MULTIPLIERS_BY_TYPE` was previously used, essentially
arbitrarily, with the idea that estimated network fees should change depending
on the max fee selected. This is only partly true. The part of the max fee that
impacts the estimated network fee is only the max priority fee, since it's
completely used in almost all cases. So we removed the multiplier from the
network fee display, but left the constant here. This PR is just housekeeping
to remove the constant and a PR with some context.
=> 🪦 Remove `ESTIMATED_FEE_MULTIPLIERS_BY_TYPE`

background/main.ts, background/redux-slices/accounts.ts
Closes #1502.
Note that this is different from - and a precursor to #1501.
This PR persists the default name of an account when switching to a new network.
=> Persist default account names across chains.

ui/components/Swap/SwapTransactionSettingsChooser.tsx
When adding the new gas picker, unfortunately, I removed padding even for the
older/published version, which resulted in some ugliness. This PR puts the
removal of the chooser's padding behind a feature flag. That said, this is only
bringing the older gas picker to its original iffy look. The overhauled version is
behind a feature flag.
<table>
<tbody>
<tr>
<td>Before 😬</td>
<td>After ✨</td>
</tr>
<tr>
<td>
</td>
<td>
</td>
</tr>
</tbody>
</table>
🤘
=> ❤️‍🩹 Patch: Feature flag the removal of the swap fee chooser's row padding

ui/components/Keyring/KeyringSetPassword.tsx, ui/package.json, yarn.lock
Closes #1329 
This PR requires users to have create a somewhat-strong password to use the extension.  
How strong of a password? 
`3` strong of a password!  
How strong is 3?
Well - the tool we're using has the following scale:
```
// 0 - too guessable: risky password. (guesses < 10^3)
// 1 - very guessable: protection from throttled online attacks. (guesses < 10^6)
// 2 - somewhat guessable: protection from unthrottled online attacks. (guesses < 10^8)
// 3 - safely unguessable: moderate protection from offline slow-hash scenario. (guesses < 10^10)
// 4 - very unguessable: strong protection from offline slow-hash scenario. (guesses >= 10^10)
```
While we all want to be good security-conscious citizens of the web I do think that requiring users to have complex passwords of more than 16 …
=> Require users to use strong(er) passwords

ui/hooks/validation-hooks.ts, ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx
These defaults are cruft from a version of the extension that did not yet have a network switcher.
Now that the user can switch networks through the TopMenu there's no reason to have them.
=> Remove Unneeded Polygon Defaults

.eslintrc.js, background/redux-slices/ui.ts, ui/components/Earn/Clock.tsx, ui/components/NetworkFees/NetworkSettingsSelect.tsx, ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx, ui/components/NetworkFees/NetworkSettingsSelectOptionButtons.tsx
The impetus here is me not removing a few unused imports lately 🙈. And the
title of the PR is slightly misleading because this is implemented by using the
`@typescript-eslint/no-unused-vars` rule. So **it covers all unused vars, not
just imports.**
=> 🧹 Add linting error for (and fix) unused imports

background/services/preferences/defaults.ts
The old URL is no longer maintained.
Refs https://github.com/Uniswap/tokenlists-org/pull/1422
To test
=====
=> :fire: Keep Feeling the Yearn: Update the Yearn token list URL

background/main.ts, background/redux-slices/selectors/transactionConstructionSelectors.ts, background/redux-slices/transaction-construction.ts, ui/components/NetworkFees/FeeSettingsText.tsx, ui/components/SignTransaction/SignTransactionDetailPanel.tsx, ui/components/SignTransaction/SignTransactionSpendAssetInfoProvider.tsx
- renamed `updateOptions` to `updateTransaction` as we are not only updating transaction's options (what options? network/gas options?) but this function is updating a whole set of transaction data
- removed duplicated gas settings redux selector - selector `selectDefaultNetworkFeeSettings` has been duplicated but only one function has been used. Removed unused one and moved the missing `baseFeePerGas` field to the other selector
- fixed showing gas price instead of `TBD` - If we know gas limit by suggested gas limit or selected by a user then we
should show the estimated gas value in the network settings selector button
=> 🧚 Minor transaction and gas improvements

src/window-provider.ts, window-provider/index.ts
Disable the linter `no-non-null-assertion` rule where it is needed.
=> 🫥 Fix linter warnings

background/services/provider-bridge/authorization.ts
No great way to test the denial now (because we auth dapps for both polygon & eth  for now) but being able to sign a transaction (for example a quickswap swap) should be a good enough test that this works.
=> Explicitly check chain id and if actually allowed when checking for permissions.

background/main.ts, background/services/internal-ethereum-provider/constants.ts, background/services/internal-ethereum-provider/db.ts, background/services/internal-ethereum-provider/index.ts, background/services/provider-bridge/index.ts
This PR adds functionality to support 1 active chain per origin - allowing for a wonderful UX for people wanting to use mlutiple dapps on different chains at once.
Some key parts:
- a given origin can only have 1 active chain (no chain-per-tab _yet_)
- we have a special origin for our internal dapp
Outstanding question - is this in-scope for Polygon launch?
=> 🧑‍🤝‍🧑 My Best Friend - One active network per origin.

ui/hooks/index.ts, ui/pages/Swap.tsx
> Let's win the swap game or die! - Greg
This PR:
- updates the disable state of the final quote button
- restricts quote updates to happen only when we have all the input data
- fix a weird behaviour that is happening because of `webext-redux`
- ~~start every swap with a clean slate~~ keep the persisted state functionality
Try to swap, and it should work as expected. 
~~When `Approve asset` happens, the swap page will NOT be repopulated with the previous settings.~~
Closes #1587
=> 🦑 Squid Game: Improvements to swap state handling

window-provider/index.ts
Resolves https://github.com/tallycash/extension/issues/1251
Allow to connect wallet, buy and list NFTs on OpenSea. 
Added `sendAsync` method, despite it being deprecated some dapps are still using it. OpenSea was throwing errors and warnings as we were not sending the expected response format.
1. Connect wallet with OpenSea
2. Buy NFT (you can use [this lamb](https://opensea.io/assets/ethereum/0xd1e5b0ff1287aa9f9a268759062e4ab08b9dacbe/36415121617891189491210625105620328235501305871961131031012756619587371395219) as I was using it for testing)
3. List NFT for sale
4. Make an offer **Note**: last time I was testing making an offer it was broken on both TallyHo and MetaMask so I assume it's on their side.
=> 🌊 OpenSea interactions

background/services/internal-ethereum-provider/db.ts
@greg-nagy's [comment](https://github.com/tallycash/extension/pull/1609#discussion_r901790735) turned out to be prescient.  The current implementation causes inconsistent behavior when SUPPORT_POLYGON is set to true.
Attempt to buy a polygon NFT (for example[ this one](https://opensea.io/assets/matic/0x66194b1abcbfbedd83841775404b245c8f9e4183/210624583337114373395836055367340864637790190801098222508621988249)).  You should be able to do so successfully.
=> Properly initialize internal active network.

ui/components/Core/CorePage.tsx, ui/pages/Popup.tsx
Turns out the missing asset on the overview tab was just hidden behind the tab
bar basically.  The height on the content area only adjusted to having a top
bar or not w/ a tab bar, but didn't handle a tab bar w/o the top bar. This PR
solves the issue by passing the bar settings into the core page component to
set the styles.
Closes #1362
🤘
=> 📜 Fix scroll in core page which fixes overview tab

background/services/internal-ethereum-provider/index.ts, ui/components/SignData/EIP191Info.tsx
Resolves #1590
Some dApps are sending sign data in plain text, not hex as expected. We should check if a sign message input is actually in hex format before decoding.
Try to sign EIP191 message - for example, sign in to https://passport.gitcoin.co/#/
=> Fix sign data displayed message

ui/pages/Onboarding/OnboardingImportMetamask.tsx
Primarily fixes our previous lack of handling
line
breaks
when importing a recover phrase.
Also converts to lowercase first. h/t @timjrobinson
Closes #1681
=> 📝 Better handle white-space in import recovery phrase

background/redux-slices/selectors/accountsSelectors.ts
Fixes https://github.com/tallycash/extension/issues/1700
To Test:
- Ensure that the overview address count is not double the number of addresses in your address list.
- Adding an address should increase the address count by 1
- Removing an address should decrease the address count by 1
=> Fix overview address count

background/index.ts, background/main.ts, env.d.ts
This strategy only sends the actual changed areas across the port, but
more importantly it only changes the objects that need to be changed in
the proxy store. This leads to less rerendering in the extension popup.
This is something I noticed while debugging a network-switching-related
issue, where rerenders were triggering certain `useEffect`s rather
unexpectedly, because of how objects are compared. This should make object
comparisons and resulting invalidation of any dependencies work a little
more predictably/like we might expect.
=> Deeply Diffed: Move webext-redux updatesto deep-diff strategy

background/main.ts, background/redux-slices/signing.ts, background/redux-slices/transaction-construction.ts, ui/pages/SignTransaction.tsx
> [**Operation Unifier**, also known as **Canadian Armed Forces Joint Task Force-Ukraine**, is the Canadian Armed Forces contribution to the security of Ukraine in coordination with the Ukrainian Armed Forces. It also includes a small Swedish contingent. It was begun in light of fomentation by separatist sentiments in the Donetsk and Luhansk and Crimean regions of Ukraine after the 2014 Ukrainian revolution and the 2014 pro-Russian unrest in Ukraine.](https://en.wikipedia.org/wiki/Operation_Unifier)
Transaction signing requests were of type `SignatureRequest`, which
predates the `SignOperation<T>` type that unifies typed data and message
signing requests. To unify all signing and make progress towards moving
all signing management into the signing slice, signing operations are
now all …
=> Operation Unifier: Make transactions follow the SignOperation<T> contract

ui/components/NetworkFees/FeeSettingsText.tsx
Dollar values were very low because of an order of operations issue that
appeared when `estimatedSpendPerGas` was added. This resolves that issue and
cleans things up a bit.
=> 👁 Fix new gas preview dollar estimate

background/redux-slices/selectors/accountsSelectors.ts, background/redux-slices/utils/asset-utils.ts, ui/pages/Swap.tsx
Closes https://github.com/tallycash/extension/issues/1703.
- Open SWAP menu on ethereum network
- searching for ETH should no longer show `Ether - PoS` in the buy token list
=> Bugfix: Swapping tokens w/ same name & symbol but different networks no longer allowed.

background/services/provider-bridge/index.ts
This fixes an issue where if a user had `Ethereum` selected in the wallet and was trying to sign a transaction on `Polygon` (or vice versa) the call would fail because there would be a mismatch between the chainID of the permission and the chainID of the requested transaction.
=> Use correct chainID when looking up permissions.

background/services/enrichment/index.ts, ui/components/NetworkFees/NetworkSettingsSelect.tsx
We should not do `(maxFeePerGas + maxPriorityFeePerGas)` because `maxPriorityFeePerGas` is included in `maxFeePerGas`.
This also fixes the dollar calc in `NetworkSettingsSelect`, although I don't believe that's used anywhere at the moment.
=> 🤏 Fix enrichment service's insufficient funds warning calc

window-provider/index.ts
Closes https://github.com/tallycash/extension/issues/1736
Evidence of bridge working: 
Approval: https://etherscan.io/tx/0xae3dd5f15036b1359faf712e5c4c0272d444927eeaef92d605c625b0353f619e
Bridge Transaction: https://etherscan.io/tx/0x8c4a3701d38085ecd06d3a4b8fab161eac59924d89a2ee2dc0fb0fe7c84d716b
So it appears what was happening was that https://wallet.polygon.technology/bridge/ was calling `send` but expecting the response to their call to be in the shape of a `sendAsync` response.
Question to @greg-nagy or @Shadowfiend  - do we think this breaks existing functionality - or is the conditional branch inside of the `if` statement on line 142 something that has never worked?
If we think it will break existing functionality - I fear we may need some sort of whitelist for dapps that require …
=> Fallback to sendAsync inside of window-provider's send method

window-provider/index.ts
- adding isWeb3 flag to `window-provider`
- saving the chainId on the `window-provider` in case of `wallet_switchEthereumChain` || `wallet_addEthereumChain`
Note: on the initial connection, a `wrong network` error will be shown. 
Fixing this would require white-labeling meshswap which is probably not a good idea. 
This behavior is identical with MM. 
Closes #1761
=> Fix meshswap dapp connection

background/services/enrichment/index.ts, background/services/enrichment/utils.ts
This PR resolves the issue of name service lookups temporarily bringing the application to a halt.
- Load the extension, add an account, open the background logs
- Go do something else for ~4 minutes
- Come back - focus all your energy on testing this ticket
=> Only lookup names for relevant ERC20 transfers

background/services/indexing/db.ts
We track more than custom assets, but custom assets were the only assets being
checked by `isTrackingAsset`. Although all custom assets are tracked, this can
exclude non-custom tracked assets. This PR updates `isTrackingAsset` to
match the expected behavior of returning `true` on all tracked assets.
=> 🐾 Update `isTrackingAsset` to match intent

background/services/indexing/index.ts
https://github.com/tallycash/extension/pull/1788/commits/2564d140e633bf4853073224d452ce7a451cf0d5 states, 
> Baseline trust is currently defined as a token that was SENT BY an address that is being tracked
(i.e., an account the user has added to the wallet) OR that is already
known (typically via a token list).
So it looks like the idea is to check if an asset is known, not just if it's tracked.
This PR adds checking if an asset is known to the baseline trust check.
=> 🐾 Also check if asset known

background/redux-slices/selectors/accountsSelectors.ts, ui/components/SignTransaction/SignTransactionContainer.tsx, ui/components/Wallet/WalletAccountBalanceControl.tsx, ui/pages/PersonalSign.tsx, ui/pages/SignData.tsx, ui/pages/SignTransaction.tsx, ui/pages/SingleAsset.tsx
Resolves #1799
Fix problems where read-only accounts were allowed to try to sign transactions and other regressions caused by #1724
Please test this side by side with our last release to make sure read-only accounts are handled the same way they were before.
=> Fix read-only accounts

background/services/name/resolvers/address-book.ts
No need for a `call` here since changing `lookUpAddressForName` and `lookUpNameForAddress` to functions binds `this` for us.
=> Remove `call` code cruft

background/lib/token-lists.ts, background/package.json, background/services/indexing/index.ts
this function call is extremply expensive cpu wise
and it's also a pure function in the practical sense
so we can optimize by running it only if the input
list changes
we use a shortcut for calculating the cache key
for similarity definition. We are not checking for
all the contract addresses to be the same, but
we use the number of all the elements in the list
as an indicator that the incoming lists are the same
This is a reasonable compromise, given we are dealing
with token lists here.
=> 📒Create a memoized version of the mergeAssets

webpack.config.ts
github actions started to kill the build process
with error message of 137 which signals out of
memory
Couldn't find any way to set it manually without
self-hosting the builder, so I went with a shortcut
of building only for browsers that we are currently
shipping for.
This decreased the memory usage to it's third
8394096640 > 3120578560
to measure on osx: /usr/bin/time -l yarn build
=> fix for github CI memory issue

background/lib/token-lists.ts
networkAssetsFromLists is using mergeAssets
and it's called every time getCachedAssets is called
so it also worth memoizing
the effect of this optimization is not that significant
as it was for the `getCachedAssets` but this still
makes this to the top of the list in terms of cpu usage
=> 💬Memoize 2/n: use the memoized version of `mergeAssets` in `networkAssetsFromLists` 

package.json
Apply patches before dev build
If for some reason webext-redux package is not patched then we experience weird bugs without an easy way to debug them. As this is a recurring issue and we are wasting our time on it,
let's apply patches before dev builds.
=> Patch packages before each dev build

ui/components/Shared/SharedAssetInput.tsx
Resolves https://github.com/tallycash/extension/issues/1825
As it is not possible to send the full amount of base asset we shouldn't suggest users to do it by having "max" button next to the asset amount input
=> Hide "max" button for base asset

background/constants/currencies.ts, background/lib/prices.ts, background/redux-slices/assets.ts, background/redux-slices/migrations/index.ts, background/redux-slices/migrations/to-14.ts, background/tests/earn/assets.mock.ts, background/tests/prices.test.ts
Remove the historical price data from the redux store. We are not using it for anything and it's saved into indexedDB, so we can query for it later when we need it. 
⚠️ These testing steps focus on this PR and #1875 together as a measure to improve our CPU usage. They are kind of separate from dev perspective, but part of the same problem — big redux store.
- create a clean install 
- test store size change
- verify store size with the script below 
- import `enroll...`
- check overview tab and wallet > assets tab that it shows usd values
- wait 5 minutes
- verify store size again 
- wait 10 minutes
- verify store size again 
- wait 10 minutes
- verify store size again 
- test cpu usage with final store size (after completing the above steps)
- with chrome task manager
- [open chrome task …
=> ⏰ Remove historical pricepoint from assets

background/redux-slices/migrations/to-13.ts
Apparently, the wallet can be in a state where the ids list is not defined for a given account
=> 🔧  Expect activities ids list to be `undefined`

background/redux-slices/0x-swap.ts
Resolves #1896 
Let's use `gated` prefix only on Ethereum mainnet, not on Polygon.
Test swaps on the build made by Github, not the local one
=> Don't prefix polygon 0x address with `gated`

background/services/internal-ethereum-provider/index.ts
Let's go back to the previous solution for sign message to unblock SIWE that is expecting input to be parsed as ASCII.
---
**This is not a final solution.**
=> Revert treating sign message input as hex to fix SIWE

ui/pages/Popup.tsx
We have changed routes names before - if a user hasn't used the wallet for a while and it updates to a newer version then it can be stuck on a location that has been removed. Let's default to the main route if the wallet is in an unknown location.
=> Default to main route if wallet is stuck on unknown route

background/assets.ts, background/constants/currencies.ts, background/constants/networks.ts, background/lib/prices.ts, background/networks.ts, background/tests/keyring-integration.test.ts
remove coingeckoPlatformID from `CoinGeckoAsset` and add it to `Network` instead.
=> Standardize coingeckoPlatformID

background/services/chain/utils.ts, background/services/ledger/index.ts
Cleanup some errors that were being thrown without the `new` keyword.
=> Ensure that thrown errors are instantiated with "new"

background/services/ledger/index.ts
Added the Nano S Plus `productId` so newer hardware wallet users can connect with Tally Ho.
Refs #1352, closes #1331
H/t @adrienlacombe-ledger
=> Ledger Plus Plus: Enable support for Ledger Nano S Plus

background/main.ts
Switching networks in the extension shouldn't impact different dApp connections.
Closes #1846
=> Orthogonal Networks: Don't notify dApps when extension account changes

background/main.ts
Reverts tallycash/extension#1961
https://github.com/tallycash/extension/pull/1961#issuecomment-1216858204
> So the situation after this PR: network is still changing for the dapps if the extension changes network but we have lost the change account functionality.
=> Revert "Orthogonal Networks: Don't notify dApps when extension account changes"

background/constants/networks.ts, background/networks.ts, background/redux-slices/selectors/transactionConstructionSelectors.ts, background/redux-slices/transaction-construction.ts, background/services/chain/index.ts, background/services/chain/utils/index.ts, background/services/chain/utils/optimismGasPriceOracle.tsx, background/services/enrichment/index.ts, ui/components/NetworkFees/FeeSettingsText.tsx, ui/components/NetworkFees/NetworkSettingsChooser.tsx, ui/components/NetworkFees/NetworkSettingsSelect.tsx, ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx, ui/components/Swap/SwapTransactionSettingsChooser.tsx, ui/pages/Swap.tsx
Some things to note:
- Provider.getGasPrice() only gives us the gas price of a transaction on optimism.
- The bulk of an optimism transaction's cost is taken by the security fee - and deducted automatically by the network.
- The total amount a given account pays for a tx is the L2 tx fee plus the L1 security fee - this is what we want to display for the user.
- Optimism provides a contract that allows us to query the total fee in wei of rolling up a given transaction.
- Displaying the cost in `gwei` will be handled in a future PR - this PR only addresses displaying the $ value.
- We certainly need a redesign of the Fee Settings component because while the tx fee is modifiable by the user the security fee is not.  This means that while a user may set their gas cost to `0.0001` gwei in …
=> Incorporate L1 Rollup Fees into Optimism Gas Fee Display

background/redux-slices/transaction-construction.ts
Calculate the optimism block estimate once and reuse it rather than calculating three times.
=> Remove some redundant optimism block estimate calculations

background/lib/alchemy.ts
Resolves #1919
To prevent Alchemy server errors on really big accounts we need to specify `pageSize` parameter.
=> Add page size to Alchemy getNFTs request

ui/components/SignData/SignDataInfo.tsx, ui/components/SignTransaction/SignTransactionNetworkAccountInfoTopBar.tsx, ui/pages/DAppConnect/RequestingDApp.tsx, ui/pages/PersonalSign.tsx, ui/pages/SignData.tsx
Resolves #1895
Relates to #1794
* show the current network on the signing screen - that way we can see what network is selected in a wallet during signing
* fix the problem with data sign and a personal sign that was expecting the wallet to be on the same network as dapp, while [transaction sign was accepting it being on a different network](https://github.com/tallycash/extension/blob/show-network-on-signing-page/ui/pages/SignTransaction.tsx#L37-L43) - ideally wallet should match the network that dapp is expecting but let's unify our implementation first
* fix styles problems on the signing screens
=> 🔧 Signing and networks improvements

ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
The path we were using works with MEW's derivation notation, but was
erroring on a Ledger because... *drumroll*... it's for ETC.
https://blog.trezor.io/trezor-integration-with-myetherwallet-3e217a652e08
https://www.reddit.com/r/TREZOR/comments/81qffg/comment/dv4exam/
Closes #1943
=> Remove erroneous Trezor derivation path

ui/components/NFTs/NFTsSlideUpPreviewContent.tsx
1. Find NFT with no preview image
2. Click on the NFT
Bug: Unexpected Error
Expected: Opens slideup with selected NFT
=> Fix error on NFT preview slideup with no image

background/services/ledger/index.ts
This was introduced in siwe-while-you-sign, and is due to a subtlety of
Buffer.from().toString("hex"), which was swapped out with passing hex data
directly here. Buffer.toString("hex") does not include the 0x prefix,
whereas our hex data does. The Ledger library can't handle that and
blows up.
Fixes #1971.
=> Pass unprefixed hex to Ledger for message signing

background/services/name/resolvers/ens.ts, background/services/name/resolvers/uns.ts
=> Allow ENS and UNS name resolution on Optimism and Arbitrum

ui/components/TopMenu/TopMenuProtocolList.tsx
> Görlitzer Park **(nicknamed "Görli")** is a major park and recreation area in the [Kreuzberg](https://en.wikipedia.org/wiki/Kreuzberg) district of [Berlin](https://en.wikipedia.org/wiki/Berlin). The 14-hectare park area contains, among other things, a [petting zoo](https://en.wikipedia.org/wiki/Petting_zoo), several sports and [football fields](https://en.wikipedia.org/wiki/Football_pitch), and a small lake.[[1]](https://en.wikipedia.org/wiki/G%C3%B6rlitzer_Park#cite_note-1)[[2]](https://en.wikipedia.org/wiki/G%C3%B6rlitzer_Park#cite_note-2)[[3]](https://en.wikipedia.org/wiki/G%C3%B6rlitzer_Park#cite_note-3) At its north-west end is the [Görlitzer Bahnhof](https://en.wikipedia.org/wiki/G%C3%B6rlitzer_Bahnhof_(Berlin_U-Bahn)) U-Bahn station.
— [Wikipedia, …
=> Kreuzberg: Add a divider between production and test networks in the switcher

ui/components/AccountItem/AccountItemOptionsMenu.tsx
Closes #1957 
This PR fixes layering issue on the accounts panel. Option menu background appears underneath the dots of the row after it. The z-index property has been changed which specifies the stack order of an element. 
**Before:**
**After:**
**To Test**
=> Change z-index for account options menu on the accounts panel

ui/components/SignData/EIP191Info.tsx
Closes #1977 
This PR fixes text cutting issue for messages in the signing page where "transaction" is split in the middle. The` line-break` property was removed. The `overflow-wrap` property has been added with value `anywhere`. The value `normal` is used by default for property `word-break`.
**Before:**
**After:**
**To test**
=> Make a text wrapping for messages in the signing page

background/services/name/resolvers/uns.ts
This should alleviate the sometimes painfully slow loading of transaction confirmation screens.
=> Add timeout to UNS Requests

background/services/preferences/db.ts, background/services/preferences/defaults.ts
Updates default and stored token lists URL preferences, the later through a migration
Refs: 
#2039
=> Replace .eth.link token lists urls to .eth.limo

background/lib/alchemy.ts, background/services/chain/index.ts
Remove the sliding window transfer lookup construct in `ChainService`, instead immediately looking up history when an account is tracked.
While the block height concept isn't absolutely removed for now, in practice in the happy path we should have a single call for a new account's transfer history.
Explicitly out of scope for this PR, though I'd like to address some of these issues in follow-ups
* Intelligent retries/backoffs for the original history pull. The current behavior is a single dumb hourly retry, but doesn't change parameters.
* Removing the dumb hammer-retry logic getting more recent asset transfers.
* Even though I call this a "single call" for history lookups, it's actually 2 — one for incoming and another for outgoing transactions. I'd like to get it down to 1 for new …
=> 📖 Conservative View of History: Rely on a single `getAssetTransfers` to pull wallet history in the happy case 

background/lib/alchemy.ts, background/services/chain/asset-data-helper.ts, background/services/chain/index.ts
Alchemy only supports checking against a "to" or "from" address when calling `getAssetTransfers`... meaning we are often making two API calls per account tracking.
This PR skips checking outgoing asset transfers when possible in `ChainService`. It should reduce `getAssetTransfer` calls by around 45% every 15 minutes (after the initial history load).
Closes #2059
=> Cursory View of History: Don't check outgoing asset transfers unless necessary

background/services/name/resolvers/uns.ts
This PR adds caching to the UNS resolver in an effort to reduce the amount of calls made to the Unstoppable Domains API while syncing blocks.
Refs: 
#1967
>- [ ] Add a new account and wait until syncing starts dispatching multiple reverse lookup queries for the new account address
>
> OR
>- [ ] Go to sign transfer page after setting as the destination the current account address
=> Reduce number of UNS address lookups

background/networks.ts
Legacy transactions were slipping through, leading to type errors enriching transactions on Optimism.
Closes #2064
=> Optimistic Typeguards: Tighten up the EIP1559 tx request type guard

background/services/chain/db.ts, background/services/chain/index.ts
Now that we've moved to an approach of querying a given accounts most recent 1k asset transfers every 90 seconds - we need to ensure that we are not retrieving the same transactions unnecessarily.
Prior to this change - the "transactionsToRetrieve" queue would fill up every 90 seconds even after some transactions were correctly processed via "handleQueuedTransactionAlarm".  The performance hit from that was especially large on accounts with a large asset transfer history due to how we handle determining if a given transaction hash is already in the queue inside of "queueTransactionHashToRetrieve".
```
setInterval(() => console.log("Transactions in queue: ", this.transactionsToRetrieve.length), 10_000)
```
=> Avoid adding transaction hashes for known asset transfers to the queue of transactions to retrieve.

background/services/enrichment/transactions.ts
Closes #2063 
This PR addresses an issue where transactions producing multiple ERC-20 `Transfer` events were significantly impacting the performance of the extension.
In extreme cases - transactions such as [this one](https://etherscan.io/tx/0x3c712768212cc75eec5329c6d08ed4a4edc679ee5c4553c6433c7b16259816fb) containing thousands of ERC-20 `Transfer's` would cause the extension to attempt to enrich each address involved in the transfer - slowing the extension to a standstill.  This PR aims to keep the desired behavior of enriching addresses involved in ERC-20 `Transfer` events while only enriching the events that are relevant to the accounts loaded into the extension.
=> Drastically reduce unnecessary enrichment of ERC-20 Transfers.

background/services/enrichment/transactions.ts, background/services/enrichment/utils.ts
This fixes a potential problem where failing to enrich one subannotation from a `Transfer` log prevents all subannotations from populating.
=> Support partial subannotation population in the case where one annotation fails.

background/main.ts, background/services/chain/index.ts, background/services/keyring/index.ts, background/tests/factories.ts
Closes #2042 
This change should free up some alchemy bandwidth if and when we get an influx of new users similar to last week.
=> Avoid looking up historical transfers for newly created accounts.

.github/CODEOWNERS
This is closer to my original intent with the `CODEOWNERS` config — keyring code should be hard to change, dependencies should be hard to change, non-dependency releases should be a bit looser.
We should agree on a process for adding people to the @tallycash/extension-dependency-auditors team. The idea here is that anyone who joins it needs to agree that they won't merge without auditing every dependency change... a pretty serious lift / responsibility.
=> More Release Owners: Separate release management from dependency audits

.github/ISSUE_TEMPLATE/BUG.yml, scripts/update-version.sh
We haven't been CE since v0.14.0 😀
=> Beyond Community Edition: Remove "Community Edition" prefix from bug reports

background/services/preferences/defaults.ts, background/services/preferences/tests/index.integration.test.ts
Turn off the "set Tally Ho as default wallet" preference default. This avoids the error where users try to use the wallet before onboarding, and are greeted with a frustrated green screen message.
We have product alignment for this new behavior to avoid churn / uninstalls. There's an ongoing discussion about where to go from here in #2085 that I suggest all who are interested check out.
Closes #2026
=> 👛 You Must Have a Wallet to Have a Default Wallet: Don't set Tally Ho as the default wallet before onboarding

ui/hooks/validation-hooks.ts
This fixes an issue with imported accounts, where activities never load since the UI slice's selected account stores a dirty address that never gets matched to it's normalized version in the activities slice.
1. Import this address `0x00976385980F6a03606C29EB97627691d7e3CAA6` or any non normalized address 
2. Activities should show up now
=> Fix missing activities for read only accounts

background/redux-slices/accounts.ts
Resolves #2075
Avoid adding two accounts with the same default name and avatar in the row.
Add multiple accounts and check if no two addresses in a row have the same name and avatar
=> Make default account names more random

background/main.ts, background/redux-slices/dapp.ts, background/services/provider-bridge/db.ts, background/services/provider-bridge/index.ts
Resolves #1978
When user removes address we should remove its dApp permissions too from db and redux store
1. Add a couple of accounts to the wallet
2. Open background script devtools so you can observe how dAppPermissions database is changing 
3. Connect to any dapp - confirm in the UI it is connected on both dapp and wallet side, refresh db and check new connection is saved there
4. Remove address that is connected to the dapp
5. Confirm it is correctly disconnected from dapp and wallet, UI and db
6. Add that address again - it shouldn't be connected to that dapp
7. Confirm dapps connections feature is working as before in general (connect, switch accounts, disconnect, sign tx)
=> Remove dApp permissions with account

background/constants/index.ts, background/lib/alchemy.ts, background/redux-slices/ui.ts, background/services/chain/index.ts, background/services/chain/serial-fallback-provider.ts, background/services/name/resolvers/uns.ts
Follow-on to https://github.com/tallycash/extension/pull/2087
=> Improve activeNetworks functionality.

background/services/chain/index.ts
Enables tracking of the Goerli network in the background.
=> Enable Background tracking of Goerli.

background/redux-slices/selectors/accountsSelectors.ts
=> Display current network's base asset earlier in assets list

window-provider/index.ts
matcha.xyz does not play nicely with Tally - so lets add it to our list of websites on which to impersonate metamask.
=> Enable Tally users to use Matcha.xyz

ui/components/NFTs/NFTsImage.tsx
Closes #2081 
This PR stops blinking loader animation after NFTs are loaded.
**UI**
Before
After
**To Test**
=> Change NFTs styles when it is already loaded

ui/components/Shared/SharedButton.tsx, ui/components/Wallet/WalletActivityList.tsx
Closes #2074 
This PR fixes styles of "End of activity list" message
**Changes**
- center text
- remove padding for the button
-  reduce the button icon
**UI**
Before
After
**To Test**
=> Change styles for message in the wallet activity list

window-provider/index.ts
=> Add new galaxy url to metamask impersonation list

ui/pages/SingleAsset.tsx
=> Make Single Asset Etherscan link Network Aware

background/services/enrichment/transactions.ts
Pretty sure wallet users know enough about their own wallet 😀
Closes #2131
=> Enrichment Interaction: Annotate "to" address on transactions, not "from"

background/services/preferences/index.ts
=> Display uniswap contract name when signing optimism transactions on uniswap

background/redux-slices/selectors/transactionConstructionSelectors.ts, ui/components/NetworkFees/FeeSettingsText.tsx
This PR fixes a regression where having `Ethereum` selected as the network while transacting on Optimism or Polygon through a dapp showed erroneous gas price previews
Sometimes l2fees.info is quite slow to update but as long as you're not seeing a dollar cost above $2 then this fix is working as intended.
=> Fix In-wallet selected network affecting gas preview

background/services/preferences/index.ts
The beauty of ✨ CREATE2 ✨ means the same address works across networks for both contracts.
=> Optimistically Named Router: Add 0x and Uniswap contract names on Opti and Arbi

background/lib/gas.ts, background/third-party-data/blocknative/index.ts
Closes #1445
By calling Blocknative.connect inside of `getBlockPrices` - we were opening a websocket connection each time we polled for block prices - which then stayed open for an indefinite amount of time.  Once a critical mass of websocket connections were opened - they would begin to disconnect and then automatically reconnect - causing a loop that used up _significant_ resources.  Switching to a singleton mitigates this issue and still lets us allow on the sdk's reconnect logic in case of connectivity issues.
=> Dam the Waterfall - Fix Blocknative Cascading Reconnect

background/redux-slices/assets.ts
We were deduplicating assets that shared a name but belonged to different networks - now we don't.
=> Greatly increase available swap assets on L2's

background/redux-slices/selectors/transactionConstructionSelectors.ts
This PR addresses a bug that arises due to a race condition or poor connection quality - so it is a bit hard to reproduce.
It looks like when switching to a new network for the first time we are sometimes trying to access `networks.evm[currentNetwork.chainID]` before `networks.evm[currentNetwork.chainID]` has been populated.  
It is quite inconsistent and difficult to recreate - but these are the general steps:
I can reproduce this about 1 out of 20 times but the change is quite straightforward and has minimal risk of doing anything harmful - so hoping we can merge.
=> Fix swap screen sometimes crashing when switching networks for the first time.

background/redux-slices/utils/activity-utils.ts, ui/components/SignTransaction/SignTransactionContainer.tsx, ui/pages/PersonalSign.tsx, ui/pages/SignData.tsx, ui/pages/SignTransaction.tsx
Resolves https://github.com/tallycash/extension/issues/1817
Handle blockheight in activities screen the same way as the activity is labeled - `pending`, `dropped`, `failed`. We can add migration so it would fix activities for existing extensions but it is not needed IMO - but open to suggestions 😄 
Resolves https://github.com/tallycash/extension/issues/2051
Fix the problem with pending/loading sign button and transactions that can't be signed.
After user clicks "Sign" button `handleConfirm()`function is called. Each `handleConfirm()` had its rules when the transaction was not yet ready to be signed. In that case, function had no effect but Sign button was already in a "loading" state and as users were waiting for it to finish the action window was often losing focus - and disabling the …
=> ⏱ Pending transaction fixes

ui/components/NetworkFees/NetworkSettingsChooser.tsx
Behavior before this commit:
- Have Optimism selected as the in-wallet network
- Setup up an ethereum uniswap swap
- Attempt to edit gas settings
- "Unexpected Error"
Behavior after this commit:
- Have Optimism selected as the in-wallet network
- Setup up an ethereum uniswap swap
- Attempt to edit gas settings
- 🎉 💯 ✅ 🥇
=> Fix Optimism network settings chooser mismatch

background/services/chain/index.ts, background/services/chain/utils/index.ts
Closes https://github.com/tallycash/extension/issues/2204
Closes https://github.com/tallycash/extension/issues/2201
This one was tricky - we need a `from` field when estimating gas limits for a given legacy tx - but `from` is also disallowed when serializing legacy transactions.  Luckily we correctly separate our concerns with `ethersTransactionRequestFromLegacyTransactionRequest` and `ethersTransactionFromSignedTransaction` so the fix was simple to implement - although difficult to pinpoint.
=> Populate `from` on LegacyTransactions when estimating gas limit

background/services/chain/serial-fallback-provider.ts
=> Fix fallback logic for unsupported `alchemy_filteredNewFullPendingTransactions`

background/utils/view-model-transformer.ts
=> Fix "0x Router" not displaying in Activity List for Tally Swaps

ui/components/Shared/SharedButton.tsx, ui/components/SignTransaction/SignTransactionContainer.tsx, ui/hooks/dom-hooks.ts
Resolves https://github.com/tallycash/extension/issues/2164
Resolves https://github.com/tallycash/extension/issues/2202
Same as `Sign` button `Reject` button should be blocked when the transaction is not ready to be signed.
This is because sometimes there are pending dispatched actions when the user is rejecting transaction and there is no easy way to cancel them. When they are finally dispatched then the transaction should be already rejected but it is being repopulated with data. Because of this signing screen becomes visible again. 
Expected: Signing screen shouldn't be visible again after user rejects, after sign there should be no endlessly spinning Sign button
https://user-images.githubusercontent.com/20949277/190655998-46378df8-9cf7-41d1-b1af-d97dec78dbcc.mov
=> Block reject button when transaction is not ready

.tsconfig-eslint.json
After testing the extension on Firefox, I found my eslint server crashing constantly due to being out of memory. A couple of tests afterwards revealed the problem to be in the exclude directives used by `.tsconfig-eslint.json`. 
As shown in the screenshot below, both my RAM usage and CPU time went down by a lot (~70%/~50%) when linting after adding output directories to the excluded paths in `.tsconfig-eslint.json`.
Left side has same settings as PR
Middle does not exclude `validate` and `local-chain` folders
Right side only excludes `dist/firefox`
=> Reduce ram/cpu usage for eslint

ui/pages/Onboarding/OnboardingInfoIntro.tsx, ui/pages/Onboarding/Tabbed/Intro.tsx
We no longer flip the option on by default.
Closes #2257
=> Don't show "Tally Ho as default" page onboarding

ui/pages/Settings.tsx
Closes #2294 
This PR is moving "default wallet" up to top of "Settings.
**UI**
Before
After
**To test**
=> Move default wallet up to top of Settings

ui/_locales/en/messages.json, ui/pages/DAppConnect/SwitchWalletPage.tsx
Closes #2255 
This PR updates Switch Wallet Page.
**Changes**
- add texts to translations
- change "Menu" to "Setting"
- add settings icon to description
**UI**
Before
After
**To test**
=> Update texts for SwitchWalletPage

background/services/provider-bridge/index.ts, window-provider/index.ts
Will let the picture speak:
To do this, we let `net_version` come through before explicit dApp authorization (as we already do with `eth_chainId`, its more contemporary counterpart), and we add Etherscan to the Metamask impersonation list.
Closes #2016, #2290.
=> Multiscan: Support Etherscan connections in Tally

background/services/provider-bridge/index.ts
This allows certain dApps like Optimism Etherscan to work. It's also in line with our whitelisting wallet_addEthereumChain for access before dApp authorization.
I missed pushing a commit in #2313 and it landed too fast for me to fix it 🙈
=> Multiscan Optimism: Allow wallet_switchEthereumChain calls before authorizing a dApp

background/services/chain/index.ts, background/services/chain/tests/index.integration.test.ts
This should also help decrease our json-rpc usage.
=> Prevent chain service from subscribing to networks twice.

background/lib/gas.ts, background/main.ts, background/redux-slices/ui.ts, background/services/chain/index.ts, background/services/chain/tests/index.unit.test.ts, background/services/internal-ethereum-provider/index.ts, background/services/provider-bridge/index.ts, background/tests/factories.ts, ui/pages/Popup.tsx
This PR introduces functionality which limits the extension from polling for gas prices when the extension is not active - and lays the groundwork for doing the same with base asset balances, erc20 lookups, and just about any other chain lookup we want to throttle.
The central change that this PR introduces is a [central piece of state](https://github.com/tallycash/extension/blob/reduce-the-consumption/background/services/chain/index.ts#L146:L148) inside of chain service which tracks the last time a network was "active".  The current events that trigger a refresh of "active" time are:
-  User has opened or navigated to any page in the extension (currently selected network activity)
-  A dapp has requested to permission to connect to the wallet (dapp's connected network activity)
-  A dapp …
=> Only poll for gas prices when a network is active

background/redux-slices/0x-swap.ts
cc @VladUXUI 
(The "Copy Address" being expanded is an artifact of my screenshotting software)
=> Change insufficient asset liquidity warning to reflect actual reason for error.

background/redux-slices/migrations/to-16.ts
An old migration didn't move the `ids` and `entities` from the address level into the `chainID` level but copied it. Because of this these keys are still in the state and there is is entities field inside the `ids` or `entities` array. This has caused migration issues for some folks on brave. The easy nondestructive fix is simply ignore these properties. Because the slice will be refactored soon it did not worth the risk to remove those keys from state.
⚠️ We don't have a way to reproduce the green screen issue. We just know the error message/line of code and the state of the environment where it happened. So these tests are only to verify that nothing is broken and generally the migrations
are safe. For more context see #2334 
Closes #2334
=> 👻 Banish Ghosts: fix `to-16.ts` migration, to fix green screen of death

background/main.ts, background/services/provider-bridge/index.ts
In our current implementation - a dapp connected to tally in an active or inactive tab will reset `lastUserNetworkActivity` each time it sends a request to the wallet.
This change updates that logic to only set `lastUserNetworkActivity` when `eth_requestAccounts` is received - which is indicative of a user actively navigating to a dapp.
=> Prevent background dapp connections from marking network activity.

background/main.ts, background/redux-slices/signing.ts, background/services/internal-ethereum-provider/index.ts, background/utils/signing.ts, ui/components/SignData/EIP191Info.tsx, ui/components/Signing/SignatureDetails/DataSignatureDetails/MessageDataSignatureDetails.tsx, ui/components/Signing/SignatureDetails/index.tsx, ui/pages/PersonalSign.tsx, ui/pages/PersonalSignDetailPanel.tsx
> [The **Union Jack**, or **Union Flag**, is the de facto national flag of the United Kingdom. Although no law has been passed making the Union Jack the official national flag of the United Kingdom, it has effectively become such through precedent. It is sometimes asserted that the term *Union Jack* properly refers only to naval usage, but this assertion was dismissed by the Flag Institute in 2013 following historical investigations.](https://en.wikipedia.org/wiki/Union_Jack)
`SignDataRequest` was an envelope container for (personal, non-typed-data) message signing requests that were further subdivided by type, and different message types (such as SIWE messages) had more specific parsed data types in a `signingData` field. `SignDataMessageType` was an integer enum that was used for …
=> Union Jack: Rework SignDataRequest as MessageSigningRequest discriminated union

ui/components/SignTransaction/SignTransactionNetworkAccountInfoTopBar.tsx
on the `eth_signTypedData.*` > `signTypedData`> emit `signTypedDataRequest` 
the `typedDataRequest` is dispatched which populates the `signing.typedDataRequest` 
property in redux. The rest of the transaction is populated properly from this slice, but 
the network display didn't check this slice for network info.
Closes #2368
=> add typedData for network display on signing

background/services/indexing/tests/index.unit.test.ts
Fix broken test that was failing on GH builds. 
This version is not time-dependent as this is using emitted events instead of `wait`.
=> Fix token list test

background/services/internal-ethereum-provider/index.ts
1inch sends nonce from mainnet when approving
assets on arbitrum and this causes the broadcast
to fail
we lookup the nonce during the signing process
so it's safe to ignore this parameter from the dapp
Closes #2370
=> 😢 But why?: remove nonce if received from dapp

ui/components/NFTs/NFTsSlideUpPreviewContent.tsx
- add `0x77f6e4ea32f0b807dcaaddbec9dabe0131614cd5 ` as a readonly address
- check if the snolizard is linked properly to arbiscan
- [reference url](https://arbiscan.io//token/0x0dCCAb3f2FC587b67bFDC66ffd2c87a567B21394?a=1742)
Closes #2375
=> add arbiscan url for nft links

ui/_locales/en/messages.json, ui/components/NetworkFees/NetworkSettingsChooser.tsx, ui/components/NetworkFees/NetworkSettingsSelectOptimism.tsx
We have decided to use the legacy networks select panel for gas setting on arbitrum, so it doesn't make sense anymore to keep this nameing. 
Closes #2360
=> rename `NetworkSettingsOptimismAndArbitrum` > `NetworkSettingsOptimism ` for unambiguity

background/main.ts
=> Allow revoking of Arbitrum dapp permissions.

provider-bridge/index.ts
This should prevent weird script tags from appearing on xml docs
Ref: https://discord.com/channels/808358975287722045/888500174685614090/1031480622377615420
=> Don't inject provider on non html documents

background/lib/prices.ts, background/services/indexing/index.ts, background/tests/prices.test.ts
This PR fixes an issue where if the product of (Addresses & Networks) was more than 60 - users would _always_ hit the coingecko ratelimit - and if it was less than that they were likely to when adding multiple addresses or networks at once (or while using coingecko.com).
This PR lays down some groundwork for https://github.com/tallycash/extension/issues/2134
There are two common scenarios happening that may rate-limit coingecko for users (and result in inconsistent prices).
1.  When the extension is first loaded - chain service emits every account on every network as part of the `newAccountToTrack` event - each of which triggers a call to `handlePricealarm`.
2.  When a user switches to a network for the first time - a `newAccountToTrack` event is emitted for every account in the wallet. …
=> Throttle CoinGecko API calls.

window-provider/index.ts
Closes #2452 
This PR adds the Apex to the 'impersonate MM' list . Swapr was added earlier. 
**Before**
**After**
**To Test**
Set Tally Ho as default wallet.
=> Add the apex.exchange to the 'impersonate MM'

README.md
The badge src was wrong:
After the fix:
=> Fix: weblate badge URL in readme

background/redux-slices/utils/0x-swap-utils.ts
Since we are currently somewhat limited by how we can do price discovery for coingecko assets right now - we might not have prices for assets on some chains - especially if a bridged asset has a different contract address on a given L2.
We should still support swapping to / from these assets even if we don't  have a good way of getting their price data currently.
Note that currently we display `$0.00` as the price for the asset we're swapping to when a price is unknown - this should probably change to something more descriptive to the user but is out of the scope of this bugfix.
=> Fix swaps involving assets for which we do not have price data.

ui/pages/Send.tsx
In cases where the Send recipient is resolved from a name, the address is presented under the name as a copiable item. Very roughly aligns with existing designs around the contact list.
With resolved names, the full address is shown and can be clicked to copy:
Standard addresses are unchanged:
=> Destination Resolution: Show resolved address for Send recipient

ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/Shared/SharedIcon.tsx, ui/pages/Send.tsx
In a few places, icons were being used alongside text whose color transitioned on hover. Because the icons are not colored the same way, the icon colors would change instantly instead of transitioning, which led to a jerkiness in the hover animation.
SharedIcon now has a transitionHoverTime property that sets the time it takes to transition the icon color on hover. This is applied appropriately for the account lock/unlock button in the accounts panel, as well as for the address copy button on the Send page.
=> Transitional Fossil: Transition icon colors on hover where relevant

.github/workflows/build.yml, background/services/chain/tests/index.unit.test.ts, background/services/name/index.ts, background/services/name/tests/index.integration.test.ts, background/tests/factories.ts, package.json, setupJest.env.ts, yarn.lock
This PR addresses a number of issues encountered while debugging tests failing in CI (but passing locally)
- Global mock (during tests) of the SerialFallbackProvider to avoid creating websocket connections during testing.
- [Upgraded from node12 to node 16 github actions.](https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/)
- Attempt local name resolution prior to using remote name resolvers.
- Explicitly stop chain after tests which start it are run.
- [Fix to an intermittently failing name service test.]
=> Mock Websocket Connections - Fix a number of issues relating to tests running inconsistently in CI

ui/_locales/en/messages.json, ui/components/Onboarding/OnboardingDerivationPathSelect.tsx
This PR removes RSK testnet option from derivation path selection screen as this is not required for RSK integration release. 
- Activate `HIDE_IMPORT_DERIVATION_PATH` env flag
- Now check the Import account screen (dpath select dropdown)
=> [FIX] Remove RSK Testnet option from dPath dropdown

window-provider/index.ts, window-provider/wallet-connection-handlers.ts
https://user-images.githubusercontent.com/94649004/197816072-cccca7bc-55b9-4fde-9be3-13ed040af757.mov
=> Inject Tally Ho as a connection option on abroad.exchange

background/services/name/resolvers/rns.ts
This PR fixes `rnsResolver` to use `RSK` network. Using `ETHEREUM` network in `rnsResolver` is incorrect and due to this reason `RNS` names are not resolving on send screen.
- Activate `SUPPORT_RSK` env flag
- Choose `RSK` network
- Enter an `RNS` name in send field
- Examples Name: `alepc.rsk`, `riverplate.rsk`
- It should resolve to the correct address on rsk network
=> [FIX] Use `RSK` network in `RNS` resolver

background/services/preferences/db.ts, ui/components/AccountItem/AccountItemOptionsMenu.tsx, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx, ui/components/Shared/SharedDropDown.test.tsx, ui/components/Shared/SharedDropDown.tsx
The settings icon was not displaying because when #2523 got tested and merged it did not include a recently merged update to `SharedIcon` rendering 
Latest build: [extension-builds-2541](https://github.com/tallycash/extension/suites/9082050358/artifacts/420636406) (as of Wed, 02 Nov 2022 06:10:09 GMT).
=> Fix account settings icon not displaying

.github/workflows/builds/post-build-link.js
A misplaced paren was causing these to continue failing. Enable TypeScript JS checking to catch this kind of issue in the future, with some light type annotations.
Sorry folks, noticed the merge commits were still failing instead of passing as no-ops.
Latest build: [extension-builds-2557](https://github.com/tallycash/extension/suites/9136815148/artifacts/424558486) (as of Fri, 04 Nov 2022 19:04:31 GMT).
=> Correctly fix post-build-link for merge commits

ui/components/Shared/SharedAssetInput.tsx, ui/components/Shared/SharedAssetItem.tsx
Ref #2583
Let's add a link to the scan website to make it easier for users to know what token it is - to avoid confusion where there are multiple tokens with the same or very similar names on the list.
https://user-images.githubusercontent.com/20949277/201067230-deca9eea-542f-4b2f-a915-00d83f73f088.mov
Latest build: [extension-builds-2584](https://github.com/tallycash/extension/suites/9232166466/artifacts/431486585) (as of Thu, 10 Nov 2022 10:33:34 GMT).
=> Add token contract links to the asset selector component

window-provider/index.ts
Latest build: [extension-builds-2605](https://github.com/tallycash/extension/suites/9262627746/artifacts/433616041) (as of Fri, 11 Nov 2022 20:14:04 GMT).
=> Add transferto.xyz to MetaMask impersonation list

background/services/chain/serial-fallback-provider.ts
`alchemy_filteredNewFullPendingTransactions` is [deprecated](https://docs.alchemy.com/changelog/deprecated-support-for-alchemy_newfullpendingtransactions-and-alchemy_filterednewfullpendingtransactions) - this PR updates our extension to use the new recommended method.
Latest build: [extension-builds-2603](https://github.com/tallycash/extension/suites/9284250991/artifacts/435247150) (as of Mon, 14 Nov 2022 05:10:44 GMT).
=> Update method for getting pending transactions via alchemy

background/constants/networks.ts, background/lib/nfts.ts, background/lib/poap.ts
- Show POAP in NFTs tabs
- Treat them as Achievements on Ethereum mainnet - as we aren't currently supporting Gnosis chain. 
Latest build: [extension-builds-2608](https://github.com/tallycash/extension/suites/9293170709/artifacts/435886969) (as of Mon, 14 Nov 2022 14:21:04 GMT).
=> Add POAP NFTs support

background/constants/networks.ts, background/main.ts, background/redux-slices/dapp.ts, background/redux-slices/selectors/transactionConstructionSelectors.ts, background/services/chain/index.ts, background/services/name/resolvers/rns.ts, ui/_locales/en/messages.json, ui/components/NetworkFees/FeeSettingsText.tsx, ui/components/NetworkFees/NetworkSettingsChooser.tsx, ui/components/NetworkFees/NetworkSettingsSelectRSK.tsx, ui/components/Shared/SharedAssetItem.tsx, ui/components/TopMenu/TopMenuProtocolList.tsx, ui/hooks/validation-hooks.ts, ui/utils/constants.ts
Since we don't yet fully support ledger on rootstock - lets mark it as beta until we do.
This PR also changes the name of the `RSK` network to `ROOTSTOCK` to align with the naming of the other networks in the extension.
cc @alepc253
Latest build: [extension-builds-2625](https://github.com/tallycash/extension/suites/9315040506/artifacts/437473896) (as of Tue, 15 Nov 2022 13:32:18 GMT).
=> Mark Rootstock as beta in network selector

background/constants/networks.ts
This RPC is causing swaps to fail, disabling it as a quick fix to use alchemy while we find and test a different provider
Refs: #2656
Latest build: [extension-builds-2657](https://github.com/tallycash/extension/suites/9426857886/artifacts/445460044) (as of Mon, 21 Nov 2022 17:18:19 GMT).
=> Disable Arbitrum generic RPC

ui/_locales/en/messages.json, ui/components/NFTS_update/NFTsHeader.tsx, ui/components/Shared/SharedLoadingSpinner.tsx, ui/pages/NFTs.tsx
```
SUPPORT_NFT_TAB=true
```
Latest build: [extension-builds-2670](https://github.com/tallycash/extension/suites/9506349443/artifacts/451097785) (as of Fri, 25 Nov 2022 14:06:45 GMT).
=> Add Stats to NFT header

window-provider/index.ts
Latest build: [extension-builds-2704](https://github.com/tallycash/extension/suites/9613916352/artifacts/458884753) (as of Thu, 01 Dec 2022 16:30:03 GMT).
=> Add staking.polygon.technology to Metamask impersonation whitelist

background/lib/nfts_update.ts, background/lib/poap_update.ts, background/lib/simple-hash_update.ts, background/nfts.ts, background/redux-slices/selectors/nftsSelectors_update.ts, background/services/nfts/db.ts, background/services/nfts/index.ts, ui/components/NFTS_update/ExploreMarketLink.tsx, ui/components/NFTS_update/NFTItem.tsx, ui/components/NFTS_update/NFTPreview.tsx, ui/components/NFTS_update/NFTsHeader.tsx, ui/components/Overview/NFTsPortfolioOverview.tsx, ui/hooks/index.ts, ui/hooks/nft-hooks.ts, ui/pages/NFTs.tsx
- update collections as NFTs are loaded - POAPs collection should update number of NFTs it contains, Galxe collections should be marked as badges
- show number of NFTs, badges and collections in the stats UI for NFTs and Portfolio page
- calculate the total floor price for NFTs from loaded accounts and show it in stats
**Note: as loading NFTs is improved in [this PR ](https://github.com/tallycash/extension/pull/2703) here stats are updating as user is expanding collections - visible for POAPs and Galxe NFTs. In the linked PR action that triggers update is changed from expanding collection to collection being visible on the screen so it will be much nicer UX.**
Latest build: [extension-builds-2710](https://github.com/tallycash/extension/suites/9668601723/artifacts/462737410) (as of Mon, 05 …
=> Show real data in NFTs statistics

ui/_locales/en/messages.json, ui/pages/Settings.tsx, ui/pages/Settings/SettingButton.tsx
Closes #2763 
This PR updates the Settings page and adds FAQ link.
Changes:
- Remove the current "Join Community" banner
- Add social icons in the footer
-  Add Need help button  
Latest build: [extension-builds-2785](https://github.com/tallycash/extension/suites/9886761639/artifacts/477393896) (as of Thu, 15 Dec 2022 13:20:31 GMT).
=> Add FAQ link to Settings page

.github/workflows/build.yml
e2e tests depend on external services eg. cowswap which can result in false negatives. To prevent this from affecting developer velocity we run this only on main. This way we can be notified if something is broken without affecting other workflows.
We don't really have a way to test this change before actually merging on main.
=> Restrict the running of e2e tests only to main

.github/CODEOWNERS
tallycash has become tallyhowallet, so the old team name did not resolve.
Latest build: [extension-builds-2792](https://github.com/tallyhowallet/extension/suites/9896250759/artifacts/478063092) (as of Thu, 15 Dec 2022 21:09:12 GMT).
=> Updated CODEOWNERS for new org name

window-provider/index.ts
Closes #2786 
This PR fixes the issue with switching networks on Alpaca Finance.
- Select `Ethereum` in the in-wallet network dropdown selector
- Navigate to https://app.alpacafinance.org/
- Connect with Tally Ho
- Click `Switch Network` when the in-dapp popup comes up.
Latest build: [extension-builds-2794](https://github.com/tallyhowallet/extension/suites/9904009093/artifacts/478651832) (as of Fri, 16 Dec 2022 08:18:22 GMT).
=> Fix the issue with switching networks on Alpaca Finance

background/main.ts, background/services/ledger/index.ts, ui/components/Signing/Signer/SignerLedger/SignerLedgerFrame.tsx
Closes #2767 
This PR allows a swap on Pancakeswap with Ledger when the user has changed the Ledger settings.
- go to [pancakeswap](https://pancakeswap.finance/swap) to make swap with Ledger account
- try to do a swap when bling signing is enabled on the settings
- disable blind signing on the settings
- try to do a swap again
Latest build: [extension-builds-2796](https://github.com/tallyhowallet/extension/suites/9909132501/artifacts/478991299) (as of Fri, 16 Dec 2022 13:29:41 GMT).
=> Fix issue with swapping on Pancakeswap with Ledger

background/assets.ts, background/redux-slices/assets.test.ts, background/redux-slices/assets.ts, background/tests/factories.ts
Improves price point accuracy for smart contract assets and tests fix introduced by #2711 
Closes #2748
Latest build: [extension-builds-2793](https://github.com/tallyhowallet/extension/suites/9949807493/artifacts/481892529) (as of Mon, 19 Dec 2022 15:26:17 GMT).
=> Add test for price point asset selector

ui/components/NFTS_update/NFTImage.tsx, ui/components/NFTS_update/NFTPreview.tsx
Resolves https://github.com/tallyhowallet/extension/issues/2790
On the NFTs Preview slide-up we would like to show images with higher resolution than on the list because they are bigger and poor quality starts to become visible.
As we already have loaded the smaller image (for the list items) it can be displayed instantly while the higher resolution image has some load time.
Let's progressively display images with better resolution on the preview while showing smaller images first for seamless UX.
- load some accounts with NFTs, scroll the list, check out the preview slide-ups - images should be updated to higher resolution (barely visible most of the times I've checked)
Latest build: [extension-builds-2799](https://github.com/tallyhowallet/extension/suites/9986920660/artifacts/484584991) …
=> Load NFT images with higher resolution if available

ui/components/Swap/SwapQuote.tsx
Closes #2232 
This PR adds a scroll for the swap quote view.
Before
After
https://user-images.githubusercontent.com/23117945/210089751-96a21c6d-efa1-4107-a026-7c6aae0275d4.mov
- select Polygon network
- try to swap Matic<>AMP
Latest build: [extension-builds-2825](https://github.com/tallyhowallet/extension/suites/10114473112/artifacts/493411996) (as of Fri, 30 Dec 2022 16:11:08 GMT).
=> Add scroll for swap quote view

background/lib/nfts.ts, ui/components/NFTs/NFTsSlideUpPreviewContent.tsx
Closes #2765 
This PR adds the correct link to the BSC scan on the NFT page
Link: https://bscscan.com/token/0xE5b184875dd4f09f687d497d76c22D20Aec67788?a=7074
- select BSC/AVAX network
- go to the NFTs tab
- open NFT slide up preview content
- open the NFT asset on BSC/AVAX scan
Latest build: [extension-builds-2823](https://github.com/tallyhowallet/extension/suites/10111955978/artifacts/493245761) (as of Fri, 30 Dec 2022 12:00:32 GMT).
=> Add correct link to BSC/AVAX scan for NFT

background/redux-slices/nfts_update.ts, ui/components/NFTS_update/NFTsHeader.tsx
This PR includes improvements for NFT filters.
Changes
- NFT filters are available after reloading on the main page
- Making sure that owners of NFTs from the same collection are correctly added to the array
- Don't add collections to filters when the number of NFT per collection is 0
Collection name: ,,ENS: Ethereum Name Service"
Accounts: `berrry.eth` and `pelagic.eth` 
```
SUPPORT_NFT_TAB=true
```
Latest build: [extension-builds-2817](https://github.com/tallyhowallet/extension/suites/10152263754/artifacts/496037280) (as of Tue, 03 Jan 2023 07:35:19 GMT).
=> Nft filters improvements

ui/pages/Overview.tsx
Previous to this change the portfolio tab was broken with the `SUPPORT_ABILITIES` false.
Latest build: [extension-builds-2858](https://github.com/tallyhowallet/extension/suites/10307285907/artifacts/506854455) (as of Wed, 11 Jan 2023 12:26:02 GMT).
=> Fix the feature flag check for daylight menu

ui/components/AccountsNotificationPanel/EditSectionForm.tsx
Before: 
After:
Latest build: [extension-builds-2869](https://github.com/tallyhowallet/extension/suites/10378682387/artifacts/512090440) (as of Sun, 15 Jan 2023 11:49:11 GMT).
=> Proposal: Autofocus on input when editing section name

ui/pages/Settings.tsx
Resolves https://github.com/tallyhowallet/extension/issues/2871
Fix URLs for our Github and Twitter buttons
Latest build: [extension-builds-2872](https://github.com/tallyhowallet/extension/suites/10391518950/artifacts/512985953) (as of Mon, 16 Jan 2023 10:40:20 GMT).
=> Fix links to Twitter and Github

ui/components/Shared/SharedSquareButton.tsx, ui/components/Wallet/WalletAccountBalanceControl.tsx
Resolves https://github.com/tallyhowallet/extension/issues/2874
Fix buttons' colors and icons size
Latest build: [extension-builds-2883](https://github.com/tallyhowallet/extension/suites/10434853556/artifacts/516114569) (as of Wed, 18 Jan 2023 08:58:00 GMT).
=> Fix wallet control button styles

ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
Closes https://github.com/tallyhowallet/extension/issues/2904
To avoid erroneously showing prices of untrusted assets (and thus making them appear to be legitimate) we should not show the user prices for those assets.
Before:
After:
Latest build: [extension-builds-2902](https://github.com/tallyhowallet/extension/suites/10533600698/artifacts/523529251) (as of Mon, 23 Jan 2023 18:26:35 GMT).
=> Don't display prices for untrusted assets.

background/main.ts, background/redux-slices/tests/transaction-construction.unit.test.ts, background/redux-slices/transaction-construction.ts
Closes #2905 
Since we were resetting custom gas values to 0 on network switch but not the fee type selected - sending a transaction on a new network after using custom gas settings resulted in gas transactions being sent with gas values set to 0 - which would cause the transaction to fail.
Latest build: [extension-builds-2903](https://github.com/tallyhowallet/extension/suites/10535670807/artifacts/523684007) (as of Mon, 23 Jan 2023 20:13:46 GMT).
=> Reset transaction fee type on network switch

background/services/abilities/index.ts
Closes #2908 
The previous implementation does not allow for runtime switches.  The pattern here matches how we check for feature flags in all other instances.
Latest build: [extension-builds-2907](https://github.com/tallyhowallet/extension/suites/10536438251/artifacts/523740197) (as of Mon, 23 Jan 2023 20:53:32 GMT).
=> Properly use isEnabled to gate abilities polling based on feature flag.

window-provider/index.ts
- set wallet as default
- have metamask enabled on the browser
- try to connect wallet to [CowSwap](https://swap.cow.fi/#/1/swap/WETH)
- you should connect to TallyHo
Latest build: [extension-builds-2916](https://github.com/tallyhowallet/extension/suites/10555825810/artifacts/525096196) (as of Tue, 24 Jan 2023 16:28:34 GMT).
=> Impersonate MetaMask on CowSwap

ui/components/Signing/Signer/SignerBaseFrame.tsx
Before:
After:
Fixes #2912
Latest build: [extension-builds-2917](https://github.com/tallyhowallet/extension/suites/10557396288/artifacts/525210443) (as of Tue, 24 Jan 2023 17:35:55 GMT).
=> Disable Sign button if user can't pay fees

background/redux-slices/selectors/accountsSelectors.ts
To make the spam tokens less visible it let's allow to hide them with `Hide asset balances under $2` settings option
https://user-images.githubusercontent.com/20949277/214821734-b2f3d649-f65c-481c-87eb-22468ca0ff56.mov
Latest build: [extension-builds-2927](https://github.com/tallyhowallet/extension/suites/10595543874/artifacts/528090668) (as of Thu, 26 Jan 2023 11:14:13 GMT).
=> Hide untrusted assets with hide dust option

ui/components/Shared/SharedInput.tsx
Before:
After:
Fixes #2909
Latest build: [extension-builds-2918](https://github.com/tallyhowallet/extension/suites/10585916210/artifacts/527334315) (as of Wed, 25 Jan 2023 21:52:22 GMT).
=> Fix label background in SharedInput

background/lib/poap_update.ts, background/nfts.ts, background/redux-slices/accounts.ts, background/redux-slices/selectors/accountsSelectors.ts, ui/components/NFTS_update/NFTPreview.tsx, ui/components/Shared/SharedAddress.tsx
Resolves https://github.com/tallyhowallet/extension/issues/2848
- display POAPs supply for a given event on the Preview slideup
- add hardcoded POAPs contract as a contract address
- make addresses on the Preview slideup clickable
- show resolved account names instead of addresses if account has ENS/UNS name
Latest build: [extension-builds-2928](https://github.com/tallyhowallet/extension/suites/10597919968/artifacts/528262541) (as of Thu, 26 Jan 2023 13:27:13 GMT).
=> NFTs preview improvements

background/services/preferences/db.ts, background/services/preferences/defaults.ts
Updates the default and the existing token list stored in preferences
Latest build: [extension-builds-2932](https://github.com/tallyhowallet/extension/suites/10614716265/artifacts/529521072) (as of Fri, 27 Jan 2023 07:01:20 GMT).
=> Update default Avalanche token list

background/redux-slices/assets.ts, background/redux-slices/selectors/accountsSelectors.ts
Do not fall back to best effort matches when retrieving price points for untrusted assets
Latest build: [extension-builds-2933](https://github.com/tallyhowallet/extension/suites/10657658900/artifacts/532691947) (as of Mon, 30 Jan 2023 10:12:37 GMT).
=> Prevent price point best effort matching for untrusted assets

ui/components/TopMenu/TopMenu.tsx
Hide the icon behind a feature flag 
Latest build: [extension-builds-2975](https://github.com/tallyhowallet/extension/suites/10735550953/artifacts/538435581) (as of Thu, 02 Feb 2023 11:21:48 GMT).
=> Hide Wallet Connect connection icon behind feature flag

e2e-tests/dapp-connect.spec.ts
A recent CowSwap UI update broke this test
Latest build: [extension-builds-2970](https://github.com/tallyhowallet/extension/suites/10730013144/artifacts/538058727) (as of Thu, 02 Feb 2023 05:59:44 GMT).
=> Update dApp connection e2e test

background/services/preferences/db.ts, background/services/preferences/defaults.ts
Closes #2988 
Related #2932 
This PR updates the default token list for Avalanche.
Latest build: [extension-builds-2992](https://github.com/tallyhowallet/extension/suites/10805759394/artifacts/543533728) (as of Mon, 06 Feb 2023 15:00:07 GMT).
=> Update Avalanche token list

background/main.ts, background/redux-slices/abilities.ts, background/redux-slices/keyrings.ts, background/services/abilities/index.ts, background/services/chain/index.ts, background/services/doggo/index.ts, background/services/indexing/index.ts, background/services/name/index.ts, background/services/nfts/index.ts, ui/_locales/en/messages.json, ui/components/Overview/AbilitiesHeader.tsx, ui/pages/Abilities/AbilityFilter.tsx
Closes #2978
This PR changes visibility for abilities. Abilities should not be shown for read-only accounts.
```
SUPPORT_ABILITIES=true
```
Latest build: [extension-builds-2981](https://github.com/tallyhowallet/extension/suites/10806567227/artifacts/543588141) (as of Mon, 06 Feb 2023 15:30:44 GMT).
=>  Change visibility for Abilities

background/redux-slices/ui.ts
Closes #2993 
Latest build: [extension-builds-2994](https://github.com/tallyhowallet/extension/suites/10815479292/artifacts/544240159) (as of Mon, 06 Feb 2023 22:40:52 GMT).
=> Optimistically dismiss Analytics notification

background/lib/poap_update.ts, background/lib/simple-hash_update.ts, background/nfts.ts, background/redux-slices/nfts_update.ts, ui/_locales/en/messages.json, ui/components/NFTS_update/NFTPreview.tsx, ui/components/Shared/SharedSlideUpMenu.tsx, ui/components/Shared/SharedTooltip.tsx, ui/components/Swap/SwapTransactionSettingsChooser.tsx, ui/pages/Claiming/Eligible.tsx, ui/pages/Swap.tsx
Resolves https://github.com/tallyhowallet/extension/issues/2991
- Show rarity ranks on NFT preview
Other fixes:
- Fix color of slideup's background
- Allow tooltip to show content with "auto" width
Note: in the tooltip we show `rank / # of NFTs in collection` which may be different from what OpenSea shows for some collections - if some ranks are shared by many NFT in the collection. As we don't have rarity data on the collection level we can't show this information.
```
SUPPORT_NFT_TAB=true
```
Latest build: [extension-builds-3000](https://github.com/tallyhowallet/extension/suites/10830021187/artifacts/545316928) (as of Tue, 07 Feb 2023 14:10:00 GMT).
=> Add rarity rankings to NFTs

ui/components/Overview/NetworksChart.tsx
Make all built-in chains have a color 🎨 
Latest build: [extension-builds-2997](https://github.com/tallyhowallet/extension/suites/10837469077/artifacts/545848308) (as of Tue, 07 Feb 2023 19:23:53 GMT).
=> Add custom chart color for Rootstock

background/services/provider-bridge/index.ts, background/services/wallet-connect/index.ts, background/services/wallet-connect/legacy-sign-client-helper.ts
Closes #2950 
Retrieves favicon url / dApp name from the Wallet Connect session proposal metadata
```
SUPPORT_WALLET_CONNECT=true
```
Latest build: [extension-builds-2963](https://github.com/tallyhowallet/extension/suites/10704456820/artifacts/536148379) (as of Wed, 01 Feb 2023 06:05:29 GMT).
=> ⚠Wallet Connect - Display dApp info when connecting the wallet through

ui/_locales/en/messages.json
Latest build: [extension-builds-3004](https://github.com/tallyhowallet/extension/suites/10841982781/artifacts/546188235) (as of Tue, 07 Feb 2023 23:37:02 GMT).
=> Drop `beta` tag for Avalanche network.

background/services/provider-bridge/index.ts, background/services/provider-bridge/utils.ts
Resolves https://github.com/tallyhowallet/extension/issues/2985
Check if wallet address is on the expected position in params list for `eth_call` and `personal_sign` methods.  If it isn't then flip params order.
This should allow dapps that are not following JSON-RPC standard to be able to sign messages anyway.
Check if you can connect to dapp and sign message on:
- https://www.premint.xyz/
- https://mintkudos.xyz/
- https://login.xyz/
- https://tallyho.org/web3pledge/
Latest build: [extension-builds-3006](https://github.com/tallyhowallet/extension/suites/10852469412/artifacts/546985369) (as of Wed, 08 Feb 2023 11:39:07 GMT).
=> Flip RPC request params

background/redux-slices/abilities.ts, background/services/abilities/index.ts
This PR makes the filter state for abilities is not updated after reloading.  Accounts added after the flag change should be enabled.
Latest build: [extension-builds-3008](https://github.com/tallyhowallet/extension/suites/10857046169/artifacts/547299870) (as of Wed, 08 Feb 2023 15:02:41 GMT).
=> No change filter state after reloading

background/lib/daylight.ts
Confirmation that the key has been added to gh secrets:
Latest build: [extension-builds-3014](https://github.com/tallyhowallet/extension/suites/10906122700/artifacts/550931024) (as of Fri, 10 Feb 2023 14:59:35 GMT).
=> Add Daylight API Key to daylight requests

background/lib/daylight.ts, background/lib/tests/daylight.unit.test.ts
This is a difficult one to test - so will probably need to rely on making sure code & test are accurate.
The way to test this would be:
Latest build: [extension-builds-3015](https://github.com/tallyhowallet/extension/suites/10908416756/artifacts/551098481) (as of Fri, 10 Feb 2023 16:48:02 GMT).
=> Retry up to five times if an addresses abilities are still pending

ui/components/NFTS_update/NFTCollection.tsx
If there was a collection with no NFTs even after it was reloaded then it was hidden (no opacity or mouse events). Because it was still in the DOM it was messing up expanding collection animations. Let's remove that element from DOM after it fails to load any NFTs.
- load an address with a collection with no NFTs (POAPs most likely as we always have this collection loaded even if it has no NFTs) and check how collections are expanding
- example: my nemesis `ensagent.eth` who holds `berry.eth` 😄 then on Wallet page try to expand ENS collection. It should expand to the right. 
Latest build: [extension-builds-3011](https://github.com/tallyhowallet/extension/suites/10881502011/artifacts/549114381) (as of Thu, 09 Feb 2023 14:24:42 GMT).
=> Remove NFT collections with no NFTs from DOM

ui/components/Wallet/WalletAnalyticsNotificationBanner.tsx, ui/pages/Wallet.tsx
Close #3023 
Changes:
- set the correct width
- fix the width of icons (checkmark and X)
- display only one banner
Latest build: [extension-builds-3026](https://github.com/tallyhowallet/extension/suites/10948840013/artifacts/554047633) (as of Mon, 13 Feb 2023 15:46:30 GMT).
=> Handle multiple banners on Wallet page

background/redux-slices/utils/asset-utils.ts, background/redux-slices/utils/tests/asset-utils.unit.test.ts, ui/components/Shared/SharedAssetInput.tsx, ui/components/Shared/__tests__/SharedAssetInput.test.tsx, ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
Close #2941 
This PR hides untrusted tokens from the swap list.
Before
After
Latest build: [extension-builds-3033](https://github.com/tallyhowallet/extension/suites/10990796483/artifacts/557115793) (as of Wed, 15 Feb 2023 08:33:13 GMT).
=> Hide untrusted tokens from tokens selector

ui/pages/SingleAsset.tsx
Resolves https://github.com/tallyhowallet/extension/issues/3034
(couldn't find a good example but now it should be breaking the word)
Latest build: [extension-builds-3035](https://github.com/tallyhowallet/extension/suites/10998123811/artifacts/557629421) (as of Wed, 15 Feb 2023 14:20:49 GMT).
=> Break asset name on single asset page

background/lib/alchemy.ts, background/services/chain/asset-data-helper.ts
Due to the recent polygon hard-fork it is no longer possible to batch more than 100 requests together on polygon.  Because alchemy relies on batch calling under the hood when processing `alchemy_getTokenBalances` requests sent with a list of token contracts to check - we need to move away from the pattern of passing in a discrete lists of contracts to check.  
Luckily, Alchemy exposes the `erc20` request parameter which returns all erc20 balances for a given address - which we can use not only on polygon but on all chains alchemy supports - so lets do that!
Latest build: [extension-builds-3036](https://github.com/tallyhowallet/extension/suites/11007404854/artifacts/558317221) (as of Wed, 15 Feb 2023 21:13:48 GMT).
=> Use `erc20` argument when fetching token balances via Alchemy.

background/redux-slices/migrations/index.ts, background/redux-slices/migrations/to-25.ts
This PR fixes the issue of the incorrect state of the redux version. The issue occurred during the [upgrade](https://github.com/tallyhowallet/extension/commit/9519333b28caeda423cf8c4e4bd0b705ddab4da0#diff-b230998d1b07555389be4903734ca40c413bb671181a92e55a3f2d9c7bc2df7aL28) from version 23 to 24. Changes add missing migration 25.
Latest build: [extension-builds-3049](https://github.com/tallyhowallet/extension/suites/11045816318/artifacts/561210209) (as of Fri, 17 Feb 2023 12:34:19 GMT).
=> Fix issue for migration state

background/abilities.ts, background/redux-slices/migrations/index.ts, background/redux-slices/migrations/to-26.ts
Claim type for abilities should be enabled by default.
Latest build: [extension-builds-3059](https://github.com/tallyhowallet/extension/suites/11107052947/artifacts/565763395) (as of Tue, 21 Feb 2023 10:59:43 GMT).
=> Make claim type enabled by default

background/lib/daylight.ts
This PR changes the limit for getting abilities. There has been a change in the API. By default, the limit is set to 15.  The number has been increased to the maximum. A parameter responsible for the order in which abilities are taken has also been added. 
At this point, completed abilities are not being fetched. The user has the option to mark the ability as completed in the wallet. This should probably be resolved and streamlined. It is not in the scope of this PR. Probably to be resolved later.
Latest build: [extension-builds-3066](https://github.com/tallyhowallet/extension/suites/11130316814/artifacts/567497892) (as of Wed, 22 Feb 2023 09:59:37 GMT).
=> Fix the issue of getting abilities

background/redux-slices/migrations/to-26.ts
Fix failing migration for users that don't have abilities slice yet (they are updating from earlier versions)
- checkout tag with version for example v0.18.6
- install extension
- checkout main and hit 'reload' - extension should have green screen and error in the background
- checkout this branch and hit reload - extension should be back 
Latest build: [extension-builds-3074](https://github.com/tahowallet/extension/suites/11164255473/artifacts/570011862) (as of Thu, 23 Feb 2023 16:36:37 GMT).
=> Fix migration for users without abilities slice

background/redux-slices/abilities.ts, background/services/abilities/db.ts
This PR gives the opportunity to update existing abilities. Property such as `completed` and `removedFromUi`  should not be updated.
Latest build: [extension-builds-3075](https://github.com/tahowallet/extension/suites/11165565147/artifacts/570107603) (as of Thu, 23 Feb 2023 17:31:53 GMT).
=> Update the existing ability

background/lib/posthog.ts, background/main.ts, background/services/analytics/index.ts, background/services/analytics/tests/index.integration.test.ts
Closes #3078
Removes extension load time event as we can get this data from the chrome store. Additionally, moved all events to a string enum so we get some protection against sending inconsistent events and also code-wise they're easier to track.
Latest build: [extension-builds-3079](https://github.com/tahowallet/extension/suites/11172086788/artifacts/570582817) (as of Thu, 23 Feb 2023 23:17:52 GMT).
=> Analytics - Remove background start event

background/services/chain/db.ts, background/services/preferences/db.ts
Closes #3076
Updates networks stored in both chain and preferences db in order to prevent the wallet from treating these stored network assets as untrusted.
Latest build: [extension-builds-3082](https://github.com/tahowallet/extension/suites/11177745994/artifacts/571046923) (as of Fri, 24 Feb 2023 07:33:23 GMT).
=> Token Discovery - Update networks stored in chain & preferences db

background/services/provider-bridge/index.ts, ui/components/TopMenu/TopMenuProtocolList.tsx
And Separately
Latest build: [extension-builds-3084](https://github.com/tahowallet/extension/suites/11191886046/artifacts/572044288) (as of Fri, 24 Feb 2023 19:50:40 GMT).
=> Don't show add network popup if SUPPORT_CUSTOM_NETWORKS is not enabled

ui/components/Shared/PriceDetails.tsx
Closes https://github.com/tahowallet/extension/issues/2741
cc @VladUXUI Are you OK with the thresholds here?  0-2% is not highlighted, 2-5% is yellow, 5+% is red.
Latest build: [extension-builds-3096](https://github.com/tahowallet/extension/suites/11261059064/artifacts/577060605) (as of Tue, 28 Feb 2023 18:36:46 GMT).
=> Fix price impact highlighting

env.d.ts, ui/pages/ErrorFallback.tsx
This should help with debugging redux and state errors that aren't necessarily caused by background actions
Latest build: [extension-builds-3101](https://github.com/tahowallet/extension/suites/11291295174/artifacts/579279456) (as of Wed, 01 Mar 2023 21:22:40 GMT).
=> Logging - Log UI errors caught by main error boundary

background/services/nfts/db.ts, background/services/nfts/index.ts
Persist info about loaded NFTs collections and transfers timestamp between extension reloads to reduce number of requests to SimpleHash.
Construct data for `freshCollections` cache based on already fetched NFTs in the database - this will ensure that NFTs already fetched for our users won't be refetched.
1. Install extension from this branch, check NFTs and ensure everything works as expected. Checkout Network page in the background script, filter for SimpleHash requests and clear it. Then reload extension and check network page again - there should be 1 request for transfers and all collections previously loaded should be loaded from database.
2. Install extension from `main`, add accounts, check NFTs page and then upgrade to this branch - ensure there are no migration errors and NFTs …
=> Load NFTs service state from database

ui/components/Signing/Signer/TransactionButton.tsx
Fixes a bug that would cause both reject and sign buttons to remain locked when attempting to sign a message
Latest build: [extension-builds-3114](https://github.com/tahowallet/extension/suites/11352040150/artifacts/583581270) (as of Sat, 04 Mar 2023 21:05:20 GMT).
=> Signing - Prevent signing button from staying locked when attempting to sign data

ui/pages/Swap.tsx
Closes #3118 
This PR fixes UX bug and adds a back button on swap page.
**UI**
Before
After
Latest build: [extension-builds-3123](https://github.com/tahowallet/extension/suites/11399855519/artifacts/586952103) (as of Tue, 07 Mar 2023 11:18:26 GMT).
=> Add a back button for swap page

ui/pages/Abilities/AbilityCard.tsx
Ref #3128
If an account is not imported let's hide abilities for that account. Hotfix for the problem of fetching accounts from the ledger before they are selected to be imported.
1. You have to have any abilities on one of your Ledger accounts
2. import Ledger, let address with abilities load on the list but don't select it, select another one
3. Go to abilities page - it should be loading as usual and there should be no ability from the account you have ignored in prev step.
Latest build: [extension-builds-3129](https://github.com/tahowallet/extension/suites/11428154896/artifacts/589009381) (as of Wed, 08 Mar 2023 13:18:42 GMT).
=> Omit abilities from unknown accounts

background/main.ts
Prevents abilities polling for all ledger addresses discovered instead of only selected addresses when adding new accounts
Closes #3100
Refs:
- https://github.com/tahowallet/extension/pull/3095#pullrequestreview-1319275833
Latest build: [extension-builds-3131](https://github.com/tahowallet/extension/suites/11447290997/artifacts/590431383) (as of Thu, 09 Mar 2023 07:49:11 GMT).
=> Daylight - Only poll ablities for imported addresses

background/constants/networks.ts, background/main.ts, background/redux-slices/networks.ts, background/redux-slices/selectors/networks.ts, background/redux-slices/selectors/uiSelectors.ts, background/services/chain/db.ts, background/services/chain/index.ts, ui/_locales/en/messages.json, ui/pages/Settings/SettingsCustomNetworks.tsx
Closes #2758
Allows managing custom networks from within the settings page
```
```
Latest build: [extension-builds-3032](https://github.com/tahowallet/extension/suites/11529113568/artifacts/596372116) (as of Mon, 13 Mar 2023 16:40:02 GMT).
=> [Custom RPCs] Allow displaying and removing custom networks

.github/CODEOWNERS
CODEOWNERS was still referencing tallyhowallet as the org name for teams, which is incorrect. This is now correctly tahowallet. While we're in here, add an extension-security-auditors group to handle ownership of CODEOWNERS itself as well as keyring code.
As a last adjustment, drop package.json, which was triggering CODEOWNERS during releases because of a simple bump for the top-level package version. Instead, yarn.lock remains under CODEOWNERS. Since CI requires yarn.lock be up to date by using `--frozen-lockfile`, the effect of requiring that dependency changes be audited by the extension-dependency-auditors group remains.
Latest build: [extension-builds-3143](https://github.com/tahowallet/extension/suites/11524342976/artifacts/596027626) (as of Mon, 13 Mar 2023 13:46:45 GMT).
=> Fix CODEOWNERS teams and drop package.json

background/services/indexing/index.ts
Fix attempting to filter on `undefined` - while adding a new network with Chainlist there are no cached assets yet
Latest build: [extension-builds-3160](https://github.com/tahowallet/extension/suites/11578827244/artifacts/599913023) (as of Wed, 15 Mar 2023 13:32:41 GMT).
=> Handle case where there are no cached assets for given network

background/lib/prices.ts, background/services/indexing/tests/index.integration.test.ts
Closes https://github.com/tahowallet/extension/issues/3164
This change was introduced to resolve an issue where 429 responses from CoinGecko would block swap functionality in the application.  This was happening because the fetchJson function we were using automatically waits and retries requests that come back with a 429 status code.  Due to the high likelihood of us being rate limited when hitting the coingecko api - this is actually undesirable functinality since we want to fail fast in the case that coingecko is unavailable.
By passing in a throttleCallback to fetchJson that always resolves to false  - we can rely on the (already existing) code around the function call to handle cases where we get a 429 or a bad response.  This results in a snappier user experience when querying …
=> Disable 429 Retry when querying CoinGecko API.

ui/_locales/en/messages.json, ui/pages/NewCustomNetworkRequest.tsx
Closes #3207 
Adds a warning to the new custom network confirmation screen
```
```
Latest build: [extension-builds-3211](https://github.com/tahowallet/extension/suites/11915544816/artifacts/623964814) (as of Thu, 30 Mar 2023 12:17:05 GMT).
=> Custom Networks - Display a warning when attempting to add an already supported network

background/lib/posthog.ts, background/main.ts, background/redux-slices/ui.ts, background/services/analytics/db.ts, background/services/analytics/index.ts, ui/pages/Onboarding/Tabbed/ImportSeed.tsx, ui/pages/Onboarding/Tabbed/Intro.tsx, ui/pages/Onboarding/Tabbed/Ledger/Ledger.tsx, ui/pages/Onboarding/Tabbed/NewSeed/NewSeedVerify.tsx
This PR adds two analytics events:
- Onboarding Started - sent when a user clicks either the `Use Existing Wallet` or `Create new wallet` buttons in onboarding.
- Onboarding Finished - went when a user successfully creates a new wallet, imports a wallet, or connects via ledger.
Importantly the `Onboarding Finished` event is _not_ sent when a user adds a read_only address.
Latest build: [extension-builds-3215](https://github.com/tahowallet/extension/suites/11954553841/artifacts/626844075) (as of Fri, 31 Mar 2023 21:08:37 GMT).
=> Add analytics for Onboarding

window-provider/index.ts
Allows to use kyberswap.com with Taho
Latest build: [extension-builds-3239](https://github.com/tahowallet/extension/suites/12000893632/artifacts/630245077) (as of Mon, 03 Apr 2023 20:56:26 GMT).
=> Impersonate Metamask on kyberswap

background/lib/posthog.ts, background/main.ts
Latest build: [extension-builds-3235](https://github.com/tahowallet/extension/suites/11998160789/artifacts/629966676) (as of Mon, 03 Apr 2023 17:36:50 GMT).
=> Add analytics event when connecting to a Dapp

e2e-tests/utils/onboarding.ts, ui/components/NFTS_update/ExploreMarketLink.tsx
The missing `title` was causing the NFT E2E test locator to fail
Latest build: [extension-builds-3234](https://github.com/tahowallet/extension/suites/11996957930/artifacts/629886232) (as of Mon, 03 Apr 2023 16:48:32 GMT).
=> Add title to NFT market links

ui/components/SignTransaction/SignTransactionNetworkAccountInfoTopBar.tsx
Closes #3124
Latest build: [extension-builds-3241](https://github.com/tahowallet/extension/suites/12004971760/artifacts/630413718) (as of Mon, 03 Apr 2023 23:23:19 GMT).
=> Fix missing network icon on custom networks

ui/_locales/en/messages.json, ui/components/Shared/SharedSlideUpMenu.tsx, ui/components/TopMenu/TopMenu.tsx, ui/components/TopMenu/TopMenuProtocolList.tsx, ui/components/TopMenu/TopMenuProtocolListFooter.tsx
Updates footer according to new design for custom networks v1
Closes #3149 
```
```
Latest build: [extension-builds-3244](https://github.com/tahowallet/extension/suites/12015063375/artifacts/631180674) (as of Tue, 04 Apr 2023 10:13:53 GMT).
=> Custom Networks - Update Protocol List Footer

background/main.ts, background/redux-slices/assets.ts, background/services/chain/db.ts, background/services/chain/index.ts, background/services/chain/tests/db.integration.test.ts, background/services/chain/tests/index.integration.test.ts, background/services/indexing/index.ts
In addition to adding a path for importing tokens via _just_ their contract address - this PR fixes two important bugs related to custom networks.
1) Custom networks were not being returned from the `getNetworksToTrack` method. https://github.com/tahowallet/extension/commit/4382083c35bc5787be33cac75f2f1815cb609435
2) Balance checks on all networks were failing during the initial balance check on extension startup. https://github.com/tahowallet/extension/commit/63cbd8263c70df5ffebc198e32f3387d60d0c897
Add the following snippet inside of `internalStartService` in `main.ts`.
```
;(window as any).chainService = this.chainService
this.indexingService.addCustomAssetViaContractAddress(
"0x4EdF8E0778967012D46968ceadb75436d0426f88",
{
chainID: "1284",
coingeckoPlatformID: "moonbeam",
family: …
```
=> Add plumbing to allow for tokens to be imported via contract address

ui/components/TopMenu/TopMenuProtocolList.tsx
Per @VladUXUI clarification, the footer in the network switcher should not be fixed at the bottom.
Latest build: [extension-builds-3246](https://github.com/tahowallet/extension/suites/12042306255/artifacts/633141626) (as of Wed, 05 Apr 2023 10:09:24 GMT).
=> Remove sticky positioning from footer in network switcher

background/lib/posthog.ts, background/main.ts, background/services/analytics/index.ts, background/services/chain/index.ts, background/tests/factories.ts
Latest build: [extension-builds-3236](https://github.com/tahowallet/extension/suites/12046398882/artifacts/633415473) (as of Wed, 05 Apr 2023 13:17:48 GMT).
=> Add custom chain analytics event

background/lib/posthog.ts, background/main.ts, background/services/analytics/index.ts, background/services/chain/index.ts
Latest build: [extension-builds-3251](https://github.com/tahowallet/extension/suites/12047061858/artifacts/633461910) (as of Wed, 05 Apr 2023 13:43:45 GMT).
=> More Analytics Events

ui/components/AccountItem/ShowPrivateKey.tsx
This PR adds a wallet-unlocking step. The screen should appear whenever the user wants to open the slide-up menu for `Show Private Key`.
https://user-images.githubusercontent.com/23117945/230336203-550e0798-10b1-419c-bcd1-0e42ad81f59f.mov
Latest build: [extension-builds-3257](https://github.com/tahowallet/extension/suites/12068023649/artifacts/634995263) (as of Thu, 06 Apr 2023 09:40:41 GMT).
=> Unlock screen for the account backup 

.github/ISSUE_TEMPLATE/BUG.yml, .github/ISSUE_TEMPLATE/config.yml
We've been linking the `#feedback` Discord channel on the New GH Issue landing page. The channel no longer exists and the `#bug-report` channel is now a designated place for bug reporting in Discord.
Updating name of the channel and the invite link. The invite link does not have the expiry date and allows for unlimited use.
Latest build: [extension-builds-3258](https://github.com/tahowallet/extension/suites/12092805225/artifacts/636786921) (as of Fri, 07 Apr 2023 11:57:13 GMT).
=> Update link to the Discord channel for bug reporting

ui/components/Overview/OverviewAssetsTable.tsx
Closes #3098
This PR updates styles for the portfolio page.
Scope of changes:
1 All fonts in asset prices should have the same color. 
2 Move Asset(##) up a bit and add a table head with asset
Before
After 
Latest build: [extension-builds-3260](https://github.com/tahowallet/extension/suites/12074766657/artifacts/635464158) (as of Thu, 06 Apr 2023 14:52:42 GMT).
=> Style update for portfolio

ui/components/Shared/SharedSecretText.tsx
Chrome has a problem with rendering backdrop blur when content is scrolled, sometimes blur just disappears which is unacceptable for SharedSecretText component that handles private keys and mnemonics. Let's use `filter: blur()` rule as it seems to be working much better.
- export the mnemonic for HD wallet with a couple of accounts added, expand the accounts accordion so mnemonic's container is rendered out of the screen (at least partially)
- make sure blur is always present if you are not hovering the container with the mouse
- test private keys export flow as well
Latest build: [extension-builds-3265](https://github.com/tahowallet/extension/suites/12151916263/artifacts/641062230) (as of Tue, 11 Apr 2023 09:13:10 GMT).
=> Fix background blur issue

background/lib/alchemy.ts, background/lib/logger.ts, background/main.ts, background/redux-slices/assets.ts, background/services/chain/asset-data-helper.ts, background/services/chain/index.ts, ui/_locales/en/messages.json, ui/components/Shared/SharedInput.tsx, ui/components/Shared/SharedLink.tsx, ui/components/Shared/SharedTooltip.tsx, ui/components/Wallet/WalletAssetList.tsx, ui/pages/Settings.tsx, ui/pages/Settings/SettingsAddCustomAsset.tsx, ui/public/images/placeholder.svg, ui/routes/routes.tsx
Allows manually adding tokens from the asset list and the settings page
```
```
Latest build: [extension-builds-3261](https://github.com/tahowallet/extension/suites/12160852252/artifacts/641691473) (as of Tue, 11 Apr 2023 15:24:07 GMT).
=> Custom Token Import - Allow manually importing assets

background/redux-slices/migrations/index.ts, background/redux-slices/migrations/to-27.ts, background/redux-slices/selectors/accountsSelectors.ts, background/redux-slices/ui.ts, ui/_locales/en/messages.json, ui/components/Wallet/WalletAssetList.tsx, ui/components/Wallet/WalletHiddenAssets.tsx, ui/pages/Wallet.tsx
Closes #3224 
This PR separates hidden assets from non-hidden assets in the asset list. The `Hide Asset Balances under $2` should no longer hide untrusted assets. All hidden assets should be separated and displayed together.
Before
After
https://user-images.githubusercontent.com/23117945/231146605-98e9b23b-0b8c-4099-8d30-e39198d27c44.mov
Latest build: [extension-builds-3263](https://github.com/tahowallet/extension/suites/12179823482/artifacts/643115140) (as of Wed, 12 Apr 2023 09:29:23 GMT).
=> Separate assets in the asset list 

ui/components/Snackbar/Snackbar.tsx, ui/pages/Tab.tsx
Closes #3151 
This PR fixes a snackbar position for tabbed onboarding.  When we toggle default wallet on, the snackbar should be under the button and not centered.
https://user-images.githubusercontent.com/23117945/231990342-2ea58c25-1745-420f-adbf-bb3c293fdfbe.mov
Latest build: [extension-builds-3274](https://github.com/tahowallet/extension/suites/12281069291/artifacts/650518670) (as of Mon, 17 Apr 2023 10:12:25 GMT).
=> Fix a snackbar position for tabbed onboarding

background/services/keyring/index.ts
Resolves https://github.com/tahowallet/extension/issues/3276
If the account is added again, it should no longer be hidden, whether it was added with a private key or mnemonic.
Follow the steps described in the linked task or:
- add account with private key (first you have to export this private key in Metamask from the HD wallet with mnemonic you know)
- remove that account
- add HD wallet with mnemonic you used to export private key
You should be able to add the same address with both private key and mnemonic
Latest build: [extension-builds-3282](https://github.com/tahowallet/extension/suites/12315887155/artifacts/653029617) (as of Tue, 18 Apr 2023 14:45:36 GMT).
=> Fix unhiding removed accounts

ui/pages/Swap.tsx
Fixes the following issue: https://github.com/tahowallet/extension/pull/3147#issuecomment-1514254469
Hidden asset balances where not being loaded in the Swap page, after attempting to swap them by clicking an action from the wallet asset list the user would be redirected to the Swap page in an empty state.
Latest build: [extension-builds-3288](https://github.com/tahowallet/extension/suites/12351450295/artifacts/655656750) (as of Wed, 19 Apr 2023 19:53:15 GMT).
=> Check all asset amount balances in Swap page

ui/pages/Settings/SettingsCustomNetworks.tsx
Latest build: [extension-builds-3289](https://github.com/tahowallet/extension/suites/12353412413/artifacts/655804870) (as of Wed, 19 Apr 2023 21:23:51 GMT).
=> Update hover-color of delete network icon

background/main.ts, background/redux-slices/utils/asset-utils.ts, ui/pages/Settings/SettingsCustomNetworks.tsx
This somehow got reverted after merging main into #3233
Also includes a fix for the back button at custom networks settings page
```
```
Latest build: [extension-builds-3290](https://github.com/tahowallet/extension/suites/12366435754/artifacts/656801830) (as of Thu, 20 Apr 2023 11:10:14 GMT).
=> Mark imported assets as trusted

playwright.config.ts
We have a problem with the E2E test that was checking NFTs balance after a wallet was loaded.
Seems like this request may take longer than 30s but CI wasn't waiting long enough. Let's try making `expect` timeout 60s. Tried 5 times on this PR and it seems fine.
Latest build: [extension-builds-3300](https://github.com/tahowallet/extension/suites/12437097546/artifacts/661990529) (as of Mon, 24 Apr 2023 10:28:04 GMT).
=> Change expect timeout on CI to handle loading NFTs

ui/components/Signing/SignatureDetails/TransactionSignatureDetails/TransactionSignatureSummary/SwapAssetSummary.tsx
Closes #2651 
"Swap Assets" transaction confirmation screen shows an incorrect asset swap preview
Before
After
https://user-images.githubusercontent.com/23117945/233987911-98c35439-6814-41b6-88fd-08221fe60161.mov
Latest build: [extension-builds-3305](https://github.com/tahowallet/extension/suites/12439280615/artifacts/662140865) (as of Mon, 24 Apr 2023 12:02:04 GMT).
=> Fix the issue with showing an incorrect asset swap preview

background/main.ts, background/redux-slices/selectors/accountsSelectors.ts, ui/_locales/en/messages.json, ui/pages/Settings/SettingsAddCustomAsset.tsx
Shows a warning message when the user has enabled "Hide assets under 2$" and attempts to add a token which balance is below the threshold.
- `0xdbdb4d16eda451d0503b854cf79d55697f90c8df` You should see the dust balance warning
- `0x8965349fb649a33a30cbfda057d8ec2c48abe2a2` You should not see the warning as there's no price data
- `0x6c28AeF8977c9B773996d0e8376d2EE379446F2f` You should not see the warning since the $ value exceeds the threshold
Latest build: [extension-builds-3307](https://github.com/tahowallet/extension/suites/12466162180/artifacts/664180075) (as of Tue, 25 Apr 2023 11:12:04 GMT).
=> Display a warning message when custom asset balance is dust

background/main.ts, background/services/name/index.ts
Closes  #2097
When we add an account and then remove it, we do not clear the data in the name service. After re-adding, we do not update the names because they are still stored in `cachedResolvedNames`.  Check this part of the [code](https://github.com/tahowallet/extension/blob/main/background/services/name/index.ts#L299:L302). 
If you know of other steps to reproduce this issue let us know below.
Before
https://user-images.githubusercontent.com/23117945/234500672-711e1e7e-438f-414f-9126-5ac96a487816.mov
After
https://user-images.githubusercontent.com/23117945/234503355-33542e67-41a2-4b92-9459-0ccd31e17dc0.mov
Latest build: [extension-builds-3308](https://github.com/tahowallet/extension/suites/12470066557/artifacts/664454250) (as of Tue, 25 Apr 2023 13:49:58 GMT).
=> Fixing the account name issue when adding it again

ui/_locales/en/messages.json, ui/components/Shared/SharedNetworkIcon.tsx, ui/pages/Settings/SettingsAddCustomAsset.tsx
Closes #3317, #3318, #3319, #3320, #3324 
Also adds rounded corners to network fallback icons
Latest build: [extension-builds-3328](https://github.com/tahowallet/extension/suites/12515171347/artifacts/667837920) (as of Thu, 27 Apr 2023 04:55:52 GMT).
=> Custom Networks - Copy changes

ui/_locales/en/messages.json
Latest build: [extension-builds-3335](https://github.com/tahowallet/extension/suites/12538186689/artifacts/669589536) (as of Thu, 27 Apr 2023 22:27:38 GMT).
=> Add (beta) label to custom network menu options

background/constants/networks.ts, ui/components/SignTransaction/SignTransactionDetailPanel.tsx
Closes https://github.com/tahowallet/extension/issues/3326
Please check this [PR](https://github.com/tahowallet/extension/pull/3088). When the network has the ability to change fees, we should leave extra space for a possible warning that will appear. Otherwise, there should be no extra space. 
For internal swaps, we have an additional tab - "Raw data". When we make an external swap there is a problem with additional space for example for the Optimism network. In this case, we should leave extra space for a possible warning. It is not the best solution but it is a quick fix. 
Before
After
https://user-images.githubusercontent.com/23117945/235107275-8b4f5fa2-bfc6-4635-95aa-e85349eae4a3.mov
**Extreme case**
https://user-images.githubusercontent.com/23117945/235142515-606be4de-0c6d-442f-b79c- …
=> Fix style regression issue for transaction warning

ui/components/Shared/SharedNetworkIcon.tsx
Closes https://github.com/tahowallet/extension/issues/3321
It looks like the dynamic sizing wasn't working at all so we would get a border radius of 0px every time.
Addressed per https://github.com/tahowallet/extension/issues/3321#issuecomment-1527118305
Latest build: [extension-builds-3352](https://github.com/tahowallet/extension/suites/12606759478/artifacts/674557353) (as of Tue, 02 May 2023 01:07:23 GMT).
=> Round corners on custom network icons

ui/components/InternalSigner/InternalSignerUnlock.tsx
To prevent Enter keypress to mess with other components listening for that key let's catch it on the Unlock screen so user can type password and press Enter to confirm.
Confirm you can unlock by pressing Enter on:
Latest build: [extension-builds-3355](https://github.com/tahowallet/extension/suites/12615522781/artifacts/675227855) (as of Tue, 02 May 2023 10:41:45 GMT).
=> Catch Enter keypress on Unlock screen

.github/workflows/test-list/release-test-list.md
Abilities should not be displayed for read-only accounts.
**_Originally posted in https://github.com/tahowallet/extension/pull/3304#discussion_r1184669786_**
Latest build: [extension-builds-3364](https://github.com/tahowallet/extension/suites/12695934333/artifacts/681289464) (as of Fri, 05 May 2023 09:21:57 GMT).
=> Fix the issue for QA checklist

background/main.ts, background/services/ledger/index.ts, background/services/signing/index.ts
> “By failing to prepare, you are preparing to fail.”
>
> ― Benjamin Franklin
Some signers can require various types of setup when a new signing request is about to come in. Two quick examples are hardware wallets, which may need to explicitly refresh the connection state to make sure that the wallet is still connected and ready, or remote signers like WalletConnect (currently not supported), which might need to establish a remote connection to be able to make a request.
For the case where a Ledger did not have arbitrary data signing enabled specifically, 8dc160b landed a fix where a full connection refresh would be kicked off, fixing a specific bug. However, this led to an issue where arbitrary data signing information would be checked in certain cases when a Ledger was disconnected, …
=> Failing to Prepare: Add a SigningService hook for pre-notifying signers of a request

background/redux-slices/abilities.ts, background/services/internal-signer/index.ts, background/services/internal-signer/tests/index.unit.test.ts, background/services/signing/index.ts
Improvement mentioned in the [RFB 4: One-Off Keyring Design](https://github.com/tahowallet/extension/pull/3372/commits/6c71c8de122ab2e59f71e77c5d246921fccbcd90#diff-ed55cc77a7760815ad539b38803831098099e4912702cee612fa3565656a39bfR163-R165)
To avoid storing duplicated key material let's remove duplicated accounts, HD wallet accounts should have higher priority than accounts imported with single private key.
This was already working as intended from a user perspective but we were leaving "orphaned" duplicated accounts in the service
Latest build: [extension-builds-3377](https://github.com/tahowallet/extension/suites/12854108486/artifacts/692919980) (as of Fri, 12 May 2023 11:21:11 GMT).
=> Remove private key signers if they are replaced by accounts from HD wallet

rfb/rfb-4-one-off-keyring-design.adoc
Retrospective RFB for the base work in #3089 (the internal signer service and the hd-keyring work that underpinned exports there).
Latest build: [extension-builds-3372](https://github.com/tahowallet/extension/suites/12839223276/artifacts/691769831) (as of Thu, 11 May 2023 19:49:06 GMT).
=> RFB 4: One-Off Keyring Design

background/redux-slices/selectors/accountsSelectors.ts, ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
Previously, the only type of id being taken into account to differentiate between different signers was the keyring id. This meant that two accounts from two different Ledgers appeared under the same entry in the account list, "Ledger 1". Additionally, it meant if you renamed the Ledger category, it was for all Ledgers, not just for one.
The underlying change to fix this is fairly minor: `keyringId` is now generalized to `signerId`, which is derived separately for each account signer type. The derivation is set up such that adding a signer type will require specifying how to differentiate between signers of that type. Any signers that prefer not to differentiate can return `null`, or another value.
NOTE: this change will probably interact with #3089 !
The easiest way to test is to add two …
=> Ledger-en-dary: Categorize accounts by signer id instead of just keyring id

ui/components/Shared/SharedActivityIcon.tsx, ui/components/Wallet/WalletActivityDetails.tsx, ui/components/Wallet/WalletActivityList.tsx, ui/components/Wallet/WalletActivityListItem.tsx, ui/hooks/activity-hooks.ts, ui/pages/Wallet.tsx
Closes #1167 
This PR adds a header to the transaction details view and solves the problem of missing header for the custom network. Changes:
-  Separate component for the activity icon
- Special hook to return activity details view
- Minor improvements
In addition, the problem with missing padding when the network does not have NFTs has been fixed, check the screenshots below.
**Before**
**After**
Latest build: [extension-builds-3387](https://github.com/tahowallet/extension/suites/12979887290/artifacts/702340713) (as of Thu, 18 May 2023 07:07:45 GMT).
=> Add header  in transaction details view

background/services/indexing/index.ts
[Changes](https://github.com/tahowallet/extension/blob/main/background/services/indexing/index.ts#L589:#L602) for verified/unverified tokens have resulted in an error about importing custom tokens. The metadata has not been set correctly. This caused imported tokens to be added to the db as unverified assets. By default, these assets should be verified.
Before
After
https://github.com/tahowallet/extension/assets/23117945/5a1f4b77-ef66-4d80-8547-88d54fce1b8d
Use `testertesting.eth` account for the Fantom network. 
Latest build: [extension-builds-3423](https://github.com/tahowallet/extension/suites/13262265640/artifacts/723282407) (as of Wed, 31 May 2023 06:58:35 GMT).
=> Fix the issue of adding a custom token

background/constants/base-assets.ts, background/constants/currencies.ts, background/constants/networks.ts, background/lib/simple-hash_update.ts, background/nfts.ts, ui/components/NFTS_update/ExploreMarketLink.tsx, ui/components/NFTS_update/NFTPreview.tsx, ui/components/Shared/SharedButtonUp.tsx, ui/components/Shared/SharedNetworkIcon.tsx
- support NFTs on zkSync
- fix button up icon
- fix custom network icon on NFT thumbnails
Latest build: [extension-builds-3425](https://github.com/tahowallet/extension/suites/13291296855/artifacts/725535967) (as of Thu, 01 Jun 2023 06:22:34 GMT).
=> Add zkSync custom network to NFTs supported networks

ui/components/NetworkFees/FeeSettingsText.tsx
Prevents a crash when trying to send funds after adding a network under slow network conditions or certain RPCs
Latest build: [extension-builds-3434](https://github.com/tahowallet/extension/suites/13375997039/artifacts/731891139) (as of Mon, 05 Jun 2023 12:10:42 GMT).
=> Fix UI crash when gas fee data is unavailable

background/redux-slices/assets.ts, background/redux-slices/migrations/index.ts, background/redux-slices/migrations/to-29.ts, background/redux-slices/utils/asset-utils.ts, background/redux-slices/utils/tests/asset-utils.unit.test.ts
Closes #3445 
Fixes an issue when caching assets in the redux state that did not correctly handle already existing network base assets.
Latest build: [extension-builds-3431](https://github.com/tahowallet/extension/suites/13384491623/artifacts/732526029) (as of Mon, 05 Jun 2023 17:25:44 GMT).
=> Fix duplicate base assets being stored in redux asset cache

background/redux-slices/selectors/0xSwapSelectors.ts, background/redux-slices/utils/asset-utils.ts, ui/pages/Send.tsx, ui/utils/swap.ts
Closes https://github.com/tahowallet/extension/issues/3438
The user should not be able to send and swap unverified assets. In addition, assets with 0 balance should not appear in the list of assets.
Before
https://github.com/tahowallet/extension/assets/23117945/44eb61d8-9783-4c55-8a43-b7850cfe457c
After
https://github.com/tahowallet/extension/assets/23117945/c549328e-d03e-4d7f-a488-46c3add42df5
```
SUPPORT_UNVERIFIED_ASSET=true
```
Latest build: [extension-builds-3452](https://github.com/tahowallet/extension/suites/13430489328/artifacts/736164593) (as of Wed, 07 Jun 2023 09:22:45 GMT).
=> Fix issue for assets list for swapping/sending 

ui/_locales/en/messages.json, ui/components/DAppConnection/DAppConnectionDefaultToggle.tsx, ui/components/DAppConnection/DAppConnectionInfoBar.tsx, ui/components/TopMenu/TopMenuConnectedDAppInfo.tsx, ui/pages/DAppConnect/DAppConnectPage.tsx
The dApp Connect popup now shows the top bar for switching
between Taho being default and not, and includes an explanatory
popover triggered by clicking on an `i` icon.
This PR does not yet implement the “first time” flow, where the
default wallet explanation appears without user interaction;
that is in #3464. It also does not implement automatically closing
the dApp connection popup and bringing up the next wallet if
default connection is turned off; that is in #3462.
The Taho dApp connection flow should come up.
matches the one in the wallet popup.
popup should show the same default state.
dApp Connection modal, then reloading the dApp and attempting
to connect, should trigger the other wallet's dApp Connection
flow.
Additionally, without updated dApp Connections enabled:
The Taho dApp …
=> Cable Connection: Implement standard flow for dApp connect popup

ui/components/Core/CorePage.tsx
In addition to being unnecessary, this z-index was preventing SharedSlideUps from properly overlaying on top of the tab bar by creating a new stacking context. Whoops!
Latest build: [extension-builds-3476](https://github.com/tahowallet/extension/suites/13586815056/artifacts/748529675) (as of Wed, 14 Jun 2023 02:56:08 GMT).
=> Slide On Over: Drop an unnecessary z-index on CorePage

background/abilities.ts, background/services/abilities/index.ts
Currently, all abilities are fetched from one endpoint. In about two weeks' time, the abilities type the `article` and the `result` should be fetched from another endpoint. Let's exclude these types and then, in the next steps, retrieve them from another endpoint. 
https://github.com/tahowallet/extension/assets/23117945/9586609d-3719-42c6-889c-1dcff932bf4a
Latest build: [extension-builds-3479](https://github.com/tahowallet/extension/suites/13624732258/artifacts/751620264) (as of Thu, 15 Jun 2023 10:02:31 GMT).
=> Exclude `article` and `result` types for abilities

background/services/provider-bridge/index.ts, env.d.ts, src/window-provider.ts, ui/pages/DAppConnect/DAppConnectPage.tsx, window-provider/index.ts
Adds the ability to pass through to the next provider as soon
as the user toggles default wallet off.
Can be reviewed and merged separately from #3451.
Ex:
https://github.com/tahowallet/extension/assets/8245/9fcb3c77-8242-4461-831b-7988243be4ed
Note that you can get into a state where you've previously requested a MetaMask connection, but did not complete the flow (e.g. by not unlocking MetaMask). In this case MetaMask will auto-decline the connection request from the dApp, so the above flow will appear not to work. Make sure MetaMask is in an unlocked idle state before testing the flow above.
```
ENABLE_UPDATED_DAPP_CONNECTIONS=true
```
Latest build: [extension-builds-3462](https://github.com/tahowallet/extension/suites/13633228421/artifacts/752242181) (as of Thu, 15 Jun 2023 15:12:02 …
=> Repeater Connection: Forward requests to new default when default is switched off during dApp connection flow

background/lib/gas.ts, background/services/indexing/index.ts, background/services/indexing/token-list-edit.ts
Looks like matic.network has been fully decommissioned, and for both gas prices and for the PoS WETH asset, we were relying on it. Move to polygon.technology equivalents.
In practice, the asset SVG for PoS WETH won't be used because newer versions of the Polygon token lists don't include the broken WETH asset that we were substituting in. We keep it because it's referenced in a migration and I would rather not try to figure out if it's safe to kill the migration for now.
Fixes #3482 .
Latest build: [extension-builds-3483](https://github.com/tahowallet/extension/suites/13645026026/artifacts/753192433) (as of Fri, 16 Jun 2023 00:51:51 GMT).
=> Auto-Not-So-Matic: Fix two matic.network URLs to polygon.technology

background/main.ts, background/redux-slices/ui.ts, background/services/preferences/db.ts, background/services/preferences/index.ts, ui/components/DAppConnection/DAppConnectionDefaultToggle.tsx, ui/components/DAppConnection/DAppConnectionInfoBar.tsx, ui/components/Shared/SharedToggleButton.tsx
Draft until #3451 lands.
Adds a `DismissableItem` concept and related functionality to the
`PreferencesService` and to the UI slice, providing a common pattern
for things that should be shown to the user exactly once, e.g. new
feature banners and related functions.
This PR will complete the work on updated dApp connections.
Latest build: [extension-builds-3464](https://github.com/tahowallet/extension/suites/13641442570/artifacts/752912241) (as of Thu, 15 Jun 2023 20:55:13 GMT).
=> Case Dismissed: Forcibly show DAppConnectionInfoBar popover on first dApp connection

e2e-tests/nfts.spec.ts, e2e-tests/utils/onboarding.ts
We have configured a ENS name for the
`0x6f1b1f1feb01235e15a7962f16c389c7f8218ed6` address. We need to update the tests to reflect that.
Latest build: [extension-builds-3494](https://github.com/tahowallet/extension/suites/13792525506/artifacts/764721892) (as of Thu, 22 Jun 2023 14:20:28 GMT).
=> Change expected account name in NFTs tests to ENS domain

ui/components/Shared/SharedCheckbox.tsx
Compiled refactors of the Checkbox component from https://github.com/tahowallet/extension/pull/3455 and https://github.com/tahowallet/extension/pull/3488 as these are not going to be merged to `main` soon. 
- new styles
- allows checkbox to be disabled
- allows checkbox to show error message
- allows to display label on both sides of the checkbox
On this branch (main) checkbox is not used anywhere right now.
Latest build: [extension-builds-3495](https://github.com/tahowallet/extension/suites/13815587027/artifacts/766623220) (as of Fri, 23 Jun 2023 11:09:22 GMT).
=> Refactor and fix styles for SharedCheckbox component

e2e-tests/utils/onboarding.ts
Under certain conditions, running e2e tests would sometimes open up a third, blank tab which caused an onboarding helper to fail setting the page to run the tests correctly or even executing the test run.
There are a few ways to test this fix addresses the issue:
- Run `PWDebug=1 npx playwright test`, after opening the browser the tests should run normally (might need to click play button on the playwright debugger).
- Run `PWDebug=console npx playwright test`, after opening the browser the tests should run normally.
- Run `npx playwright test`, tests should also run normally
- Check CI e2e runs still work
Latest build: [extension-builds-3503](https://github.com/tahowallet/extension/suites/13878762407/artifacts/771453927) (as of Mon, 26 Jun 2023 22:16:46 GMT).
=> Fix E2E onboarding helper

.github/workflows/build.yml
So far, we've been running E2E tests only when a PR was changing feature flag, contained `e2e` in the name of the feature branch or got merged to `main`. This prevented us from noticing changes braking E2E tests fast enough - we sometimes were noticing such changes only after they got already merged to `main`. In this commit we modify CI config in a way that most of the E2E tests will be run on every PR update. We also allow for specifying tests which shouldn't be run this often - such tests should be marked with `@slow` tag in the test name (read more here: https://playwright.dev/docs/test-annotations#tag-tests). We may want to use this feature when we'll have tests that require spending some funds.
Note: depending on which PR gets merged first, we may need to update either this PR or …
=> Execute E2E tests more frequently

background/services/preferences/db.ts, background/services/preferences/defaults.ts
Closes https://github.com/tahowallet/extension/issues/3391
Closes https://github.com/tahowallet/extension/issues/3501
The current list of tokens in the application is not updated. We should update it every time new tokens are added.
Before
After
Test address - `0x23Dd978A22f81e29941358Dbb0eAde9F53389Eb2`
Latest build: [extension-builds-3506](https://github.com/tahowallet/extension/suites/13972850715/artifacts/779111374) (as of Fri, 30 Jun 2023 08:19:57 GMT).
=> Update Taho token list reference

.github/workflows/build.yml
In commit https://github.com/tahowallet/extension/commit/780d6d4eb817d05300a8458e534a10d1fa12e4ca we've turned off uploading of
build artifact to workflow details in case when the workflow is triggered by a
push of tag. Later in https://github.com/tahowallet/extension/commit/168d945c0e138c250ca4edac27f9071a59fb0d83 we've decided to
change conditions of e2e tests execution to run the tests more frequently. But
we've forgotten that we can't run the tests when workflow is triggered by a tag
push, as there is no build artifact available. Now we're updating the triggers
of e2e tests to take that under consideration.
Latest build: [extension-builds-3514](https://github.com/tahowallet/extension/suites/14023914491/artifacts/782964063) (as of Mon, 03 Jul 2023 11:15:24 GMT).
=> Don't run e2e tests when workflow is triggered by push of tag

background/redux-slices/selectors/nftsSelectors.ts, background/redux-slices/utils/nfts-utils.ts
Follow up for https://github.com/tahowallet/extension/pull/3486
Add fallback from name to address in NFT filters. To avoid NFT filters throwing error when the account is not yet loaded let's add a fallback from name to address to put in the SharedToggle label.
Latest build: [extension-builds-3513](https://github.com/tahowallet/extension/suites/14022443935/artifacts/782867040) (as of Mon, 03 Jul 2023 10:15:53 GMT).
=> Fix throwing NFT filters panel

ui/pages/Swap.tsx
Resolves https://github.com/tahowallet/extension/issues/3515
Let's not override gas price that 0x gave us for Optimism transactions, as our existing fee handling for Optimism has been broken by the EIP-1559 functionality added in the last network upgrade.
This should be tested on all networks that are supporting swaps. This can potentially result in high gas fees so you can block broadcasting transaction to avoid loosing money for testing (for example throwing error [here](https://github.com/tahowallet/extension/blob/swaps-on-op/background/services/chain/index.ts#L1190) and logging transaction instead) You should check if gas prices are matching market values.
Latest build: [extension-builds-3516](https://github.com/tahowallet/extension/suites/14029858033/artifacts/783404247) (as of Mon, …
=> Use gas price from 0x quote to setup swap transaction

.github/workflows/sync-pledge.yml
New workflow to sync pledge was missing information about CI environment
Latest build: [extension-builds-3519](https://github.com/tahowallet/extension/suites/14038097612/artifacts/783985722) (as of Mon, 03 Jul 2023 23:10:26 GMT).
=> Fix invalid workflow file

.github/workflows/sync-pledge.yml
Follow up on #3519, this removes a trigger used for testing and fixing issues with the new workflow
Latest build: [extension-builds-3520](https://github.com/tahowallet/extension/suites/14041155744/artifacts/784212517) (as of Tue, 04 Jul 2023 03:54:47 GMT).
=> Remove workflow trigger used for testing

background/redux-slices/migrations/to-31.ts
Migration should be ready to handle accounts that are in a loading state without throwing and breaking the extension.
Latest build: [extension-builds-3527](https://github.com/tahowallet/extension/suites/14071112936/artifacts/786522923) (as of Wed, 05 Jul 2023 09:15:07 GMT).
=> Fix migration for cleaning account balances

e2e-tests/nfts.spec.ts
If the NFT page is loading really fast then the "loading doggo" animation may not be visible for long enough to allow the e2e test to catch that element. As the loader itself is not necessary for the rest of the test let's omit testing for loader visibility, we can just test if the loader disappeared.
Latest build: [extension-builds-3541](https://github.com/tahowallet/extension/suites/14183949363/artifacts/795270419) (as of Mon, 10 Jul 2023 14:09:54 GMT).
=> Remove waiting for Loading Doggo component in E2E tests

background/redux-slices/utils/contract-utils.ts, env.d.ts, provider-bridge/index.ts, src/provider-bridge.ts, src/window-provider.ts, window-provider/index.ts
Up until now, Taho's approach to being marked as default was meant to
be roughly:
- If Taho is marked as default, and the dApp supports showing a non-MetaMask
provider at `window.ethereum`, make Taho that provider.
- If Taho is marked as default, and the dApp *doesn't* support showing a non
MetaMask provider, have Taho impersonate MetaMask so that users can still
connect using Taho.
- If Taho is marked as not-default, leave everything untouched, and only
show Taho for dApps that specifically look for it (typically at `window.tally`,
but sometimes in `window.ethereum.providers`).
For this to work, the window provider was tracking an allowlist of sites to
impersonate MetaMask on, and it was *also* tracking an allowlist of sites to
do additional tricks on (e.g. returning a blank `providers` …
=> Sticky Defaults: Make Taho-as-default replace MetaMask in almost all cases

background/lib/priceOracle.ts, background/services/internal-signer/index.ts
Two fixes here, one for a small edge case in internal signer emission
that meant that if for some reason the internal signers data was cleared
in redux, it would never be correctly repopulated (expectation is that
there's no production scenario that would really trigger this).
The other is an issue where adding a network to the extension that didn't
have an associated spot price oracle listed would cause price lookups for
that network to fail, and this would cascade into failing all price lookups.
The correct fix for the latter is probably to make price lookups less sensitive
to individual failure, but for now I'm making the spot price oracle bit be
safe for networks that don't have an entry in the spot price oracle list.
Latest build: …
=> Buggity fixes: two small bug fixes

background/differ.ts, background/index.ts, background/main.ts
In the current implementation, `bigints` are treated as objects and are incorrectly excluded from generated patches. This fixes `bigint` diffing by adding a handler for these cases to the `jsondiffpatch` pipeline.
Latest build: [extension-builds-3561](https://github.com/tahowallet/extension/suites/14449081920/artifacts/815732866) (as of Thu, 20 Jul 2023 17:02:04 GMT).
=> Add bigint filter for jsondiffpatch

.github/workflows/build.yml
Added a suffix to the fork-related assets and changed the workflow steps to publish the correct production build as the release asset.
Latest build: [extension-builds-3564](https://github.com/tahowallet/extension/suites/14480268296/artifacts/818192057) (as of Fri, 21 Jul 2023 19:49:40 GMT).
=> Fix incorrect build asset uploaded on release

.github/workflows/build.yml
The ungated 0x API has been sunset, meaning we need an API key for dev builds to work.
Latest build: [extension-builds-3565](https://github.com/tahowallet/extension/suites/14481912198/artifacts/818327456) (as of Fri, 21 Jul 2023 21:16:07 GMT).
=> Add dev 0x API key to dev build

ui/_locales/en/messages.json
When there are no activities listed on the Activity pane I noticed that there was a typo in the default text.
Latest build: [extension-builds-3584](https://github.com/tahowallet/extension/suites/14671307315/artifacts/832623799) (as of Sun, 30 Jul 2023 05:23:40 GMT).
=> Fix typo on activity section default text

.github/workflows/test-list/release-test-list.md
- Changed "overview" to "portfolio" to match the new name of the page in the extension
- Added a test to read-only accounts so that we're explicitly checking that these accounts don't have export options for private key and recovery phrase.
Latest build: [extension-builds-3575](https://github.com/tahowallet/extension/suites/14642864832/artifacts/830631345) (as of Fri, 28 Jul 2023 13:08:31 GMT).
=> Update release-test-list.md: changed outdated terminology and added tests for new features

background/constants/networks.ts, background/services/chain/serial-fallback-provider.ts, background/services/chain/tests/serial-fallback-provider.integration.test.ts, background/tests/utils.ts, scripts/unreliable-rpc-provider-utils.ts, scripts/unreliable-rpc-provider.mjs
If some RPC request fails because of a timeout we should change to a different RPC provider. Tested on reproduced problem with `ankr` RPC
- Patch default providers https://github.com/tahowallet/extension/blob/7c88a8629088ce2e718e5cbc48571f99534f1a03/background/constants/networks.ts#L185 using `patchRPCURLS` from https://github.com/tahowallet/extension/blob/7c88a8629088ce2e718e5cbc48571f99534f1a03/scripts/unreliable-rpc-provider-utils.ts
- Run `node scripts/unreliable-rpc-provider.mjs`
- Reinstall the extension, open the background inspector and check that providers are being switched on timeouts/server errors
- Onboard an account, perform a few actions. Verify the wallet is handling errors gracefully
Latest build: [extension-builds-3587](https://github.com/tahowallet/extension/suites/14751 …
=> Change current provider on timeouted RPC requests

env.d.ts, src/window-provider.ts, window-provider/index.ts
- Uniswap should now update default wallet without reloads (closes #3578).
- Stargate should correctly handle transfers when the chain needs to be changed behind the scenes.
- Generally sites that may interact with event handlers before Taho's default status is read should no longer have issues.
Latest build: [extension-builds-3593](https://github.com/tahowallet/extension/suites/14936639887/artifacts/851517366) (as of Wed, 09 Aug 2023 02:29:24 GMT).
=> DAppstrosities: Fix a few observed dApp connection issues

.github/workflows/test-list/release-test-list.md
Mintkudos site's been sunset; Added explicit test for Personal Sign
Latest build: [extension-builds-3600](https://github.com/tahowallet/extension/suites/15107712796/artifacts/863252032) (as of Tue, 15 Aug 2023 13:27:27 GMT).
=> Updates to release checklist: Removed Mintkudos test

background/redux-slices/selectors/accountsSelectors.ts
When the signer id abstraction was introduced, I misunderstood each private key as needing to be treated as its own signer. In fact, we treat, on the UI side, all private keys as a single signer group. To fix this, rather than return the wallet id for the signer in these cases, we just return the constant string `"private-key"`. This ensures all private keys are categorized together.
Fixes #3606.
Latest build: [extension-builds-3618](https://github.com/tahowallet/extension/suites/15767975455/artifacts/899975852) (as of Sun, 03 Sep 2023 04:04:18 GMT).
=> Group private keys when categorizing

background/lib/posthog.ts, background/main.ts, background/services/analytics/index.ts, background/services/internal-signer/index.ts, background/services/internal-signer/tests/index.integration.test.ts, background/services/provider-bridge/index.ts, background/tests/factories.ts
This PR does two core things:
- Moves responsibility for more event tracking into the AnalyticsService itself.
- Adds tracking events for when data is signed and when there is an error signing data or transactions. The data signed and signature are not sent to Posthog, and in the case of errors only a generic set of errors is sent (rather than full error data).
Note that there is still a lot of unnecessary event management happening in `Main`, which should just be event observations from `AnalyticsService`. These can be handled at a later time.
Latest build: [extension-builds-3623](https://github.com/tahowallet/extension/suites/15873783826/artifacts/905833489) (as of Wed, 06 Sep 2023 10:24:01 GMT).
=> Joint Privacy: Rework analytics service event management and add signing tracking

.github/workflows/pledge-signer-sync/pledge-sync.js, .github/workflows/sync-pledge.yml
We want to update the pledge sync job to run daily rather than every three days so that no new pledge signers (or old community who havent signed, but now need to) are missed.
Latest build: [extension-builds-3626](https://github.com/tahowallet/extension/suites/16161486375/artifacts/922815423) (as of Thu, 14 Sep 2023 10:48:13 GMT).
=> Run pledge sync daily

background/constants/networks.ts, background/services/chain/taho-provider.ts, ui/_locales/en/messages.json, ui/components/TopMenu/TopMenuProtocolList.tsx
In this PR we address the leftover comments from the review of https://github.com/tahowallet/extension/pull/3633 (_Add support for Mainnet Sepolia and Arbitrum Sepolia testnets_).
Latest build: [extension-builds-3636](https://github.com/tahowallet/extension/suites/16906558298/artifacts/965879218) (as of Thu, 05 Oct 2023 11:15:11 GMT).
=> Sepolia support - small fixes

.github/workflows/build.yml, e2e-tests/fork-based/transactions.spec.ts, e2e-tests/regular/nfts.spec.ts, e2e-tests/regular/token-trust.spec.ts, e2e-tests/regular/transactions.spec.ts, e2e-tests/utils/onboarding.ts
We've rotated the wallets used for testing of the extension and moved some of the assets. The GH secrets got already updated accordingly, we now need to update the addresses of wallets and change some other values used in tests, to fit the assets that we have on the new testing wallets. Changes include:
* switching of `e2e.testertesting.eth` wallet from `0x6f1b1f1feb01235e15a7962f16c389c7f8218ed6` to `0x9d373acbe8540895fa1752ab463ab31bbab2b38f`
* switching of `testertesting.eth` wallet from `0x0581470a8b62bd35dbf121a6329d43e7edd20fc7` to `0x6e80164ea60673d64d5d6228beb684a1274bb017`
* changing the POAP used in the NFTs tests
* changing the number of a forking block (the new testing wallet didn't have any assets yet on an old forking block) and switching to a different asset used in tests …
=> Update e2e tests after change of testing accounts

background/services/internal-ethereum-provider/db.ts, background/services/internal-ethereum-provider/index.ts, background/services/provider-bridge/index.ts
Draft until I fill in some testing details.
The actual implementation is a little more subtle: permissions are for an origin AND a network. If the permission being cleared is for the origin's current network, as tracked in the `InternalEthereumProvider`, then that current network is cleared so that future interactions can set it.
Latest build: [extension-builds-3616](https://github.com/tahowallet/extension/suites/15762123848/artifacts/899755021) (as of Sat, 02 Sep 2023 20:14:11 GMT).
=> Unsettled Networks: Clear an origin's current network when revoking dApp permissions

patches/@ledgerhq+hw-app-eth+6.33.4.patch
It currently seems like there is an issue with Ledger's handling of high chain ids for certain transactions, where the Ledger can provide a first byte that breaks the expectations of the chain id adjustment done for legacy transactions to conform to EIP-155. The resulting `v` value returned from the signing flow is invalid and Ethers throws because of this.
This fix *may* be correct, but it may not be. To adjust for this fact, the patch limits adjustments of the underlying parity value in Ledger to happen only when the chain id matches Arbitrum Sepolia's (412614), as that's the only place we've seen consistent reports of the issue.
See also https://github.com/LedgerHQ/ledger-live/issues/5265 .
Fixes #3647 .
- Easiest way to test here is really to just hammer https://app.taho.xyz/ . In …
=> Sepo-Ledger: Patch @ledgerhq/hw-app-eth for Arbitrum Sepolia chain id handling

.github/workflows/test-list/release-test-list.md
We change the release test list to add checking whether disconnecting from dapp via Settings and connecting again on different network is possible.
Latest build: [extension-builds-3654](https://github.com/tahowallet/extension/suites/17889924808/artifacts/1027337007) (as of Fri, 03 Nov 2023 17:15:48 GMT).
=> Check connecting to dapp on different network after disconnecting

ui/components/DAppConnection/DAppConnection.tsx, ui/components/Signing/SignatureDetails/TransactionSignatureDetails/TransactionSignatureSummary/SpendApprovalSummary.tsx, ui/hooks/dapp-hooks.ts
Resolves https://github.com/tahowallet/extension/issues/3661
- Add a reusable hook that will handle finding a browser tab currently connected to the wallet to make it easier to display info about connected dapp. 
- Don't use `lastFocusedWindow` argument so window popup (token spend approval) can use the same hook for finding connected dapp.
Latest build: [extension-builds-3671](https://github.com/tahowallet/extension/suites/18184789698/artifacts/1049527106) (as of Tue, 14 Nov 2023 17:55:43 GMT).
=> Fix getting currently connected dapp info

README.md, background/main.ts, background/redux-slices/ui.ts, background/services/notifications/index.ts, background/services/preferences/db.ts, background/services/preferences/defaults.ts, background/services/preferences/index.ts, manifest/manifest.json, ui/_locales/en/messages.json, ui/components/Wallet/Banner/PortalBanner.tsx, ui/components/Wallet/WalletSubscapeLink.tsx, ui/pages/Settings.tsx
This PR adds notification-related preference, service, optional manifest permission,
and code to request the permission on Subscape banner click.
More to come!
-------------
UPDATE: 11/20/23
PR is rebased with the main branch. Force push was required because of unverified commits.
To open a dialog window with a request notification you need to click the link hidden in the Subscape bubble.
The first push notification will be added in #3667
Latest build: [extension-builds-3666](https://github.com/tahowallet/extension/suites/18412947056/artifacts/1067032376) (as of Wed, 22 Nov 2023 13:41:33 GMT).
=> Do notify: Set up base NotificationService

background/services/island/contracts.ts, background/services/island/index.ts
Resolves https://github.com/tahowallet/extension/issues/3693
As we have new realms not pre-named in the protocol let's add them by addresses
Latest build: [extension-builds-3695](https://github.com/tahowallet/extension/suites/18973789557/artifacts/1109219752) (as of Tue, 12 Dec 2023 13:43:30 GMT).
=> Add Subscape realms by adddress not name

.github/workflows/pledge-signer-sync/pledge-export.js
Let's allow to save pledge signers to JSON files using format supported on Snapshot.
Doesn't need testing, committing this file to the repo to have a reference in the future.
Latest build: [extension-builds-3698](https://github.com/tahowallet/extension/suites/19015853280/artifacts/1112431839) (as of Wed, 13 Dec 2023 16:24:07 GMT).
=> Create script to export pledge signers

background/services/chain/db.ts
Resolves https://github.com/tahowallet/extension/issues/3685
Add database transaction dependency to fix removing items from `customRpcConfig` table.
Latest build: [extension-builds-3699](https://github.com/tahowallet/extension/suites/19016838762/artifacts/1114194310) (as of Thu, 14 Dec 2023 09:34:36 GMT).
=> Fix removing custom networks

background/services/island/index.ts
Listening on realm contracts causes `eth_getLogs` to spam RPC node. Let's disable for now to stop spamming Alchemy.
- take a look at the prod extension - it is spamming `eth_getLogs` constantly
- check here - there is no more spam
=> Disable listeners on realm contract

.github/workflows/test-list/release-test-list.md
We want to make sure that during the release testing the tests are executed with an open DevTools window and that the logs and network traffic are monitored.
Latest build: [extension-builds-3704](https://github.com/tahowallet/extension/suites/19073390611/artifacts/1116830471) (as of Fri, 15 Dec 2023 09:04:07 GMT).
=> Check DevTools when executing tests on release testlist

background/constants/networks.ts
As Goerli testnets becomes deprecated with end of 2023, we've been migrating to another testnet - Sepolia. Up to this point we were not able to support swaps there, as 0x did not support Sepolia. But recently 0x created theAPI endpoint for Sepolia, so we're now able to use their services.
Read more: https://0x.org/docs/0x-swap-api/api-references/overview.
Tests:
Latest build: [extension-builds-3710](https://github.com/tahowallet/extension/suites/19134730944/artifacts/1121134638) (as of Mon, 18 Dec 2023 11:08:22 GMT).
=> Enable swaps on Sepolia testnet

ui/components/Shared/SharedAddressInput.tsx, ui/components/Shared/SharedInput.tsx, ui/pages/Onboarding/Tabbed/ViewOnlyWallet.tsx
Resolves #3686
Refactored read-only wallet form, not to submit the form automatically - preventing the infinite loading spinner
Latest build: [extension-builds-3705](https://github.com/tahowallet/extension/suites/19134208688/artifacts/1121095791) (as of Mon, 18 Dec 2023 10:49:33 GMT).
=> Prevent read-only address submission when validating input

ui/components/NFTs/Filters/NFTsFilters.tsx, ui/components/Shared/SharedAddress.tsx, ui/components/Shared/SharedButton.tsx, ui/components/Shared/SharedInput.tsx, ui/pages/Abilities/AbilityFilter.tsx
Resolves #2939 
Fixed some minor UI issues
Latest build: [extension-builds-3716](https://github.com/tahowallet/extension/suites/19205726225/artifacts/1126415583) (as of Wed, 20 Dec 2023 12:10:53 GMT).
=> Minor UI issues

ui/components/Claim/ClaimSuccessModalContent.tsx, ui/components/SignData/EIP4361Info.tsx, ui/pages/Earn/NotificationVaults.tsx
Hopefully working now ? Sorry for wasting your time.
=> chore(ui): typo fix

e2e-tests/regular/transactions.spec.ts
With Sepolia being deprecated with end of 2023 we need to switch the e2e tests that are run on that testnet to a different testnet. Instead of Goerli we'll use Ethereum Sepolia.
Latest build: [extension-builds-3719](https://github.com/tahowallet/extension/suites/19268527822/artifacts/1131173020) (as of Fri, 22 Dec 2023 13:25:40 GMT).
=> Switch e2e tests run on Goerli to Sepolia

background/services/chain/taho-provider.ts
Due to eth_getLogs usage from Subscape XP drop monitoring, the Alchemy endpoint for Taho had to be blocked completely. After a release that removed the log monitoring, we were still seeing very high usage of eth_getLogs, indicating small numbers of older installs were still causing issues.
Here, we drop built-in Alchemy support for Taho. Instead, we use existing public RPCs to handle all requests. Because Alchemy was blanket blocking all RPC requests from Taho (due to the aforementioned eth_getLogs issue), transaction submission was completely blocked (because the serial fallback provider prefers Alchemy providers to all others when available). This new setup should allow for public RPCs to handle transaction submission (since there will no longer be an Alchemy provider) and thus unblock …
=> Drop Arbirum Sepolia Alchemy support

background/services/abilities/index.ts, background/services/abilities/tests/index.integration.test.ts, ui/components/Overview/AbilitiesHeader.tsx, ui/components/TabBar/TabBar.tsx
Due to the way that abilities are currently implemented, load on the Daylight API side is very high. We don't have the cycles right now to implement the underlying changes that would improve API load, so for now we disable abilities fetching, as well as access to abilities in the UI.
The code that is commented out is targeted to only remove the parts that link to the abilities UI and the parts that call out to the Daylight API; the rest remains in place so that turning things back on once the fetching strategy can be improved is straightforward.
Latest build: [extension-builds-3734](https://github.com/tahowallet/extension/suites/20839694050/artifacts/1252426921) (as of Fri, 16 Feb 2024 21:10:27 GMT).
=> Disable abilities extension-wide

background/networks.ts, background/services/chain/index.ts, background/services/chain/tests/index.unit.test.ts, background/services/enrichment/types.ts, background/services/internal-ethereum-provider/index.ts, background/tests/factories.ts, ui/components/DAppConnection/DAppConnectionInfoBar.tsx, ui/components/Shared/SharedAddress.tsx, ui/components/Shared/SharedCurrentAccountInformation.tsx, ui/components/Shared/SharedIcon.tsx, ui/components/Shared/__tests__/SharedCurrentAccountInformation.test.tsx, ui/components/SignData/EIP191Info.tsx, ui/components/Signing/SignatureDetails/TransactionSignatureDetails/TransactionSignatureSummary/ContractInteractionSummary.tsx, ui/components/Signing/SignatureDetails/TransactionSignatureDetails/TransactionSignatureSummary/TransferSummary.tsx, ui/components/Signing/SignatureDetails/TransactionSignatureDetails/index.tsx, ui/components/Signing/Signer/SignerBaseFrame.tsx, ui/components/Signing/Signer/TransactionButton.tsx, ui/components/Signing/SigningNetworkAccountInfoTopBar.tsx, ui/components/Signing/index.tsx, ui/components/TopMenu/TopMenuProfileButton.tsx, ui/pages/DAppConnect/DAppConnectPage.tsx, ui/pages/NewCustomNetworkRequest.tsx, ui/pages/Onboarding/Tabbed/AddWalletOptions.tsx, ui/pages/Onboarding/Tabbed/ImportSeed.tsx, ui/pages/Onboarding/Tabbed/Intro.tsx, ui/pages/Onboarding/Tabbed/OnboardingAdditionalWallet.tsx, ui/pages/Onboarding/Tabbed/SetPassword.tsx
Hey!
I'm one of the developers on the [Wallet Test Framework](https://wtf.allwallet.dev/about/) project. As part of our grant from the Ethereum Foundation, we've built some integrations with wallets&mdash;Taho included.
This pull request contains the changes we needed to make to automate your wallet: adding a few `id` attributes, and introducing an attribute to differentiate between signing and sending a transaction. Neither myself nor @gaudren are experienced TypeScript developers, so please forgive any obvious mistakes here.
If you're curious what Taho+WTF looks like:
https://github.com/tahowallet/extension/assets/57262657/303d1df2-6458-440d-8d9e-3abbc302f720
And the glue code that makes this work: https://github.com/wallet-test-framework/glue-taho
Assuming you folks are on board, we'd …
=> Support for Wallet Test Framework

background/lib/tests/utils.unit.test.ts, background/services/internal-signer/encryption.ts, provider-bridge/README.md
Because these touch some core files, we rewrite them from scratch.
=> Fix a couple of typos from contribution

.github/workflows/build.yml
Node12 has been out of support since April 2022. As a result GH has started the deprecation process of Node12 for GitHub Actions by migrating all actions to run on Node16 ([read
more](https://github.blog/changelog/2023-07-17-github-actions-removal-of-node12-from-the-actions-runner/)). The `softprops/action-gh-release` action's version which we used in the `build.yml` workflow was running on Node12. But a newer version (`v0.1.15`) of the action is run on Node16. We're swithing to using that newer version. This should make `The following actions uses node12 which is deprecated and will be forced to run on node16: softprops/action-gh-release@1e07f4...` annotation disappear from the details of the workflow runs.
The upgrade may also remove the `The "set-output" command is deprecated and will …
=> Move action using node12 to a newer version

background/constants/networks.ts, background/services/ledger/index.ts, background/services/name/resolvers/uns.ts, ui/components/Signing/Signer/SignerLedger/SignerLedgerSigning/index.tsx, ui/pages/Send.tsx
These are unrelated changes: UNS is disabled due to compromise during the late-last-week SquareSpace domain theft issues, while the Ledger signing issue is long-standing. The Ledger signing issue is partial—it doesn't work for custom networks, and it is handled in a way that's different for EIP191 messages than for other messages; further refinement is needed to fix it the rest of the way.
Latest build: [extension-builds-3746](https://github.com/tahowallet/extension/suites/25994003749/artifacts/1700133481) (as of Mon, 15 Jul 2024 02:27:54 GMT).
=> Tweaks and creaks: Disable UNS, fix Ledger signing on built-in non-ETH/MATIC networks

background/services/ledger/index.ts
The latest version of Ledger Nano X firmware changes the product ID to `0x4000`, breaking connections with newer devices.
I tested this patch locally with a newly updated Ledger Nano X, though I haven't been able to test it with an older (pre-upgrade) Nano X.
The Ledger team suggests we move to the [Device Management Kit](https://developers.ledger.com/docs/device-interaction/beginner/discover_and_connect). I haven't had time to dig in further on whether the DMK connection flow would work with WebUSB, and [opened an issue](https://github.com/tahowallet/extension/issues/3754) for later.
Latest build: [extension-builds-3755](https://github.com/tahowallet/extension/suites/32049732661/artifacts/2319383990) (as of Fri, 13 Dec 2024 20:47:52 GMT).
=> Include the latest Ledger Nano X product ID

.github/workflows/build.yml, .github/workflows/pledge-signer-sync/package.json, .nvmrc, package.json, yarn.lock
The new version should support Ubuntu 24.04 in Github Actions
https://github.com/microsoft/playwright/issues/30368
Latest build: [extension-builds-3756](https://github.com/tahowallet/extension/suites/32386348469/artifacts/2356688184) (as of Mon, 23 Dec 2024 17:03:36 GMT).
=> Bump playwright to 1.48.0

ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
Checks there are accounts to render before attempting to render the account's category ('Imported', 'Hardware...', etc)
Closes #3762
=> Fixes empty screen when opening the account switching panel.

background/services/provider-bridge/index.ts
This was making one of the e2e test fail as an empty array was passed as dApp connection info.
Latest build: [extension-builds-3768](https://github.com/tahowallet/extension/suites/33209975358/artifacts/2449542737) (as of Fri, 17 Jan 2025 22:18:50 GMT).
=> Correct dApp info passed on eth_requestAccounts

.github/workflows/build.yml, background/services/indexing/index.ts, e2e-tests/regular/dapp-connect.spec.ts, e2e-tests/regular/nfts.spec.ts, e2e-tests/regular/signing.spec.ts, e2e-tests/utils.ts, e2e-tests/utils/connect-popup.ts, e2e-tests/utils/onboarding.ts, e2e-tests/utils/walletPageHelper.ts, src/background.ts, ui/components/NFTs/NFTListPortfolio.tsx
This also changes the workflow config so there's an output even if the job is cancelled, helping with debugging when playwright hangs indefinitely.
Latest build: [extension-builds-3775](https://github.com/tahowallet/extension/suites/34404092171/artifacts/2593695375) (as of Fri, 14 Feb 2025 16:45:49 GMT).
=> Update e2e tests

background/redux-slices/activities.ts, background/services/redux/index.ts
This adds a check into the account activity initialization process so we re-use already-enriched activity data if it corresponds to a finalized transaction.
Improves worker startup and prevents requests bursts by optimizing activity initialization for tracked accounts.
Latest build: [extension-builds-3783](https://github.com/tahowallet/extension/suites/34503181381/artifacts/2605178562) (as of Mon, 17 Feb 2025 19:35:53 GMT).
=> Reuse existing activity state data

background/services/redux/index.ts
This prevents dispatching a "Analytics Toggled" event during initialization of analytics preferences by checking if the setting has been changed before dispatching updates/events.
Latest build: [extension-builds-3784](https://github.com/tahowallet/extension/suites/34817574924/artifacts/2643584644) (as of Mon, 24 Feb 2025 19:20:05 GMT).
=> Prevented unnecessary analytics events on initialization

background/lib/priceOracle.ts
Helps reduce occurrences of `out of gas` errors when calling public RPCs. Won't help with calls made through multicall when they receive a valid RPC response with empty results. But, will reduce frequency of these scenarios.
Latest build: [extension-builds-3786](https://github.com/tahowallet/extension/suites/34820924724/artifacts/2644023557) (as of Mon, 24 Feb 2025 20:33:38 GMT).
=> Lower batch size for price discovery calls

background/redux-slices/selectors/accountsSelectors.ts, background/services/redux/index.ts
Fixes a case where a balance of zero would prevent loading from finishing early and reduces the `initialLoad` timer to 90 seconds.
Latest build: [extension-builds-3788](https://github.com/tahowallet/extension/suites/34873113422/artifacts/2650541060) (as of Tue, 25 Feb 2025 18:02:31 GMT).
=> Fix excessive loading time on new accounts

background/services/indexing/index.ts, background/services/indexing/tests/index.integration.test.ts
Prevents missed updates if a price fetch is requested shortly after after detecting a new token balance.
Latest build: [extension-builds-3787](https://github.com/tahowallet/extension/suites/34970189586/artifacts/2662917777) (as of Thu, 27 Feb 2025 12:20:43 GMT).
=> Increase frequency of price fetching

background/networks.ts, background/redux-slices/selectors/uiSelectors.ts, background/redux-slices/ui.ts, background/services/campaign/db.ts, background/services/campaign/index.ts, background/services/campaign/matsnet-nft.ts, background/services/campaign/types.ts, background/services/notifications/index.ts, background/services/preferences/db.ts, background/services/preferences/index.ts, background/services/redux/index.ts, ui/_locales/en/messages.json, ui/components/Shared/SharedBanner.tsx, ui/components/TopMenu/TopMenuProtocolListItem.tsx, ui/components/Wallet/Banner/WalletCampaignBanner.tsx, ui/pages/Wallet.tsx
This moves campaign related logic out of the main service into a dedicated service. It also causes dismissing campaign banners to clear and stop triggering notifications about the same topic. 
Campaign state is kept within the service db and updates are pushed to state in redux.
Latest build: [extension-builds-3794](https://github.com/tahowallet/extension/suites/35331061341/artifacts/2708368343) (as of Fri, 07 Mar 2025 03:08:56 GMT).
=> Move active campaign concerns to campaign service

background/lib/nfts.ts, background/nfts.ts, background/redux-slices/utils/nfts-utils.ts, background/services/campaign/matsnet-nft.ts, background/services/nfts/index.ts
Aggregates campaign NFT contract data to the NFT list
Latest build: [extension-builds-3804](https://github.com/tahowallet/extension/suites/35623668512/artifacts/2744585947) (as of Thu, 13 Mar 2025 11:03:31 GMT).
=> Display Campaign NFTs on Wallet UI

background/lib/posthog.ts, background/services/campaign/index.ts, ui/components/Wallet/Banner/WalletCampaignBanner.tsx
Adds `src` query strings to identify banners clicked from Mezo, and sets analytics events to dispatch on banner click
Latest build: [extension-builds-3801](https://github.com/tahowallet/extension/suites/35630590546/artifacts/2745445456) (as of Thu, 13 Mar 2025 13:21:56 GMT).
=> Set analytics data on mezo campaign items

background/services/name/resolvers/mezo.ts
For resolving `0xd8da6bf26964af9d7eed9e03e53415d37aa96045` into `vitalik.mezo`
:construction: Endpoint hasn't reached production yet
Latest build: [extension-builds-3806](https://github.com/tahowallet/extension/suites/35710604406/artifacts/2755893972) (as of Fri, 14 Mar 2025 22:02:54 GMT).
=> Add missing endpoint for reverse `.mezo` resolution

background/services/redux/index.ts, ui/components/Wallet/Banner/WalletCampaignBanner.tsx
Updates "Login to claim sats" banner text to include campaign referral code and removes a hardcoded origin.
Latest build: [extension-builds-3810](https://github.com/tahowallet/extension/suites/35950305371/artifacts/2785999191) (as of Thu, 20 Mar 2025 05:50:01 GMT).
=> Update copy on campaign banner

src/window-provider.ts
Note that EIP6963 should remove the need to do this, but instead sites like Etherscan still only present MetaMask as an option despite using a EIP6963-aware library under the covers. Malice, incompetence, or dirty dealings? That is left as an exercise for the reader.
Latest build: [extension-builds-3811](https://github.com/tahowallet/extension/suites/36036334941/artifacts/2797168574) (as of Fri, 21 Mar 2025 16:15:20 GMT).
=> Allow for replacing EIP6963 MetaMask as well
