tahowallet/extension

background/index.ts
manifest/manifest.development.json
manifest/manifest.json
provider-bridge/index.ts
src/provider-bridge.ts
src/window-provider.ts

The purpose of this PR is to address the remaining issues from #393 in a clean manner.
I will rebase all the upcoming PRs to this, so we have a clean separation of concerns.

Follow up PR for #393

---

background/main.ts
background/redux-slices/transaction-construction.ts
background/services/chain/index.ts
ui/components/NetworkFees/Chooser.tsx
ui/pages/Send.tsx
ui/pages/SignTransaction.tsx

Move out chosing fees code to separate component to make the
send component more readable. This PR adds a new value in redux slice
to track last time gasEstimates were updated.

Create animation to show fees timout

---

manifest/manifest.json
package.json

**Note:** This version has seen significant internal refactorings; the extension will
need to be reinstalled, not just updated! Once the extension sees its first public
release (very s∞n!), this will stop being the case.
* 🤗 Officially GPL 
* 🕵️‍♂️  ENS name and avatar resolution for added addresses
* ⛵️Fresh onboarding designs
* 👀 Cleaner overview
* ☑️ Fully featured account selector
* 🌐 Swap tab with correct asset data
* 🚇 Infrastructure for forthcoming features
* 📊 Secret fee selector
* 🏎 Faster performance  
* 🧹 Many small fixes.
**Full Changelog**: https://github.com/tallycash/extension/compare/v0.0.7...v0.8.0

v0.8.0: Let the games begin

---

manifest/manifest.json
package.json

* ⚡️ Infrastructure for dApp connection approval UI
* 🔁 Fix having to go through adding a read-only wallet twice by @henryboldi in https://github.com/tallycash/extension/pull/535
**Full Changelog**: https://github.com/tallycash/extension/compare/v0.8.1...v0.8.2

v0.8.2: Fix view-only onboarding flow

---

background/main.ts
background/redux-slices/selectors/uiSelectors.ts
background/redux-slices/transaction-construction.ts
background/services/chain/index.ts
background/services/chain/utils.ts
background/services/keyring/index.ts
ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/pages/Popup.tsx

Commits describe it all here.
See #366 .

More Bits: More small improvements on the way to dApp signing

---

background/lib/alchemy.ts
background/redux-slices/selectors/uiSelectors.ts
background/redux-slices/ui.ts
background/services/chain/index.ts
background/services/chain/utils.ts
ui/components/Wallet/WalletActivityList.tsx
ui/components/Wallet/WalletActivityListItem.tsx

On the way to dApp signing as usual.
Commits have the deets.

More Transactions: improvements to transactions in UI

---

.github/workflows/build.yml

Use correct data provider keys in CI builds.
Let's use this opportunity to thank the pagan cryptography gods for [libsodium](https://github.com/jedisct1/libsodium/blob/master/AUTHORS), without which [GitHub secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets) would not be possible.

🌊🧂 Sea Salt: Pull provider keys from GitHub secrets

---

ui/components/NetworkFees/NetworkFeesChooser.tsx
ui/components/Overview/OverviewAssetsTable.tsx
ui/components/Shared/SharedAssetInput.tsx
ui/components/Shared/SharedPanelSwitcher.tsx
ui/pages/Send.tsx
ui/pages/SignTransaction.tsx

This makes adding a fee chooser with self-contained state a matter of invoking one component, instead of wiring up several bits of state between two components.
Also some React error fixes.

Fee Amalgamation: Move fee selection button into fee chooser component

---

background/redux-slices/ui.ts
ui/components/Core/CorePage.tsx
ui/components/Snackbar/Snackbar.tsx
ui/pages/Receive.tsx

Can be set from anywhere using `dispatch(setSnackbarMessage("Copied!"))`
Closes #630

🍫 Add a snackbar for all your yummy brief feedback needs

---

ui/pages/SingleAsset.tsx

Closes https://github.com/tallycash/extension/issues/588
Heavily heavily based on Antonio's code here https://github.com/tallycash/extension/issues/588#issuecomment-991819719

✋ Fix single asset page showing other tokens

---

.github/ISSUE_TEMPLATE/BUG.yml
.github/ISSUE_TEMPLATE/FEATURE.yml
.github/ISSUE_TEMPLATE/config.yml

Include issue titles in the templates so they'll show up, and update Discord links so they don't 404.
Closes #683

Issues with issues

---

background/networks.ts
background/services/chain/index.ts
background/services/chain/utils.ts
ui/components/Wallet/WalletActivityListItem.tsx

Does what it says on the tin! Displays when transactions fail in the activity list.
Closes #678, closes #587.

Transactional Failure: Display failed transactions in the activity list

---

manifest/manifest.json
package.json

🐾🦴🐶🐕‍🦺🐩🦮🐕🦮🐩🐕‍🦺🐶🦴🐾
This is a functioning wallet.
That is all.
🐾🦴🐶🐕‍🦺🐩🦮🐕🦮🐩🐕‍🦺🐶🦴🐾

v0.9.0: It's alive

---

background/lib/utils/index.ts
background/redux-slices/utils/activity-utils.ts
ui/pages/SingleAsset.tsx

Display maxFee and price in Gwei instead of ETH, remove transformation of Gas used to different unit.
Remove "Activity" from single asset page.
Closes #717

Display fees in activities in Gwei 🐼

---

manifest/manifest.json
package.json

Includes a variety of UI fixes, support for rejecting dApp signatures,
and balance updates when transactions are submitted to catch any changes
from those transactions.

v0.9.1: Polish + gold

---

ui/components/SignTransaction/SignTransactionSignBlock.tsx
ui/pages/SignTransaction.tsx

Show sent token amount up to 4th decimal place and display main currency value in USD.
Closes #689

Update dapp sign page value display

---

background/services/provider-bridge/index.ts

As a Degen 
I want to see dApp become disconnected when I revoke the permission in the wallet 
so that I know the dApps can not access my account anymore
Fixes #608, closes #489

😷 Dapp Distancing: Notify dApps when a user disconnects

---

manifest/manifest.json

... I missed bumping the manifest for the last release :sweat:

Manifest version 0.9.2

---

provider-bridge/index.ts

https://jisho.org/search/%E5%88%87%E8%85%B9

typo in provider-bridge

---

background/redux-slices/keyrings.ts
ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/components/Shared/SharedButton.tsx

A lil' hook up to @mhluongo's heavy lifting w/ `deriveAddress`. See #761

🤝 Add account frontend hook up

---

ui/components/AccountsNotificationPanel/AccountsNotificationPanel.tsx
ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/components/Shared/SharedSlideUpMenu.tsx
ui/components/Snackbar/Snackbar.tsx
ui/components/TopMenu/TopMenu.tsx
ui/public/index.css

> “Whole Lotta Love” might have gotten the band sued by Willie Dixon, but there was no sonic precedent for it in rock music—it’s a sound that would have been unimaginable without the rise of drug culture.
This PR includes fixes for,

🤘 Scroll Lotta Love

---

background/accounts.ts
background/main.ts
background/redux-slices/accounts.ts
ui/pages/Onboarding/OnboardingAddWallet.tsx
ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx

feat: import read-only wallet by ens

---

ui/pages/Onboarding/OnboardingImportMetamask.tsx

🗣 Clarify expecting a 12-word recovery phrase

---

ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/components/NetworkFees/NetworkFeesChooser.tsx

Read-only back in biz. My bad!

🙈 Fix styling issue hiding addresses in account switcher

---

ui/pages/Onboarding/OnboardingAddWallet.tsx
ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx

"ENS domain" -> "ENS name"

---

ui/components/TabBar/TabBarIcon.tsx

I've never seen this flicker in production yet, but it pops up sometimes in development, so we might as well patch it!

📸 Fix tab bar icon sometimes flashing background color

---

ui/components/Keyring/KeyringSetPassword.tsx
ui/components/Shared/SharedAssetInput.tsx

🐛🥺 Fix lil visual bugs

---

package.json
ui/pages/Menu.tsx
webpack.config.ts
yarn.lock

Fixes #806.
NB: version is taken from `git describe`, not from manifest.

Show version, git commit and date in settings page

---

background/package.json
background/services/keyring/index.ts
background/types.ts

Adds a keyring function that will allow signing typed data, the request will come from the ui through main.

Add signing typed data to keyrings

---

ui/components/Shared/SharedAssetInput.tsx
ui/components/Swap/SwapQuote.tsx
ui/pages/Swap.tsx

These basically closes #829 aside from parts which will require a more significant refactor, like "We need to refactor the swap redux slice to use the quote API"

🔄 Swap UI tasks

---

background/main.ts
background/networks.ts
background/redux-slices/0x-swap.ts
background/redux-slices/keyrings.ts
background/services/chain/index.ts
background/services/keyring/index.ts
background/tests/keyring-integration.test.ts

Nonce management only in this branch now. The lifecycle still needs some
tweaks to invalidate nonces that don't get a signature.
Queuing transactions is moving to a separate PR.

Nonces and queues: More direct nonce management

---

background/main.ts
background/networks.ts
background/redux-slices/0x-swap.ts
background/redux-slices/keyrings.ts
background/services/chain/index.ts
background/services/keyring/index.ts
background/tests/keyring-integration.test.ts
ui/components/Swap/SwapQuote.tsx
ui/pages/Swap.tsx

I got a little too quick on the draw with the #803 rebase and
merge and missed commits from a couple of PRs that were merged
to 803 previously. This PR reintroduces those commits.
Going to approve + merge as-is unless there's an issue in CI
(I've confirmed the build passes locally).

Re-merge-merge: fix a messed swaps rebase

---

background/redux-slices/accounts.ts
background/redux-slices/selectors/accountsSelectors.ts
background/redux-slices/selectors/index.ts
background/redux-slices/selectors/keyringsSelectors.ts
background/redux-slices/selectors/signingSelectors.ts
background/redux-slices/signing.ts
ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/components/Wallet/WalletAccountBalanceControl.tsx
ui/pages/SignTransaction.tsx
ui/pages/SingleAsset.tsx

Refactoring-only PR.
Prepares Redux code for signing with methods other than keyrings.

Prepare Redux to support Ledger accounts

---

ui/pages/Popup.tsx
ui/pages/SignTransaction.tsx

Reverts tallycash/extension#818
It's more dangerous than I thought.

Revert "🗃 Preserve location when reopening extension"

---

ui/components/SignTransaction/SignTransactionContainer.tsx

I believe this is where that Ledger info popped up on the swap sign page
@Shadowfiend

🆘 Revert ledger sign transaction container buttons

---

background/redux-slices/ledger.ts

Show error message if current Ledger device is disconnected

---

background/redux-slices/0x-swap.ts

This change means the community multisig will go back to receiving fees for every swap.

Death and Taxes: Charge fees regardless of the gated 0x API

---

README.md
webpack.config.ts

with a small config change its possible to load Tally on the Edge browser (windows/mac)

✨ support build edge extension

---

ui/components/Shared/SharedAssetInput.tsx

Make divider smaller to match design.
Fix height of the list as "coming soon" notice bar is added.

Fix styles of assets list

---

background/main.ts
background/redux-slices/signing.ts
background/services/internal-ethereum-provider/index.ts
background/services/keyring/index.ts
background/services/ledger/index.ts
background/services/provider-bridge/authorization.ts
background/services/provider-bridge/index.ts
background/services/provider-bridge/show-popup.ts
ui/hooks.ts
ui/pages/PersonalSign.tsx
ui/pages/PersonalSignDetailPanel.tsx
ui/pages/SignData.tsx
ui/pages/SignTransaction.tsx

This PR makes signing messages work with Ledger, by reusing shared code.

Allow signing messages (incl. sign-in-with-ethereum) with Ledger and other related improvements

---

CONTRIBUTING.md
README.md
babel.config.js
background/README.md
background/package.json
dev-utils/local-chain/package.json
package.json
provider-bridge-shared/package.json
provider-bridge/package.json
rfb/rfb-1-keyring-design.adoc
rfb/rfb.adoc
ui/README.md
ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/package.json
ui/public/popup.html
ui/public/tab.html
window-provider/package.json

Also a few Tally -> Tally Ho renames.

Tally RFBs: Rename RFCs

---

ui/components/Shared/SharedAssetInput.tsx

Fix height of list as ETH bar was removed

Fix height of token list

---

background/lib/alchemy.ts
background/lib/utils/index.ts
background/services/provider-bridge/db.ts
background/services/provider-bridge/index.ts
env.d.ts

These are some easy-to-fix warnings that make the file diffs on Github PR Reviews longer than they need to be.

Cleanup ESLint warnings

---

.github/ISSUE_TEMPLATE/BUG.yml
manifest/manifest.json
package.json

* Fix sign transaction navigating away the first time it is opened by @cairomassimo in https://github.com/tallycash/extension/pull/1163
* 💔 It's not you: remove git dependency from the build process by @greg-nagy in https://github.com/tallycash/extension/pull/1173
* Add button View asset on Etherscan by @jagodarybacka in https://github.com/tallycash/extension/pull/1164
* Fix broken USD network fees labels by @jagodarybacka in https://github.com/tallycash/extension/pull/1189
* Release 0.12.2 QA/Bump by @henryboldi in https://github.com/tallycash/extension/pull/1172
* Remove "ETH coming soon" notice by @0xDaedalus in https://github.com/tallycash/extension/pull/1196
* Disable Editing of Slippage Tolerance in Swaps Network Settings. by @0xDaedalus in …

Smoke test - Release v0.12.3

---

ui/pages/Popup.tsx

`initialEntries` needs to be a reversed version of route history entities.
Without avoiding the initial load, entries will keep reversing. Given that
restoring our route history is a "POP" `history.action`, by specifying "PUSH"
we know that the most recent navigation change is by the user or explicitly
added.
That said, we can still certainly "POP" via history.goBack(). This case
is not yet accounted for. Because alternatively, comparing history lengths runs
into edge cases. For whatever reason, the first navigation change after
restoring the location always resets the navigation entities length to two. The
resetting entities length is something I'm looking into.
On the bright side, `history.goBack()` is not used on any page we persist.

❤️‍🩹 Remedy route persistence complications

---

.github/ISSUE_TEMPLATE/BUG.yml
manifest/manifest.json
package.json

It's been a couple of weeks since a full release, and they've been packed! Here are some of the big goodies that have landed:
- ERC20 transfers ↔️: ERC20 transfers are now available for all tokens!
- Fee dollar amounts 💰: as we continue to work on improved gas controls, we've touched up the current ones a bit to show you the max dollar amount fees can consume.
- CPU usage 📉: we've been hunting CPU usage bugs and have crushed several. More to come!
- Name that contract 📝: thanks to @jack-the-pug, transaction sign pages now show the ENS name of the contract you are interacting with, when available.
- Clipboard invasion 📋: Most addresses in the UI can now be clicked to be copied. The seed phrase during new wallet creation is also now copyable to the clipboard.
- Several adjustments to …

v0.13.0 release: ERC20 transfers of tokens on the wall

---

background/services/ledger/index.ts

This change was made by Pablo Castellano here https://github.com/tallycash/extension/pull/1202
However, the commit wasn't signed. So that the PR doesn't
sit indefinitely, I'm committing it signed by me and
adding Pablo Castellano as a co-author.

🔁 Fix typo in variable name (idDerivationPath) - By Pablo Castellano

---

ui/public/index.css

Co-authored-by: VladT <80846886+VladUXUI@users.noreply.github.com>

💚 Darken shade for `--green-120`

---

ui/components/Shared/SharedAssetInput.tsx

add relative position to parent

---

ui/components/Shared/SharedBanner.tsx

Minor improvements to make Shared Banner easier to use.
- add possibility to apply custom styles
- fix alignment of close button and text when there is only one line of text

Improve styles of SharedBanner

---

ui/components/BonusProgram/BonusProgramModal.tsx
ui/components/Shared/SharedTooltip.tsx
ui/components/TopMenu/TopMenu.tsx
ui/components/Wallet/AssetListItem/CommonAssetListItem.tsx
ui/components/Wallet/AssetListItem/DoggoAssetListItem.tsx
ui/components/Wallet/AssetListItem/styles.ts
ui/components/Wallet/WalletAssetListItem.tsx

Resolves https://github.com/tallycash/extension/issues/1476
The DOGGO asset should be treated as a special kind of asset. It has different icons - rewards program and link to Earn tab. It also has a "locked" badge with a tooltip that explains what it means that DOGGO is locked.

🐶  Treat DOGGO token as special kind of asset

---

ui/components/NetworkFees/FeeSettingsText.tsx

❤️‍🩹 Fix estimated gas fee stuck on TBD

---

ui/_locales/en/messages.json
ui/components/Shared/SharedAssetInput.tsx
ui/components/Swap/SwapTransactionSettingsChooser.tsx
ui/pages/Swap.tsx

related to https://github.com/tallycash/extension/issues/438
distil swap page strings for translation

(localization) distill swap page strings

---

ui/pages/Swap.tsx

📜 Remove padding to remove scroll from swap tab

---

ui/_locales/en/messages.json

Closes https://github.com/tallycash/extension/issues/1596

🤏 Update copy on swaps "DAO Fee"

---

background/lib/utils/index.ts
ui/components/Claim/ClaimReferral.tsx
ui/components/Shared/SharedAddressInput.tsx
ui/hooks/validation-hooks.ts
ui/pages/Onboarding/OnboardingViewOnlyWallet.tsx

Resolves https://github.com/tallycash/extension/issues/1356
If a user is typing UNS or ENS name we should allow them to finish typing before showing an error message - let's debounce by 500ms name validation to create better UX.
https://user-images.githubusercontent.com/20949277/173837618-045ed616-ee24-4293-be90-cce97fcd7101.mov

🖍 Debounce ENS/UNS name lookup

---

ui/pages/Swap.tsx

Fix "switch assets" button border.
Before:
After:

🔄 Fix styles of switch assets button

---

ui/components/Shared/SharedAssetInput.tsx

Closes https://github.com/tallycash/extension/issues/1087
This one doesn't affect accessibility, more info [here](https://github.com/tallycash/extension/pull/1435/files#r872526312)

Fix hover area for Swap buttons

---

background/services/chain/db.ts
background/services/indexing/db.ts

Dexie has its own migration solution, it's better to use that
instead of our own. (We weren't using these anyway.)
These migrations caused serious slow down (~400ms) when the
services were starting, and because of the service dependencies
this slow down propagated to the overall background startup time.
The effect become significantly worse when the user opened the
UI quickly after installation/extension reload. In those cases
the slowdown could go up to ~1500-2000ms. (Not sure why.
My best guess is that the browser was copying the db
to set up the UI thread which interefered with the migration.)
For the problem to present itself I was using a dev build,
slow 3g network throttling and 6x CPU throttling in chrome.
See https://github.com/tallycash/extension/pull/1672 debug notes + fallback …

🏴‍☠️Green screen of death round2:  Remove the unused custom db migrations

---

background/redux-slices/selectors/uiSelectors.ts
ui/components/Wallet/WalletActivityList.tsx

current account address was another layer in the data structure
which wasn't represented in the selector

fix selectShowingActivityDetail

---

background/services/provider-bridge/index.ts
window-provider/index.ts

Uniswap has migrated to web3-react v8 and during this process, they broke our integration. 
For the exact problems see the commit messages. 
Closes #1647

🤗 Fix uniswap connection

---

background/assets.ts
background/constants/currencies.ts
background/lib/prices.ts
background/redux-slices/0x-swap.ts

Closes https://github.com/tallycash/extension/issues/1729
Closes https://github.com/tallycash/extension/issues/1708
https://user-images.githubusercontent.com/94649004/177590113-755e771d-559d-4cbe-9598-5d1a9be33bba.mov
This PR fixes an issue where the swap ratio would not calculate when swapping to / from MATIC on Polygon.
It also sneaks in a fix to an issue where MATIC price was not getting fetched as part of the BASE_ASSET price fetching - which was discovered during the course of debugging the swap issue.

Fix swapping to and from MATIC on polygon.

---

background/lib/alchemy.ts
background/services/chain/index.ts
background/services/doggo/index.ts

Created an alarm to check for transactions every minute. 
There is a ~5 minutes delay in transactions that we are picking up now, which is not ideal.
Also fixed the asset flow to add the assets from the history to the `assetsToTrack` list.
- revert #1755
- import a new wallet with a history 
- `tally/indexing > assetsToTrack` should be populated with all the assets
- note: the UI will pick up the changes in the next minute or so 
🤔 Why is the UI not populated with all the assets on the first run?
Ref #1158

Fix asset transfers

---

window-provider/index.ts

- Connect to https://wallet.polygon.technology/bridge/
- Switch back and forth between polygon and ethereum using the in-app switcher
- The dapp should detect the changes and properly switch the text to Polygon / Ethereum - respectively.
- Switching the network inside of the wallet should not switch the network in the dapp.

Emit a chainChanged event after successfully switching chains

---

background/redux-slices/selectors/accountsSelectors.ts
background/redux-slices/selectors/transactionConstructionSelectors.ts
ui/components/NetworkFees/FeeSettingsText.tsx
ui/components/NetworkFees/FeeSettingsTextDeprecated.tsx
ui/components/NetworkFees/NetworkSettingsSelect.tsx
ui/components/NetworkFees/NetworkSettingsSelectDeprecated.tsx

Matic
Ethereum
Closes #1769
⚠️ Planning to write a proper description, but feel free to review it now

📈 Fix currency value for gas fee estimation

---

background/redux-slices/assets.ts
ui/_locales/en/messages.json
ui/components/Swap/SwapQuote.tsx
ui/pages/Send.tsx
ui/pages/Swap.tsx

⚠️ Would like to add an explanation behind this choice to the PR description, but feel free to review now if we need it quickly

👻 Remove gas settings before sign step

---

background/services/preferences/db.ts
background/services/preferences/defaults.ts
ui/components/Shared/SharedAssetInput.tsx

Closes https://github.com/tallycash/extension/issues/1730
- Reinstall Tally
- There should be more than 10 polygon swap pairs
- the ipfs uri should match the [`build token lists for main`](https://github.com/tallycash/token-list/runs/7240322358?check_suite_focus=true) output in the token-list repo.

Update Tally Tokenlist

---

ui/pages/Overview.tsx

🤏 Handle zero overview total balance

---

background/services/provider-bridge/index.ts

Connect wallet to uniswap 
You should be able to connect without needing to refresh

Fix Double Dapp Connect Bug

---

.prettierignore

This will make merging translations from `weblate` significantly smoother and should allow us to merge https://github.com/tallycash/extension/pull/1756 after merging this change into the branch.

Add translation JSON files to prettier ignore.

---

ui/_locales/en/messages.json
ui/pages/Receive.tsx

💬 Remove static network specific subtitle from receive

---

background/redux-slices/accounts.ts

Closes #1664
Solution explained here https://github.com/tallycash/extension/issues/1664#issuecomment-1183548873

🔄 When removing an account, update the overview tab

---

background/package.json
background/services/name/resolvers/address-book.ts
background/services/preferences/index.ts
background/services/preferences/tests/index.integration.test.ts
background/services/preferences/tests/index.test.ts
background/services/preferences/tests/index.unit.test.ts
package.json
yarn.lock

This PR lays the groundwork for testing codepaths that rely on indexedDB - and adds some basic preferenceService tests to serve as an example of how we may want to test a service going forward.

Preference Service Tests

---

background/redux-slices/0x-swap.ts

The 0x api can return other statuses than 200 and
then ethers.js throws an error, which we weren't handling before

💬 Polygon swap issue 1/n: error handling for swap price fetch

---

background/redux-slices/0x-swap.ts
ui/pages/Swap.tsx

https://user-images.githubusercontent.com/94649004/179776496-7ee7a3e0-189a-4017-b0eb-0221e09371a6.mov

Alert on 0x INSUFFICIENT_LIQUIDITY Error, Prevent swap button flickering on swap screen.

---

background/constants/networks.ts
background/redux-slices/nfts.ts
background/redux-slices/selectors/accountsSelectors.ts
ui/components/NFTs/NFTsEmpty.tsx
ui/components/NFTs/NFTsList.tsx
ui/components/NFTs/NFTsListItem.tsx
ui/components/NFTs/NFTsOverview.tsx
ui/components/NFTs/NFTsWallet.tsx
ui/components/Overview/OverviewAssetsTable.tsx
ui/pages/Overview.tsx

Resolves #1845
* add NFT overview tab to Overview page
* add empty state UI to NFT list
* add basic NFT preview with slideup menu

Create NFT Overview and other improvements

---

background/redux-slices/nfts.ts

Addressed comments from https://github.com/tallycash/extension/pull/1850
- use `URL()` to build NFTs list request
- ass basic handling of Alchemy request errors
- add a spam filter to the request
@greg-nagy I've addressed some of your comments, in a separate PR to make it easier to review

NFTs fetching improvements

---

ui/components/NFTs/NFTsEmpty.tsx
ui/components/NFTs/NFTsWallet.tsx

Various minor fixes for bugs that were found during QA.
- Change the empty NFT list component's text to not mention Looks Rare 
- fix selecting NFTs for read-only accounts that were imported using raw address (not ENS or UNS names)

✏️ NFT's post QA improvements

---

ui/components/NFTs/NFTsListItem.tsx
ui/components/NFTs/NFTsSlideUpPreviewContent.tsx

🖍 Default to "No title" if NFT doesn't have title

---

background/redux-slices/nfts.ts

If NFT has an error then maybe better to hide it from the list

💣 Filter out NFTs with errors

---

ui/pages/SignTransaction.tsx

If there are no transaction details yet we should show tx screen loader instead of an empty screen
https://user-images.githubusercontent.com/20949277/183091010-79ed5abc-0dae-410f-b7f4-f0ebca8b5bd1.mov

Fixed regression with tx screen loader

---

background/constants/currencies.ts
background/redux-slices/assets.ts

Resolves https://github.com/tallycash/extension/issues/1888
`isSmartContractFungibleAsset()` is not working correctly with base assets so let's select them by their symbols.

Fix selecting currency and asset from price pair

---

background/services/chain/utils.ts
background/services/ledger/index.ts

Implement Optimism TX Signing on Ledger

---

ui/_locales/en/messages.json
ui/components/TopMenu/TopMenuProtocolList.tsx
ui/components/TopMenu/TopMenuProtocolListItem.tsx

Add Optimism and Arbitrum as "coming soon"

---

background/lib/gas.ts

This should clean up the logs a fair bit

Only warn about inconsistent EIP-1559 gas prices on EIP-1559 gas networks

---

ui/components/Onboarding/OnboardingDerivationPathSelect.tsx

Fix the label that was too long

Fix derivation path label

---

background/networks.ts
background/services/chain/index.ts
ui/components/NetworkFees/FeeSettingsText.tsx

Optimism - Show correct gwei estimates to user in gas fee preview button

---

ui/components/NFTs/NFTsImage.tsx
ui/components/NFTs/NFTsList.tsx
ui/components/NFTs/NFTsOverview.tsx
ui/components/NFTs/NFTsWallet.tsx
ui/components/Overview/AccountItem.tsx
ui/package.json
yarn.lock

Use lazy image loading instead of list virtualisation library to align scrolling behaviour between tabs
Add many accounts with a lot of NFTs and check if NFTs lists are working as before without significant performance problems

Handle NFTs list without react-window

---

background/networks.ts

Add more color to the comment describing the LegacyEVMTranscation type

---

background/services/name/index.ts

All EVM addresses that hit `NameService` should be normalized to prevent cache misses.
Refs #2043, builds on #2054

Social Norms: Only look up names for normalized addresses

---

window-provider/index.ts

Add dydx.exchange to impersonate MM whitelist

---

background/redux-slices/migrations/index.ts
background/redux-slices/migrations/to-16.ts

Closes https://github.com/tallycash/extension/issues/2091
- Load a new wallet on version `0.14.7`
- Approve a token you have not previously approved before
- Upgrade to version to this branch
- Open the Activity Page.

Populate ActivityItem `spender` when able to.

---

background/constants/index.ts
background/lib/alchemy.ts
background/main.ts
background/redux-slices/ui.ts
background/services/chain/db.ts
background/services/chain/index.ts
background/services/chain/serial-fallback-provider.ts
background/services/indexing/index.ts
background/services/internal-ethereum-provider/index.ts
background/services/name/resolvers/uns.ts

Closes https://github.com/tallycash/extension/issues/2040
Closes https://github.com/tallycash/extension/issues/2041
This guy will need some thorough testing - the best way I've found to do it is by opening up dev tools and monitoring an individual websocket connection for messages.

Further reduce calls to alchemy - introduce Active Networks.

---

background/redux-slices/migrations/index.ts

This PR updates the redux state version to 17 for the analytics page.

Update the redux state version to 17

---

background/lib/wrappedAsset.ts

Closes https://github.com/tallycash/extension/issues/2121
Closes https://github.com/tallycash/extension/issues/1871

Correctly parse wrapped asset Withdrawals & Deposits.

---

.github/workflows/build.yml

Almost missed it!
Closes #2158

Include SimpleHash prod API creds in the build

---

.github/ISSUE_TEMPLATE/BUG.yml
manifest/manifest.json
package.json

* Display current network's base asset earlier in assets list by @hyphenized in https://github.com/tallycash/extension/pull/2111
* Translations update from Hosted Weblate by @weblate in https://github.com/tallycash/extension/pull/2114
* Add visual functionality to Analytics settings page by @kkosiorowska in https://github.com/tallycash/extension/pull/2094
* Update the redux state version to 17 by @kkosiorowska in https://github.com/tallycash/extension/pull/2123
* Enable Tally users to use Matcha.xyz by @0xDaedalus in https://github.com/tallycash/extension/pull/2110
* Change NFTs styles when it is already loaded by @kkosiorowska in https://github.com/tallycash/extension/pull/2124
* Change styles for message in the wallet activity list by @kkosiorowska in …

Release 0.16.0

---

background/redux-slices/accounts.ts

Closes #2167 
This PR renames Evm type to AccountsByChainID.

Rename Evm type to AccountsByChainID

---

src/window-provider.ts

> 🇵🇱🤝🇭🇺 https://en.wikipedia.org/wiki/Pole_and_Hungarian_brothers_be
Fix logical error in wallet router whitelist elements should be || and not &&
Closes #2077

🤝 MM and Tally, two good friends when using uniswap

---

window-provider/index.ts

Add lyra to metamask whitelist

---

background/services/chain/utils/index.ts

Closes https://github.com/tallycash/extension/issues/2212

Handle `null` transaction.value from dapp transaction requests

---

src/window-provider.ts
window-provider/index.ts

Closes https://github.com/tallycash/extension/issues/2213
cc @greg-nagy because I am only 90% sure that we should be setting `this.currentProvider = provider`

Fix stargate.finance connectivity and interaction

---

src/window-provider.ts
window-provider/index.ts

Add support for Kwenta.io

---

background/services/ledger/index.ts

I think that our friction around this functionality could be an indicator that we are making too broad use of ethersTransactionFromTransactionRequest and it might need to be broken down into two similar but distinct functions.  However, a change of that size is out of the scope of this bugfix.

Fix OP Transactions not working when using Ledger

---

ui/_locales/en/messages.json
ui/components/AccountItem/AccountItemEditName.tsx
ui/components/AccountItem/AccountItemOptionsMenu.tsx
ui/components/AccountItem/AccountItemRemovalConfirm.tsx

cc @gasolin FYI I'm going attempt to go through the repo and snag the remaining strings we need to have localized this week.  multi-language support coming Soon:tm:
https://user-images.githubusercontent.com/94649004/191079156-f128e099-1466-4202-b288-5a04184b875b.mov

Localize AccountItem components

---

background/services/preferences/index.ts

Adds the optimism bridge to the list of known contracts.

Add optimism bridge to known contracts

---

ui/components/BonusProgram/BonusProgramModal.tsx
ui/components/Claim/ClaimDelegate.tsx
ui/components/NFTs/NFTsListItem.tsx
ui/components/NetworkFees/NetworkSettingsSelect.tsx
ui/components/NetworkFees/NetworkSettingsSelectLegacy.tsx
ui/components/Overview/AccountItem.tsx
ui/pages/Earn/PoolCard.tsx
ui/pages/SignDataDetailPanel.tsx
ui/public/index.css

Resolves https://github.com/tallycash/extension/issues/2012
- fix Sign data details styles
- add `.ellipsis` class and reuse it
- go to https://snapshot.org/#/saddlefinance.eth, connect wallet, then click Join
- details should be displayed nicely

Fix sign data styles

---

background/networks.ts
background/tests/networks.unit.test.ts

Make `toHexChainID` case-insensitive.

---

background/lib/nfts.ts
ui/components/NFTs/NFTsSlideUpPreviewContent.tsx

Resolves https://github.com/tallycash/extension/issues/2295

🔗  Add galxe link to achievements

---

ui/_locales/en/messages.json
ui/pages/ErrorFallback.tsx
ui/pages/Onboarding/OnboardingAddWallet.tsx
ui/pages/Onboarding/OnboardingImportMetamask.tsx
ui/pages/Onboarding/VerifySeed/SeedVerification.tsx
ui/pages/Onboarding/VerifySeed/VerifySeedError.tsx
ui/pages/Onboarding/VerifySeed/VerifySeedSuccess.tsx
ui/pages/PersonalSign.tsx
ui/pages/Settings.tsx
ui/pages/SignData.tsx
ui/pages/SingleAsset.tsx
ui/pages/Swap.tsx
ui/pages/TabNotFound.tsx
ui/pages/Wallet.tsx

As per usual to test this PR click through the wallet on the various localized pages and make sure nothing is out of place.
Specific pages to focus on would be seed verification during onboarding, swaps, and the OnboardingAddWallet page.

Localize Wallet, Generic Pages, Swaps, parts of Onboarding, misc. others.

---

background/services/chain/tests/index.unit.test.ts
background/services/indexing/index.ts
background/services/indexing/tests/index.unit.test.ts
background/tests/factories.ts
package.json
setupJest.env.ts
setupJest.ts

Also adds a setup test block to reset IndexedDB between tests

Add tests for Indexing service

---

background/services/ledger/index.ts

... introduced via 7b7bbd3aaee8dfb5f4
If both work, we're gucci!

Fix bugged Ledger use on Optimism and Arbitrum

---

window-provider/index.ts

Add swapr to metamask impersonation list

---

window-provider/index.ts

Impersonate MetaMask on zkSync

---

1

remove some extra file named 1 in the root dir

This seems like an accident?

---

background/services/name/resolvers/uns.ts

Fix outdated UNS resolver url

---

ui/components/Shared/SharedTooltip.tsx
ui/components/Shared/__tests__/SharedTooltip.test.tsx

Closes #2548 
This PR adds component tests for SharedTooltip.
Latest build: [extension-builds-2549](https://github.com/tallycash/extension/suites/9104407960/artifacts/422258503) (as of Thu, 03 Nov 2022 08:09:07 GMT).

Add tests for SharedTooltip

---

window-provider/index.ts

Connect wallet to [Blur](https://blur.io/collections)
Latest build: [extension-builds-2575](https://github.com/tallycash/extension/suites/9186707671/artifacts/428289283) (as of Tue, 08 Nov 2022 11:10:05 GMT).

Impersonate Metamask on blur.io

---

background/main.ts

> Quality time is an expression referring to how an individual [proactively](https://en.wikipedia.org/wiki/Proactively) interacts with another while they are together, regardless of the duration.
https://en.wikipedia.org/wiki/Quality_time
Because quality time is an important love language for any relationship. 
This is true for our users with our extension. 
It's more important to know how long a wallet modal was open than when it was opened.
- switch the env variables 
- start, install, import
- open UI > close UI
- check posthog that the `UI shown` event appears, and the payload feels correct
```
SUPPORT_ANALYTICS=true
ENABLE_ANALYTICS_DEFAULT_ON=true
USE_ANALYTICS_SOURCE="PR"
```
Closes #2610 
Latest build: [extension-builds-2668](https://github.com/tallycash/extension/suites/9473827809 …

🤖⏱ Quality Time: update UI open event to track open length not date

---

background/services/analytics/index.ts

So Long, and Thanks for All the Fish is the fourth book of the [Hitchhiker's Guide to the Galaxy](https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy) ["trilogy of six books"](https://en.wikipedia.org/wiki/The_Hitchhiker%27s_Guide_to_the_Galaxy_(book)#Series) written by [Douglas Adams](https://en.wikipedia.org/wiki/Douglas_Adams).
https://en.wikipedia.org/wiki/So_Long,_and_Thanks_for_All_the_Fish
https://www.youtube.com/watch?v=r03V9OEJlgg
This PR adds a URL to be opened at the time of uninstall. 
⚠️ This change will also have a website PR that will actually send the analytics event.
- set the feature flags and start 
- install
- remove
- you should have an open tab `https://tallyho.org/goodbye/?uuid=...`
```
SUPPORT_ANALYTICS=true
ENABLE_ANALYTICS_DEFAULT_ON=true …
```

🤖🐬 So long, and thanks for all the fish: Add uninstall tracking

---

background/constants/coin-types.ts
background/constants/networks.ts
background/lib/simple-hash_update.ts
background/services/chain/serial-fallback-provider.ts
background/services/name/resolvers/ens.ts
ui/_locales/en/messages.json
ui/components/Overview/NetworksChart.tsx
ui/components/TopMenu/TopMenuProtocolList.tsx
window-provider/index.ts
window-provider/wallet-connection-handlers.ts

Closes #2568
Latest build: [extension-builds-2701](https://github.com/tallycash/extension/suites/9620018608/artifacts/459316682) (as of Thu, 01 Dec 2022 21:58:31 GMT).

Avalanche fixes

---

ui/pages/Ledger/LedgerImportAccounts.tsx

Closes #1218 
Using the items array to determine selected accounts filtered addresses that were not in the currently visible page. New approach iterates over state selected paths and filters accounts with missing data.
Latest build: [extension-builds-2798](https://github.com/tallyhowallet/extension/suites/9910179130/artifacts/479065653) (as of Fri, 16 Dec 2022 14:27:23 GMT).

Fix connecting ledger addresses from different pages

---

ui/_locales/en/messages.json

Fix: typos
Latest build: [extension-builds-2891](https://github.com/tallyhowallet/extension/suites/10461039704/artifacts/517975912) (as of Thu, 19 Jan 2023 10:20:33 GMT).

Fix: typos

---

background/redux-slices/selectors/networks.ts
ui/components/TopMenu/TopMenuProtocolList.tsx

Resolves https://github.com/tallyhowallet/extension/issues/2969
Hide Goerli on the prod chains list
Latest build: [extension-builds-2972](https://github.com/tallyhowallet/extension/suites/10734958173/artifacts/538396198) (as of Thu, 02 Feb 2023 10:52:10 GMT).

Hide Goerli on prod chains list

---

background/redux-slices/tests/assets-utils.unit.test.ts
background/redux-slices/tests/assets.unit.test.ts
background/tests/factories.ts

Adds pending tests for #2976 
Latest build: [extension-builds-2979](https://github.com/tallyhowallet/extension/suites/10756494199/artifacts/539984002) (as of Fri, 03 Feb 2023 08:13:51 GMT).

Add tests for assets slice utils

---

background/services/provider-bridge/index.ts

Certain dApps send requests for `eth_accounts` before connection, this causes the wallet to prompt the user for permissions before interacting with the dApp and, in some cases, to generate multiple prompts, rendering the browser unusable.
Latest build: [extension-builds-2983](https://github.com/tallyhowallet/extension/suites/10784251627/artifacts/542002439) (as of Sun, 05 Feb 2023 03:19:26 GMT).

Fix eth_accounts handling for dApps without permissions

---

ui/_locales/en/messages.json
ui/components/NFTS_update/NFTListPortfolio.tsx

Minor improvements:
- Hide NFT banner during loading
- Change text on NFT page
Latest build: [extension-builds-3012](https://github.com/tallyhowallet/extension/suites/10939563597/artifacts/553425349) (as of Mon, 13 Feb 2023 08:45:32 GMT).

NFT copy improvements

---

ui/components/Shared/SharedAssetItem.tsx
ui/components/Wallet/WalletAccountBalanceControl.tsx

Resolves https://github.com/tallyhowallet/extension/issues/3024
- add ellipsis to asset name and symbol
Resolves https://github.com/tallyhowallet/extension/issues/3022
- add a gap between buttons
Latest build: [extension-builds-3025](https://github.com/tallyhowallet/extension/suites/10948599044/artifacts/554032109) (as of Mon, 13 Feb 2023 15:37:36 GMT).

UX fixes for token selector and Wallet page buttons

---

ui/components/GlobalModal/GlobalModal.tsx

Latest build: [extension-builds-3051](https://github.com/tallyhowallet/extension/suites/11048999147/artifacts/561443459) (as of Fri, 17 Feb 2023 15:06:35 GMT).

Add Blog Link

---

ui/pages/Settings.tsx

Latest build: [extension-builds-3053](https://github.com/tallyhowallet/extension/suites/11049765186/artifacts/561500582) (as of Fri, 17 Feb 2023 15:40:39 GMT).

Update Help Desk Link

---

.github/workflows/build.yml

This PR adds missing configuration for daylight API key.
Latest build: [extension-builds-3061](https://github.com/tallyhowallet/extension/suites/11105431688/artifacts/565651753) (as of Tue, 21 Feb 2023 09:43:39 GMT).

Fix issue for daylight API key 

---

ui/components/Overview/AbilitiesHeader.tsx
ui/pages/Abilities.tsx
ui/pages/Abilities/AbilityCard.tsx

Closes #3062 
This PR makes visual updates for the daylight feature. Changes:
- center the content
- add animation for a small banner
- updates for `box-shadow` and `background`
Gradients don't support transitions yet.  To create an animation effect, the opacity has been set on a container element and transition the opacity.
https://user-images.githubusercontent.com/23117945/220609546-5647679c-e31c-4bf7-9d29-ba415f8483bb.mov
Latest build: [extension-builds-3067](https://github.com/tallyhowallet/extension/suites/11132656144/artifacts/567663886) (as of Wed, 22 Feb 2023 11:55:11 GMT).

Daylight: Visual updates 

---

ui/components/AccountsBackup/RevealMnemonic.tsx
ui/components/AccountsBackup/ShowMnemonic.tsx
ui/components/AccountsBackup/ShowPrivateKey.tsx
ui/components/AccountsNotificationPanel/AccountsNotificationPanelAccounts.tsx
ui/components/Send/NFTCollectionAccordion.tsx
ui/components/Shared/SharedAccordion.tsx
ui/components/Shared/SharedButton.tsx
ui/components/TopMenu/TopMenuConnectedDAppInfo.tsx
ui/pages/Onboarding/Tabbed/ImportPrivateKey.tsx
ui/pages/Onboarding/Tabbed/ImportSeed.tsx

Implemented UI changes requested in: https://github.com/tahowallet/extension/pull/3266
- test if changes requested in linked PR were applied correctly
Latest build: [extension-builds-3270](https://github.com/tahowallet/extension/suites/12183072896/artifacts/643338009) (as of Wed, 12 Apr 2023 12:00:49 GMT).

Account backup UI fixes

---

ui/_locales/en/messages.json

Resolves https://github.com/tahowallet/extension/issues/3279
New error message
Latest build: [extension-builds-3293](https://github.com/tahowallet/extension/suites/12371508521/artifacts/657155829) (as of Thu, 20 Apr 2023 14:29:45 GMT).

New error for incorrectly decrypted JSON file

---

ui/_locales/en/messages.json

Closes https://github.com/tahowallet/extension/issues/3315
Latest build: [extension-builds-3354](https://github.com/tahowallet/extension/suites/12606909335/artifacts/674566777) (as of Tue, 02 May 2023 01:17:42 GMT).

Fix intro copy

---

background/services/chain/serial-fallback-provider.ts

The `if` branch was never getting hit since `ALCHEMY_RPC_CALL_PERCENTAGE` was set to `0` five months ago.  Lets get rid of code that isn't ever used.
Latest build: [extension-builds-3371](https://github.com/tahowallet/extension/suites/12776658798/artifacts/687232328) (as of Tue, 09 May 2023 15:03:10 GMT).

Remove Dead Serial Fallback Provider Code

---

rfb/rfb-5-control-compatile-addresses.md

The implementation section still needs a little more love, but the core of the ideas is there.
Latest build: [extension-builds-3385](https://github.com/tahowallet/extension/suites/13097193642/artifacts/710933010) (as of Tue, 23 May 2023 18:55:12 GMT).

RFB 5: Control-compatible addresses

---

background/main.ts
background/services/ledger/index.ts

Maybe fixes #3419.
Compare against #3420, and let's land the one that seems to work + be most correct while we debug further.
Latest build: [extension-builds-3432](https://github.com/tahowallet/extension/suites/13347808183/artifacts/729885779) (as of Sat, 03 Jun 2023 12:24:37 GMT).

Ledger Respect: Attempt #2 at fixing Ledger connection issues

---

ui/_locales/en/messages.json

Fixes the styling of this word in the UI
Latest build: [extension-builds-3547](https://github.com/tahowallet/extension/suites/14228014160/artifacts/798752712) (as of Wed, 12 Jul 2023 00:23:27 GMT).

Fix ChainList styling

---

.github/workflows/test-list/release-test-list.md

- add tests for private key import and export
- add tests for JSON keystore import
- add tests for seed phrase export
Latest build: [extension-builds-3548](https://github.com/tahowallet/extension/suites/14242544078/artifacts/799796864) (as of Wed, 12 Jul 2023 12:30:10 GMT).

Update release checklist

---

background/services/preferences/db.ts
background/services/preferences/defaults.ts

Resolves https://github.com/tahowallet/extension/issues/3521
As we are not able to find a replacement and this was broken for a while already let's just remove it.
Latest build: [extension-builds-3586](https://github.com/tahowallet/extension/suites/14735256207/artifacts/837282268) (as of Tue, 01 Aug 2023 17:00:01 GMT).

Remove failing yearn tokenlist

---

.github/ISSUE_TEMPLATE/BUG.yml
manifest/manifest.json
package.json

v0.62.0: Manifest v3 support plus a few other QOL changes

---

e2e-tests/regular/dapp-connect.spec.ts

Fixes a locator broken after implementing EIP6963
Latest build: [extension-builds-3792](https://github.com/tahowallet/extension/suites/35037468813/artifacts/2671680486) (as of Fri, 28 Feb 2025 16:36:17 GMT).

Update dApp connections e2e test

---

background/services/provider-bridge/index.ts
background/services/redux/index.ts

This "install id" is required to check eligibility
Latest build: [extension-builds-3795](https://github.com/tahowallet/extension/suites/35517773989/artifacts/2730831555) (as of Tue, 11 Mar 2025 15:21:11 GMT).

Expose claimer id on custom rpc method

---

background/networks.ts
background/redux-slices/selectors/uiSelectors.ts
background/redux-slices/ui.ts
background/services/campaign/index.ts
ui/_locales/en/messages.json
ui/components/TopMenu/TopMenuProtocolList.tsx
ui/components/Wallet/Banner/WalletCampaignBanner.tsx
ui/pages/Settings/SettingsAddCustomAsset.tsx
ui/pages/Wallet.tsx

Changes copy on banners, and tweaks naming on some functions/parameters
Latest build: [extension-builds-3799](https://github.com/tahowallet/extension/suites/35517599734/artifacts/2730809088) (as of Tue, 11 Mar 2025 15:18:18 GMT).

Minor campaign adjustments

---

background/services/campaign/index.ts
background/services/redux/index.ts

Calls mezo sats-drop API endpoint on dapp connection to mezo if the wallet install is eligible.
Latest build: [extension-builds-3802](https://github.com/tahowallet/extension/suites/35705420369/artifacts/2755204233) (as of Fri, 14 Mar 2025 19:41:17 GMT).

Call mezo api on mezo dapp connection to check sats-drop

---

background/lib/mezo.ts
background/services/campaign/index.ts
background/services/campaign/matsnet-nft.ts
background/services/nfts/index.ts
background/services/provider-bridge/index.ts
ui/components/Wallet/Banner/WalletCampaignBanner.tsx

Sets campaign URL endpoints and updates campaign state when detecting a confirmed NFT mint transaction.
Latest build: [extension-builds-3807](https://github.com/tahowallet/extension/suites/35875182965/artifacts/2776206553) (as of Tue, 18 Mar 2025 21:25:24 GMT).

Check campaign mint transactions

---

background/lib/gas.ts
e2e-tests/utils/assets.ts
provider-bridge/index.ts
src/popup.ts

This is a version of https://github.com/tahowallet/extension/pull/3777 with all commits signed! Thanks @tianzedavid!

chore: fix some typos
